### PR TITLE
Document week numbers

### LINKED ISSUE #283: Add docs article for week numbers
Currently we only have week numbers documented in the API docs, and a brief mention about it in the Internationalization article.

From the current existing articles, “Customization” seems like the most logical place to document this, or “Internationalization”. A whole new dedicated article for just this seems like an overkill, but would be the clearest for readers I bet (visible directly in the menu).

### PR DESCRIPTION
**Pull request by manolo**
Fixes #283

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/288)

### CODE REVIEW

**Comment by samiheikki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[docs/vaadin-date-picker-customization.adoc, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW1ainJjraGz6U0KqJ7:-KW1ainJjraGz6U0KqJ8:bfa04dd) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ff71aca78af682ca02e834369d06b811968c85b5/docs/vaadin-date-picker-customization.adoc#L8)):*
> ```AsciiDoc
> 
> [[vaadin-date-picker.week-customization]]
> = Setting Week Numbers
> ```

`Setting` sounds funny as the user doesn't have to set/calculate the week numbers, but just set them to show. I'd replace setting or even remove it.

---

*[docs/vaadin-date-picker-customization.adoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW1bDxZwKh80CgH3kUY:-KW1bDxZwKh80CgH3kUZ:bwlwp8q) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ff71aca78af682ca02e834369d06b811968c85b5/docs/vaadin-date-picker-customization.adoc#L12)):*
> ```AsciiDoc
> It can be enabled by setting the [propertyname]#showWeekNumbers# to `true`, and the [propertyname]#i18n.firstDayOfWeek# to `1`.
> 
> Weeks are numerated based on the ISO-8601 standard, so as the first week in the year is the week containing the day 4th of January.
> ```

I'd simplify: `..., so the first week of the year contains 4th of January`

---

*[docs/vaadin-date-picker-customization.adoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW1aYVq4PObzUyQlrka:-KW1aYVq4PObzUyQlrkb:btscchl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ff71aca78af682ca02e834369d06b811968c85b5/docs/vaadin-date-picker-customization.adoc#L17)):*
> ```AsciiDoc
> [source,html]
> ----
> <vaadin-date-picker show-week-numbers></vaadin-date-picker-light>
> ```

rename vaadin-date-picker-light

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-date-picker-customization.adoc, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW1ainJjraGz6U0KqJ7:-KW2gCBZ_qeXOKwDdSF1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ff71aca78af682ca02e834369d06b811968c85b5/docs/vaadin-date-picker-customization.adoc#L8)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> `Setting` sounds funny as the user doesn't have to set/calculate the week numbers, but just set them to show. I'd replace setting or even remove it.
</details>
Done.

---

*[docs/vaadin-date-picker-customization.adoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW1bDxZwKh80CgH3kUY:-KW2gBZW9iKxWK6DaoXj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ff71aca78af682ca02e834369d06b811968c85b5/docs/vaadin-date-picker-customization.adoc#L12)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> I'd simplify: `..., so the first week of the year contains 4th of January`
</details>
Done.

---

*[docs/vaadin-date-picker-customization.adoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW1aYVq4PObzUyQlrka:-KW2gBGb1jg49N1A8pH_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ff71aca78af682ca02e834369d06b811968c85b5/docs/vaadin-date-picker-customization.adoc#L17)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> rename vaadin-date-picker-light
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288)*

**Comment by samiheikki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-date-picker-customization.adoc, line 2 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW2pSlL1fopOEaIarbM:-KW2pSlL1fopOEaIarbN:b-o858fl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4555165b248e00b20f9265379a8228f30dac350d/docs/vaadin-date-picker-customization.adoc#L2)):*
> ```AsciiDoc
> ---
> title: Input Customization
> ```

Started to think is week numbers doc in a wrong file or is the title for it wrong. Showing week number doesn't fit into `Input Customization`. But then again it did not fit to any else better. I'd recommend either renaming this title or creating a new file for week numbers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-date-picker-customization.adoc, line 2 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW2pSlL1fopOEaIarbM:-KW2qKH7cbNokZ8p5erM:b-ntoi5j) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4555165b248e00b20f9265379a8228f30dac350d/docs/vaadin-date-picker-customization.adoc#L2)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Started to think is week numbers doc in a wrong file or is the title for it wrong. Showing week number doesn't fit into `Input Customization`. But then again it did not fit to any else better. I'd recommend either renaming this title or creating a new file for week numbers.
</details>
@jouni 's comment in #288 suggest to use this file (or i18n) instead of creating a new menu entry. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-date-picker-customization.adoc, line 2 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-KW2pSlL1fopOEaIarbM:-KW30Zl6c5gP8u_UBGt5:bc7nr9y) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4555165b248e00b20f9265379a8228f30dac350d/docs/vaadin-date-picker-customization.adoc#L2)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> @jouni 's comment in #288 suggest to use this file (or i18n) instead of creating a new menu entry. 
</details>
But should this title then be replaced to just `Customization`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/288#-:-KW320mG0CwBj5QjboSe:bnfp4nl)*

**Pull request merged**
