### PR TITLE
Document state attributes available for styling

### LINKED ISSUE #398: API docs: missing state attributes
Attributes such as `focused`, `focus-ring`, `disabled`, `invalid` are available on the host element for styling, but not listed in the API docs as of now.

API documentation should list all of the attributes available for styling.

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #398 

I haven't added `has-value` since it will be marked as private once #455 lands.
Will also rebase this and bump analysis after that.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/467)

### CODE REVIEW

**Comment by manolo** [comment]
You need to update `analysis.json` otherwise these changes are not available in api doc

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/467#-:-KyQ8jiJ3FXlsA2DCTl1:b-gb2sqr)*

**Comment by web-padawan** [comment]
Is #455 ready to merge yet? If so, I will rebase and then update `analysis.json` once that PR is in.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/467#-:-KyQG2Cs7KTDNR82Uvg8:b-7vagxt)*

**Comment by manolo** [comment]
merged, pls rebase and update analysis, remember to run `polymer analyze  [files that you want to document normally *.html ]   > analysis.json

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/467#-:-KyQkYHBxv9TPwHLIA2-:b-fr2tp5)*

**Comment by web-padawan** [comment]
Rebased.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/467#-:-KyQnaBrSxEFX-KKSitS:bncvegj)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/467#-:-KyZyUOLDtRAIIFLG2yC:b-uwkowd)*

**Pull request merged**
