### PR TITLE
Improve usage with scrollable containers

### LINKED ISSUE #345: Scrolling and clicking errors inside paper-dialog-scrollable
Hello,

I placed several vaadin-date-picker inside a paper-dialog-scrollable, and, if the dialog has a scrollbar, and then I open the vaadin-date-picker, the scrollbar in the date picker barely works and the selection of a date doesn't work at all.

I created a JSFiddle for this: https://jsfiddle.net/s8cj3h5p/1/

if the contents of the paper-dialog-scrollable don't generate a scrollbar, the component works fine. Like in here: https://jsfiddle.net/cd6muynk/3/

### PR DESCRIPTION
**Pull request by platosha**
Fixes #345

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/347)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-behavior.html, line 477 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-Kfl6yh-37_uMIjk057x:-Kfl6yh0_dUEmbuh_FKf:b-u01k28) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23e743691f127dcb9009f4893731dc02402d9941/vaadin-date-picker-behavior.html#L477)):*
> ```HTML
>       // We cannot use iron-resize event because 1- we fire it, 2- it's fired
>       // many times, 3- causes heigth and scroll issues in safari.
>       window.addEventListener('resize', this._boundOnResize);
> ```

Using `iron-resizable-behavior` would be cleaner.

---

*[test/overlay.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-Kfl4x9fuv8O25aZu_JE:-Kfl4x9fuv8O25aZu_JF:b4dn1lq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23e743691f127dcb9009f4893731dc02402d9941/test/overlay.html#L36)):*
> ```HTML
>       });
> 
>       it('should stop scroll events from bubbling outside the overlay', function() {
> ```

No point in testing that a non-bubbling event doesn't bubble.

---

*[test/scroller.html, line 104 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-Kfl5K04H5uMWk8OVvl3:-Kfl5K04H5uMWk8OVvl4:b-1eqwv9) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23e743691f127dcb9009f4893731dc02402d9941/test/scroller.html#L104)):*
> ```HTML
> 
>         scroller.$.scroller.scrollTop += 10;
>         scroller.$.scroller.dispatchEvent(new CustomEvent('scroll', {bubbles: false}));
> ```

The event occurs from changing the scrollTop. The explicit event shouldn't be fired here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347)*

**Comment by tomivirkki** [comment]
This approach has a minor drawback: the overlay doesn't change alignment on document scroll anymore (only on resize). I can live with that if there's no better way to make this work.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-:-Kfl9u348MFTVHznlDIC:bffnet9)*

**Comment by platosha** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-behavior.html, line 477 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-Kfl6yh-37_uMIjk057x:-KfzwboY8uh1CnYVXWjR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23e743691f127dcb9009f4893731dc02402d9941/vaadin-date-picker-behavior.html#L477)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Using `iron-resizable-behavior` would be cleaner.
</blockquote></details>

Done.

---

*[test/overlay.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-Kfl4x9fuv8O25aZu_JE:-KfzxGlrqCn2bfKrWZ4O:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23e743691f127dcb9009f4893731dc02402d9941/test/overlay.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No point in testing that a non-bubbling event doesn't bubble.
</blockquote></details>

Done.

---

*[test/scroller.html, line 104 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-Kfl5K04H5uMWk8OVvl3:-KfzxI6Ngo-1oOtf5NTC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23e743691f127dcb9009f4893731dc02402d9941/test/scroller.html#L104)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The event occurs from changing the scrollTop. The explicit event shouldn't be fired here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347)*

**Comment by platosha** [comment]
@tomivirkki realignment on scroll is back.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-:-KfzxRewsmC0plvotVFq:begk1uf)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-:-Kg-kpDgzyKuDyC2mBZV:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/347#-:-KgJmOylv01HVpWhUTmh:bnfp4nl)*

**Pull request merged**
