### PR TITLE
Use generic directive from angular2-polymer

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/133

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/182)

### CODE REVIEW

**Comment by manolo** [comment]
Angular tests broken in travis

<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> #### Use generic directive from angular2\-polymer
> 
> Connects to https://github.com/vaadin/components-team-tasks/issues/133
> 
> 
> </details>


---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182#-:-KH_HEygbgt3p3FYYjRB:-724677905)*

**Comment by tomivirkki** [comment]
*[test/angular2.html, line 138 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182#-KH_HSU3M6S4pGU8a-0i:-KH_HSU3M6S4pGU8a-0j:-1486104282) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3a816f39264cb3f784fad37d75c90ff77021a5a0/test/angular2.html#L138)):*
> ```HTML
>             datepicker.value = '2001-01-01';
> 
>             datepicker.async(done, 1);
> ```

The previous directives worked synchronously. Why does angular2-polymer require this timeout?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182)*

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/angular2.html, line 138 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182#-KH_HSU3M6S4pGU8a-0i:-KHcrgz6nlqzt84TNx7s:784641795) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3a816f39264cb3f784fad37d75c90ff77021a5a0/test/angular2.html#L138)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> The previous directives worked synchronously. Why does angular2-polymer require this timeout?</details>
Good question, the new directive had a `debounce` related with assigning the value for `ngControl` – I think I'm able to remove it, running tests now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182)*

**Comment by Saulis** [comment]
Tests should be fixed now.

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Angular tests broken in travis</details>


---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/angular2.html, line 138 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182#-KH_HSU3M6S4pGU8a-0i:-KHsDmh1yg-Zk_1Dr83k:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3a816f39264cb3f784fad37d75c90ff77021a5a0/test/angular2.html#L138)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Good question, the new directive had a `debounce` related with assigning the value for `ngControl` – I think I'm able to remove it, running tests now.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182#-:-KHsE_lLeM3cauS7a2bm:-459333864)*

**Comment by tomivirkki** [comment]
:lgtm: 

<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Tests should be fixed now.</details>


---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/182#-:-KHsgxHurScNrEU1I8j9:980077423)*

**Pull request merged**
