### PR TITLE
Window scroll needs to be listened at capture phase

### PR DESCRIPTION
**Pull request by tomivirkki**
Connected to #134 

If you place the component inside a scrolling container, the dropdown should also reposition/realign when the container is scrolled (as opposed to only realigning on window scroll).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/137)

### CODE REVIEW

**Comment by samiheikki** [comment]
Should there be a test for date-picker inside a scroll container?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-:-KDSSm4BcJK2bPs3g1hY:-1611158322)*

**Comment by tehapo** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-date-picker.html, line 482 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-KDSWYRaZLSYTfJUMHWy:-KDSWYRbzgjEbNqxwm9s:-1055249509) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a7627ca8b101adc9fc853c07de8340d3cfcad079/vaadin-date-picker.html#L482)):*
Could we use `contains` method here instead of recursion?
http://devdocs.io/dom/node/contains

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 482 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-KDSWYRaZLSYTfJUMHWy:-KDSXE5CXVJSeNP_5kOD:-898972756) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a7627ca8b101adc9fc853c07de8340d3cfcad079/vaadin-date-picker.html#L482)):*
Oh, I guess not now that I looked at the code again. :smile:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 482 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-KDSWYRaZLSYTfJUMHWy:-KDSXZc7-IpynFe0ACyh:-862251533) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a7627ca8b101adc9fc853c07de8340d3cfcad079/vaadin-date-picker.html#L482)):*
I think contains covers it, but is it supported on Android Chrome and iOS Safari?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 482 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-KDSWYRaZLSYTfJUMHWy:-KDSXudj5Z0tq6KXfgPJ:2127785018) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a7627ca8b101adc9fc853c07de8340d3cfcad079/vaadin-date-picker.html#L482)):*
I would guess that it probably works on mobile browsers also (as they are mostly based on same codebase as their desktop counterparts). Might be worth trying it out?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137)*

**Comment by tomivirkki** [comment]
Added the test. Also added a test that ensures the listener is removed correctly.

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 482 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-KDSWYRaZLSYTfJUMHWy:-KDSdv5bfxa0DCj0wAJO:1978736182) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a7627ca8b101adc9fc853c07de8340d3cfcad079/vaadin-date-picker.html#L482)):*
Seems to work. Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-:-KDSdzFAmqNAbgac5eql:511904070)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-:-KDT76-ytJif4CMl2ExA:1417088721)*

**Comment by tehapo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/137#-:-KDT8IKVUiYmELUoIZZq:1417088721)*

**Pull request merged**
