### PR TITLE
Prevent selection of empty cells in vaadin-month-calendar

### LINKED ISSUE #20: Empty slots in the beginning of month allow selection

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #20

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/22)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9lf7qfYaM3RI9mF0BR:-520601023) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
These two changes kind of patch the symptoms instead of fixing the thing that causes them. It would be wrong to have the "selected" attribute in one of the elements if it's actually not.

I'd suggest pushing null-values to the days array instead whenever "date.getMonth() === startMonth" applies. Then you wouldn't get the strange "selected" attribute in the element and wouldn't need the additional "&& e.target.textContent" check below either.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tomivirkki** [comment]
Additionally, target the pointer cursor to non-empty cells only

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-:-K9lh2KauDmUTL7nvdIL:62187037)*

**Comment by tehapo** [comment]
Good point. Fixed that also.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9lh_Oxxml6h3Z_G4Bg:521947662) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
You're absolutely right, except I feel like `undefined` is less Java-like value for the empty date cell. Pushed a better fix to the issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-:-K9lhvqkECjXbHn-v-4g:-1548283298)*

**Comment by tomivirkki** [comment]
*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9llJ6fhaIyCx8shd39:-207574260) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
What I meant was something like this https://github.com/vaadin/vaadin-date-picker/commit/63e4e322c54caf4b16e1f5aee6486a366b7d60d6

No need for a new function. In this case, undefined doesn't work, you need to use null.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9ltiMG9hIF6Yt2Q5WQ:1259240686) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
Done. Definitely a better solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9lucVRwdm7s_PTiTo-:1256910836) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
Oh, but there is a small error in the comparison.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tehapo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9lv9Mlox_tuT5S5ucy:601775875) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
There, now it should work in all cases and be a bit more clear.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tomivirkki** [comment]
*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9lwAXmagqCz79lK_3c:491735282) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
Could also add the null values in a separate loop to make it clearer https://github.com/vaadin/vaadin-date-picker/commit/e1146436c46d44655b790fb5aa038a6ce25708a2

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tomivirkki** [comment]
*[vaadin-month-calendar.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22#-K9lf7qfYaM3RI9mF0BQ:-K9m0KZMtmxPbxfSa7y1:-1681430411) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/398aa1e466c127fb67a1490e79c3a2a4f90ba757/vaadin-month-calendar.html#L66)):*
Oh, nevermind. The date approach is better. lgtm.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/22)*

**Pull request merged**
