### PR TITLE
Add icon to vaadin-date-picker-icons for valo-theme

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Previous icon set:
screen shot 2017-07-26 at 13 32 42

Updated icon set:
screen shot 2017-07-26 at 14 07 39

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/405)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Valo icon set should go to the Valo theme

**Comment by manolo** [comment]
Good point, so iiuc you suggest to have a font-face specific for valo.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/405#-:-KpydQOZN_SoH9q9xNy5:bno6l8j)*

**Comment by tomivirkki** [comment]
Yep, the components should know/include nothing about a specific theme. The used font family can be overridden in the theme to match a custom font face defined by the theme.

**Comment by manolo** [comment]
Ok, abandoning this in favour of a PR in themes. Thanks Tomi

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/405#-:-KpymRaB4qJeZA531c1I:ba4ry11)*

**Comment by manolo** [comment]
moved this to vaadin-themes

**Pull request closed without merging**
