### PR TITLE
Replace Moment.js with an alternative i18n solution

### PR DESCRIPTION
**Pull request by tehapo**
A minimal solution for internationalization, which uses the core ideas from https://github.com/vaadin/vaadin-date-picker/pull/65 by @manolo, while leaving out some parts that could be added at a later point if needed.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/84)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm_strong: 

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/84#-:-KC07PYdL5PT8Qb9PwM-:-1868698381)*

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/84)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/84#-:-KC0DdzIq1mndhMJJsNo:1417088721)*

**Comment by manolo** [comment]
Please close this PR and rebase over #95

**Pull request closed without merging**
