### PR TITLE
Create ISSUE_TEMPLATE.md

### LINKED ISSUE #227: Add an ISSUE_TEMPLATE.md
### Proposed ISSUE_TEMPLATE.md

**NOTE: This issue template was sourced from the PolymerElements repositories**

The only thing I modified was the Live Demo, which now uses `vaadin-date-picker`.

If everyone's alright with adding this then I'll open up a PR.

```md
### Description
<!-- Example: The `paper-foo` element causes the page to turn pink when clicked. -->

### Expected outcome

<!-- Example: The page stays the same color. -->

### Actual outcome

<!-- Example: The page turns pink. -->

### Live Demo
<!-- Example: https://jsbin.com/qojiwugino/edit?html,output -->

### Steps to reproduce

<!-- Example
1. Put a `paper-foo` element in the page.
2. Open the page in a web browser.
3. Click the `paper-foo` element.
-->

### Browsers Affected
<!-- Check all that apply -->
- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
```

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #227

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/246)

### CODE REVIEW

**Comment by platosha** [comment]
Vertical spaces are not consistent: some headers have an empty line after, the others have not.

Maybe remove the empty lines after headers?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-:-KT9kzIEfccerbF7Ucpa:b-x6q97e)*

**Comment by samiheikki** [comment]
Did a new issue based on this template to combo-box: https://github.com/vaadin/vaadin-combo-box/issues/318.

I noticed that steps to reproduce title is pretty much useless if I provide a live demo. Can the live demo title be changed to `Live demo /  Steps to reproduce`.

**Comment by Saulis** [comment]
Removed the empty lines. @samiheikki I'd say we want to encourage ppl always to provide both a live demo and steps to reproduce the error using that live demo. In trivial cases the steps to reproduce might be pretty useless, but in those cases reporter can just ignore writing the steps.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-:-KTEOfqC09zsx9DskFPi:b-j0vl3x)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[ISSUE_TEMPLATE.md, line 1 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-KTEoBHh6zr8sx-g7qVD:-KTEoBHh6zr8sx-g7qVE:bvvesiu) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1f4fa7a385199efb1492178e7c79bd4acf7652e9/ISSUE_TEMPLATE.md#L1)):*
> ```Markdown
> ```md
> ```

Is it really necessary to wrap the template in three graves code block?

Wouldn’t it turn all the issues into blocks of markdown code?

---

*[ISSUE_TEMPLATE.md, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-KTEouwjgu4F0tkU41EL:-KTEouwjgu4F0tkU41EM:brhumzt) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1f4fa7a385199efb1492178e7c79bd4acf7652e9/ISSUE_TEMPLATE.md#L30)):*
> ```Markdown
> - [ ] iOS Safari
> - [ ] Android Chrome
> ```
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246)*

**Comment by Saulis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[ISSUE_TEMPLATE.md, line 1 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-KTEoBHh6zr8sx-g7qVD:-KTJhilO5HyQnVGzMSjB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1f4fa7a385199efb1492178e7c79bd4acf7652e9/ISSUE_TEMPLATE.md#L1)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Is it really necessary to wrap the template in three graves code block?
> 
> Wouldn’t it turn all the issues into blocks of markdown code?
</details>
Done.

---

*[ISSUE_TEMPLATE.md, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-KTEouwjgu4F0tkU41EL:-KTJhi_6eH-bjk71fYo2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1f4fa7a385199efb1492178e7c79bd4acf7652e9/ISSUE_TEMPLATE.md#L30)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Same here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/246#-:-KTJloO9WVb4OjdRp-GH:bnfp4nl)*

**Pull request merged**
