### PR TITLE
Updated i18n object apidoc

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/125)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 266 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-KD8079iankgH3yoK1VT:-KD8079iankgH3yoK1VU:456629619) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23cfd13ff2dba164472a9e6f005f337d639ac10e/vaadin-date-picker.html#L266)):*
Can you fit weekdays on one line? Is there a need to wrap this line?

---

*[vaadin-date-picker.html, line 275 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-KD80SDqNHgTug9hnGPH:-KD80SDqNHgTug9hnGPI:851589901) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23cfd13ff2dba164472a9e6f005f337d639ac10e/vaadin-date-picker.html#L275)):*
Though doesn't matter with default styles, but today and cancel button labels are titles. First letters should be capitalised.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 266 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-KD8079iankgH3yoK1VT:-KD86GqLI04qv-LhRP5A:-1421298040) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23cfd13ff2dba164472a9e6f005f337d639ac10e/vaadin-date-picker.html#L266)):*
Unfortunately they don't fit on one line in the iron-component-page view.

---

*[vaadin-date-picker.html, line 275 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-KD80SDqNHgTug9hnGPH:-KD86b6t3RhhD6gSbaVK:-1125734010) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23cfd13ff2dba164472a9e6f005f337d639ac10e/vaadin-date-picker.html#L275)):*
Yeah, they're uppercased by paper-button so it doesn't matter here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 275 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-KD80SDqNHgTug9hnGPH:-KD88nKU8GbPOl8MFhHB:-1820822613) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23cfd13ff2dba164472a9e6f005f337d639ac10e/vaadin-date-picker.html#L275)):*
But semantically these words are titles, so it's better to have them in proper title case. Ok, not a blocker for me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 275 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-KD80SDqNHgTug9hnGPH:-KD8BLceQQ2IQZEb0iox:1452475774) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/23cfd13ff2dba164472a9e6f005f337d639ac10e/vaadin-date-picker.html#L275)):*
There you go. Now they're upper cased in the data also :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125)*

**Comment by manolo** [comment]
I would adapt font sizes a little bit in index.html such as in uploader

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-:-KD8UGdOQn80er1foWH_:1871754482)*

**Comment by tomivirkki** [comment]
Scaled down the code property font. Now the month names also fit on one line :thumbsup: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-:-KD8X4oMij300qz3654f:661669429)*

**Comment by tomivirkki** [comment]
* weekdays I mean

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-:-KD8XWVxeBfXog2HpyAh:32063062)*

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/125#-:-KD8YQlDo9k5VE35Kujl:1417088721)*

**Pull request merged**
