### PR TITLE
Add support for an errorMessage

### LINKED ISSUE #224: Date Picker doesn't display error messages
Seeing how `vaadin-combo-box` and the paper components generally allow for an error-message I would expect the date-picker to be the same.

```html
<vaadin-date-picker required error-message="Some error message"></vaadin-date-picker>
```

### PR DESCRIPTION
**Pull request by nick-woodward**
[Live Demo](https://jsbin.com/yetugoweka/edit?html,output)

Closes #224

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/228)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[test/form-input.html, line 119 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/228#-KQPMpSweAKWWytkbjFb:-KQPMpSweAKWWytkbjFc:b-az16u5) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5c48e379a6c28bb029f5d174a213e825f2c00856/test/form-input.html#L119)):*
> ```HTML
>         datepicker.errorMessage = 'Not cool';
>         flush(function() {
>           var error = datepicker.querySelector('paper-input-error');
> ```

Normal querySelector won't work when targeting stuff hidden inside the root when native shadow DOM is enabled.
Use `datepicker.$$('paper-input-error')` instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/228)*

**Comment by nick-woodward** [comment]
Updated to use `$$` thanks for looking at this PR @tomivirkki!

**Comment by tomivirkki** [comment]
Hey, thanks for the contribution! :lgtm: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/228#-:-KQUk5M2b7JF00TQBwSf:b2qcyr7)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/228)*

**Pull request merged**
