### PR TITLE
Relaxed dependency restrictions

### LINKED ISSUE #159: Relax dependency restrictions to use latest versions where possible

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #159

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/160)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 146 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160#-KEttASlssVWqy7vM1nT:-KEttASlssVWqy7vM1nU:-121952584) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b6a9212be0d8cadc77599f6da9b9fd2d277c2c82/vaadin-date-picker.html#L146)):*
could you change commit message to include this modification

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 146 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160#-KEttASlssVWqy7vM1nT:-KF2yVmsHvGK_F28k5b4:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/eced570729acf13ba11fc94ee797f59eb9336269/vaadin-date-picker.html#L146)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 146 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160#-KEttASlssVWqy7vM1nT:-KF3hGRimbZIPOO0x_bV:175891237) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/eced570729acf13ba11fc94ee797f59eb9336269/vaadin-date-picker.html#L146)):*
Removed the mentioned changes because https://github.com/vaadin/vaadin-date-picker/pull/161 fixes the issue with clear icon "the right way"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-date-picker.html, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160#-KF3zxfopOwP4QSw6kp-:-KF3zxfopOwP4QSw6kp0:1321863104) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b696e7dd5f7a7d1d90d845ef5419bb86504b07dc/vaadin-date-picker.html#L72)):*
Here you have a css change still

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160#-KF3zxfopOwP4QSw6kp-:-KF4-98PAsXTc7fcxIEq:-2124979546) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b696e7dd5f7a7d1d90d845ef5419bb86504b07dc/vaadin-date-picker.html#L72)):*
Yep, this is actually a fix for regression caused by iron-dropdown version upgrade

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/160#-:-KF4-VWBD7jCk8Sq7zfe:1417088721)*

**Pull request merged**
