### PR TITLE
Switch from JSHint + JSCS to ESLint

### PR DESCRIPTION
**Pull request by limonte**
Related to: https://github.com/vaadin/vaadin-split-layout/pull/31

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/311)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/scroller.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-KXnzMlHAe617z8H605S:-KXnzMlHAe617z8H605T:brr0r58) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3ebaf5cb8a854b439178538c5364e0602b8fcf3c/test/scroller.html#L83)):*
> ```HTML
>           } else {
>             scroller.$.scroller.scrollTop -= scroller.itemHeight * 3.7;
>             scroller.async(scrollUp, 40);
> ```

Can there be a better fix for than increasing async?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/scroller.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-KXnzMlHAe617z8H605S:-KXnzfM5RUL9tIYPtOVY:b-1ht1q0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3ebaf5cb8a854b439178538c5364e0602b8fcf3c/test/scroller.html#L83)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can there be a better fix for than increasing async?
</blockquote></details>

I'm trying to understand the reason. This test is failing in 1 from 10 cases and always passes locally, so it's pretty hard to say what actually happens. Any help here will be appreciated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311)*

**Comment by tomivirkki** [comment]
*[test/.eslintrc.json, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-KYE4W3qpnNOT3kHPDum:-KYE4W3qpnNOT3kHPDun:b-5c2jfw) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3ebaf5cb8a854b439178538c5364e0602b8fcf3c/test/.eslintrc.json#L1)):*
> ```JSON
> {
> ```

Ouch, wouldn't want to enumerate all possible global variables in a separate file.
Would it be an option to switch "no-undef " off instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311)*

**Comment by tomivirkki** [comment]
Ok it seems that some rules (that the previous linter did catch) are ignored now.
Like for example we have a convention (same as Polymer team has) not to have `"`'s for quote marks in JS code (only `'`'s).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYE9YcCepoYlYNT0yql:btfgs1f)*

**Comment by limonte** [comment]
Fixed by "quotes": ["error", "single"]

---

Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/.eslintrc.json, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-KYE4W3qpnNOT3kHPDum:-KYECaMa6vfvwSFGf9L0:bkus4xt) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3ebaf5cb8a854b439178538c5364e0602b8fcf3c/test/.eslintrc.json#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Ouch, wouldn't want to enumerate all possible global variables in a separate file.
Would it be an option to switch "no-undef " off instead?
</blockquote></details>

You're right,  "no-undef: 0" for test subdirectory is totally fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYEBvwv2HdsqGrTKRsg:bc1auzt)*

**Comment by limonte** [comment]
Reviewed 13 of 16 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/scroller.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-KXnzMlHAe617z8H605S:-KYEDiMqbvjH8q7Nra9W:bmcigix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/3ebaf5cb8a854b439178538c5364e0602b8fcf3c/test/scroller.html#L83)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I'm trying to understand the reason. This test is failing in 1 from 10 cases and always passes locally, so it's pretty hard to say what actually happens. Any help here will be appreciated.
</blockquote></details>

I removed this change from this PR as non-related.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311)*

**Comment by tomivirkki** [comment]
I mean there are other rules as well (not just the quotes) that are different. Is there any way to make sure we're not missing some of them?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYEDwtaLEEbBLJiiRy7:b-gq7l6q)*

**Comment by limonte** [comment]
We can't be sure. But no worries, we're totally synced with Polymer team:  https://github.com/Polymer/polymer/blob/master/.eslintrc.json

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYEKAx8Ihb5TsGONeXz:b5fa30g)*

**Comment by tomivirkki** [comment]
They use Eslint in the core project but for elements they use polylint https://github.com/PolymerElements/paper-input/blob/master/.travis.yml#L6

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYEOxhoZ0dhi6Fkz748:b-86m2v9)*

**Comment by limonte** [comment]
polylint seem to be unmaintained, I believe we shouldn't use it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYKfEZsAqrfM70mg4tM:b9lqwlo)*

**Comment by limonte** [comment]
As dicsussed I'll try to add polylint in addition to ESLint in separated PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311#-:-KYNfaxKC7PUbnD6M_Mh:b-xj9jg1)*

**Comment by tomivirkki** [comment]
Reviewed 12 of 16 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/311)*

**Pull request merged**
