### PR TITLE
Removed custom css properties for now

### LINKED ISSUE #141: Remove element specific CSS variables
To be on the safe side, we’ll only provide mixins in 1.0.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #141

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/146)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-overlay.html, line 157 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-KDYJIiNuEh1ap5nLcZt:-KDYJIiNuEh1ap5nLcZu:1094295258) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2c0d98b38f940752ff23328b7a9293c3adf29478/vaadin-date-picker-overlay.html#L157)):*
`border-left-color` can't be customised anymore. Deliberate?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/index.html, line 118 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-KDYKHbR3tv3-1SoBLR7:-KDYKHbR3tv3-1SoBLR8:-287163285) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2c0d98b38f940752ff23328b7a9293c3adf29478/demo/index.html#L118)):*
Would it be more consistent to use --paper-gray-something?

---

*[demo/index.html, line 120 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-KDYKN8MP1Y-8wcHIqpH:-KDYKN8NyLgUEftwwgmi:-287163285) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2c0d98b38f940752ff23328b7a9293c3adf29478/demo/index.html#L120)):*
Would it be more consistent to use --paper-gray-something?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146)*

**Comment by tomivirkki** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 157 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-KDYJIiNuEh1ap5nLcZt:-KDYREej4LwBkt9nTCKn:-1876060151) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2c0d98b38f940752ff23328b7a9293c3adf29478/vaadin-date-picker-overlay.html#L157)):*
Done. Added a new mixin for it. It's the color for the year scroller arrow indicator.

---

*[demo/index.html, line 118 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-KDYKHbR3tv3-1SoBLR7:-KDYR5ueK6JNQQ1McXzh:-188583265) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2c0d98b38f940752ff23328b7a9293c3adf29478/demo/index.html#L118)):*
See below

---

*[demo/index.html, line 120 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-KDYKN8MP1Y-8wcHIqpH:-KDYPrsiEeouScmqFspu:-979370869) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2c0d98b38f940752ff23328b7a9293c3adf29478/demo/index.html#L120)):*
The color is --dark-theme-secondary-color which is fixed in the main theme file https://github.com/PolymerElements/paper-styles/blob/master/default-theme.html#L60 and there's no value for it in https://github.com/PolymerElements/paper-styles/blob/master/color.html

Can't use "--dark-theme-secondary-color" here as value either because it's changed few lines above and that would create a conflict. I think it's ok to demonstrate use of inline color values also (not only variables)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-:-KDYRqwJAekQitszmBLy:1417088721)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-:-KDYTBkvl1bquBgR3tbx:1417088721)*

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-:-KDYYq2946IhOQRR4fjo:1417088721)*

**Comment by tehapo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/146#-:-KDYaoiQK8YvT6xphOTa:1417088721)*

**Pull request merged**
