### PR TITLE
Prepare for the P3 conversion

### LINKED ISSUE #519: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #519

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/529)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 22 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/529#-:-L9Eizd927V-CfEnpDJ9:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/529#-L9KLuhi0eWlX9jzPmmQ:-L9KLuhj6DvxykWPoEJQ:bohcz2v) (no related file):*
The fullscreen mode (on mobile) doesn't look right

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/529)*

**Comment by web-padawan** [comment]
Review status: 15 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/529#-L9KLuhi0eWlX9jzPmmQ:-L9KVmBG-oPF8XY6cseR:b-pq2ouo) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The fullscreen mode (on mobile) doesn't look right
</blockquote></details>

Released `vaadin-lumo-styles` 1.0.0-pre.3 with the fix (rebased on top of master). Now fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/529)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 19 of 26 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/529#-:-L9KfI21ADWvOATlYuBN:bnfp4nl)*

**Pull request merged**
