### PR TITLE
Add initial implementation of <vaadin-month-calendar>

### PR DESCRIPTION
**Pull request by tehapo**
Connects to #4  

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/7)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Some tests are failing on iOS

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-month-calendar.html, line 61 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WBqiOSYf7vK_QjqMq:-K9WBqiOSYf7vK_QjqMr:-947373988) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L61)):*
Since these three are public properties, they should have api docs. Or should these be private instead?

---

*[vaadin-month-calendar.html, line 83 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WEAOPEf2AbyyuCmQU:-K9WEAOPEf2AbyyuCmQV:129755128) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L83)):*
This if-check feels unnecessary

---

*[vaadin-month-calendar.html, line 130 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WEU2_P6ls_t33NzWQ:-K9WEU2_P6ls_t33NzWR:-1960481798) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L130)):*
Don't know how heavy Polymer.dom() is but doing it on every loop might slow things down

---

*[vaadin-month-calendar.html, line 137 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WG8s9oBMLL721ArVT:-K9WG8s9oBMLL721ArVU:-263992422) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L137)):*
Using the data-attribute adds a lot of code in this file. But I guess a custom property for a <div> would be worse?

---

*[vaadin-month-calendar.html, line 174 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WDVIENjFe0YGWqi6A:-K9WDVIENjFe0YGWqi6B:-574039899) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L174)):*
Looks like IE doesn't have full support for classList. Could use this.toggleClass api instead

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-:-K9WAOjhvxBunPrDF9r8:211886138)*

**Comment by tehapo** [comment]
Looks like MockInteractions.tap() does not work properly with iOS, added a workaround.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[vaadin-month-calendar.html, line 61 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WBqiOSYf7vK_QjqMq:-K9WXwmecjxitK_Zwp64:-382456306) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L61)):*
Made all localization related properties private for now until we actually start adding localization support.

---

*[vaadin-month-calendar.html, line 83 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WEAOPEf2AbyyuCmQU:-K9WYAtuId5wPTO5nciJ:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L83)):*
Done.

---

*[vaadin-month-calendar.html, line 130 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WEU2_P6ls_t33NzWQ:-K9WYJMUUeazl1Fi9sAt:1509009250) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L130)):*
Good point, moved outside of the loop and modified to append elements in a batch.

---

*[vaadin-month-calendar.html, line 137 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WG8s9oBMLL721ArVT:-K9WYU5uHi__7lkkdBAW:-22900308) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L137)):*
Not sure what would be best option, but to me using a data attribute seems better than a custom property on a standard HTML element.

---

*[vaadin-month-calendar.html, line 174 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WDVIENjFe0YGWqi6A:-K9Wh2GgAZ1emUuks2go:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/5708532e7a35ffbb7efa55637433b0a0c7fa0c13/vaadin-month-calendar.html#L174)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-:-K9Wh2pf7jCR7C051kcB:919564425)*

**Comment by tomivirkki** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 3 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WkQccmjRhBhiZ63mm:-K9WkQccmjRhBhiZ63mn:1697983934) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b284db5aba18b05abc92b314e0b1a120c92751c5/vaadin-date-picker-overlay.html#L3)):*
Import to vaadin-month-calendar.html needed here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7)*

**Comment by tehapo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 3 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7#-K9WkQccmjRhBhiZ63mm:-K9Wp7VCp7adloSZfQEf:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b284db5aba18b05abc92b314e0b1a120c92751c5/vaadin-date-picker-overlay.html#L3)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/7)*

**Comment by tehapo** [comment]
Abandoning this in favor of already merged version of the same functionality.

**Pull request closed without merging**
