### PR TITLE
Improved documentation for the latest features

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/59)

### CODE REVIEW

**Comment by magi42** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBN9IRWNYnBulau-Jzu:-KBN9IRXEk55poDXRvcm:1803136967) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L10)):*
* Use `[vaadinelement]` for top-level elements, that is, those having the vaadin- prefix.
* If there's multiple locales, they are probably different, so rather just "_multiple locales_".

OK, it has support, but does the developer need to set the locale explicitly or does the element detect and use browser's locale preference automatically? If it doesn't, it would be good to describe in this section how it can be done.

---

*[docs/vaadin-date-picker-features.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBN9w9P0pRDSwlP3whH:-KBN9w9P0pRDSwlP3whI:1534407657) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L11)):*
Rather use active voice here:
```
You can adjust the element to a specific locale with the [propertyname]#locale# property.
```

---

*[docs/vaadin-date-picker-features.adoc, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNAMbcpSFjjm3W7WZL:-KBNAMbdbji1QDZ2BRN-:-808258447) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L12)):*
* If talking about a class, use `[classname]#String#`, but here it's perhaps better to talk about strings as concept, so just have it lower-case.
* It's a bit technical and vague to talk about a locale format accepted by some library. I'd separate this into two things:
 * "``The value should be a locale identifier given in the BCP 47 format, such as `en-gb`, `fi`, or `es`.``"
 * "`The date picker supports all the locales supported by the link:http://momentjs.com/[moment.js] library. Please refer to its website for the complete list of supported locales.`"

---

*[docs/vaadin-date-picker-features.adoc, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNAftwDZvtIn3_YhZI:-KBNAftwDZvtIn3_YhZJ:2129422876) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L13)):*
* Comma after introductory clause: "_Once set,_"
* No need to say "given"
* Use `[vaadinelement]` here (and in other similar occurrences). 

---

*[docs/vaadin-date-picker-features.adoc, line 22 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNDmZ4lZ0IiTtkkMDH:-KBNDmZ4lZ0IiTtkkMDI:-430295660) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L22)):*
* Section names should be capitalized: Initial Position
* It's a zero-level section name (=), but there may only be one such in an AsciiDoc file, so this would not even compile (without errors). If you want to have the section as a same level as the Localization section, you need to move it to a separate file.

---

*[docs/vaadin-date-picker-features.adoc, line 24 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNDNd2GzBwX2N66FVM:-KBNDNd2GzBwX2N66FVN:625591090) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L24)):*
* `[vaadinelement`]
* Comma missing after introductory clause: "..._dropdown, it_..."
* "selected" is rather strange here, as no one has selected anything yet. Rather talk about "initial date".

---

*[docs/vaadin-date-picker-features.adoc, line 30 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNELMq8wQM20LkzHMz:-KBNELMq8wQM20LkzHN-:-415580456) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L30)):*
As an API this looks a bit odd. It's not just any position, but a date, so why not talk about dates?

Also having an "initial-date" attribute looks a bit odd. I don't know what design idea is behind this or what is the convention with Polymer elements, but at least in basic HTML inputs, initial values are given with a "value" attribute, which then actually changes when user selects something different.

---

*[docs/vaadin-date-picker-overview.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNFEBYC4X9d6Q_y68K:-KBNFEBYC4X9d6Q_y68L:-425320874) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L10)):*
* `[vaadinelement]`

---

*[docs/vaadin-date-picker-overview.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNFQv4Un-Y4Cdvtqqt:-KBNFQv4Un-Y4Cdvtqqu:768653372) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L11)):*
* I so associate "UI" as the entire UI, although in general it's true that also smaller elements of an UI have a UI. Nevertheless, I'd rather talk about "the picker" or something.
* Maybe it's better to split this into two sentences. I'd also rephrase a bit: "_.../tapped. It has two display modes, full-screen or desktop, which is determined according to the size of the screen._"

---

*[docs/vaadin-date-picker-overview.adoc, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNGNzfPLdnX6UKhl2R:-KBNGNzfPLdnX6UKhl2S:1355531163) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L12)):*
* I'd add: "..._and then select a date_."

---

*[docs/vaadin-date-picker-overview.adoc, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNGU5VLo2GahOIEQMN:-KBNGU5VLo2GahOIEQMO:-989512859) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L14)):*
* Do not use contractions -> rather "The picker has a"
* Does the "today" button just jump to the current month, but does not select the current day?
* You could separate the cancel button to a separate sentence: ". A cancel button allows closing..."
* I don't know what the buttons looks like, but maybe it should be a "today button" and "close button", no need to use quotes for those. "Today" sort of begs them more, while a "close button" is a more common concept.
* Now it reads as if the "dropdown closes on the dropdown footer" – how does it "close on" there? I assume the cancel button is in the dropdown footer, so maybe rather: "A close button in the footer allows closing the dropdown."

---

*[docs/vaadin-date-picker-overview.adoc, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNOwu_fTICwUktMWi-:-KBNOwu_fTICwUktMWi0:2107313237) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L21)):*
Use [vaadinelement] here as well. I hope it works OK within a title

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBN9IRWNYnBulau-Jzu:-KBRdsPaVR8yCzAivLnW:-1244241725) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L10)):*
Done. The following sentences state that the user adjusts the locale.

Automatic locale detection has been discussed but isn't currently included and will not be included into any specific Vaadin element but possibly a separate utility i18n package.

---

*[docs/vaadin-date-picker-features.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBN9w9P0pRDSwlP3whH:-KBRemSrr2RTWXuaUh9b:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L11)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNAMbcpSFjjm3W7WZL:-KBReo8p6vy6yQUQcMca:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L12)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNAftwDZvtIn3_YhZI:-KBRep0GSdJEMvE3mLUF:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L13)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 22 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNDmZ4lZ0IiTtkkMDH:-KBRerLzE29MEFHJzI7M:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L22)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 24 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNDNd2GzBwX2N66FVM:-KBRf6fkGPct33y-x4P_:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L24)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 30 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNELMq8wQM20LkzHMz:-KBRajGGsUZOUISzd2lN:255517053) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-features.adoc#L30)):*
initialValue would indeed sound like some pre-selected value which isn't the case here. I hope the revised documentation better describes what the property is meant for.

---

*[docs/vaadin-date-picker-overview.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNFEBYC4X9d6Q_y68K:-KBRf7et_wkD6bee2lp9:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L10)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNFQv4Un-Y4Cdvtqqt:-KBRfDEfry43TMdVSi7W:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L11)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNGNzfPLdnX6UKhl2R:-KBRfDcwtKskQn9YdMj6:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L12)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNGU5VLo2GahOIEQMN:-KBRfHe0r_eBQ-yaZJaM:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L14)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNOwu_fTICwUktMWi-:-KBRfIGNh8OvvoMBpkVc:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L21)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by magi42** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSVRosciMg-_BEUoxI:-KBSVRosciMg-_BEUoxJ:-1175181560) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L12)):*
* Names don't get articles, and don't want to use the lower-case name to start the sentence, hence  `The [vaadinelement]#vaadin-date-picker# element`

---

*[docs/vaadin-date-picker-features.adoc, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSX6A8yPyR_FUqI4bj:-KBSX6A8yPyR_FUqI4bk:2068800288) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L28)):*
Maybe rather: "_When the [vaadinelement]#vaadin-date-picker# has no selected value and the dropdown is opened, it automatically scrolls to the current month._"

---

*[docs/vaadin-date-picker-features.adoc, line 29 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSYhFuje9N88XMvj4B:-KBSYhFvxCSURSCJIpnX:345530761) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L29)):*
* Article missing ("the ... property") and rephrase: "_You can make it scroll to another month by setting the [propertyname]#initialPosition# property to a date in that month."

---

*[docs/vaadin-date-picker-features.adoc, line 31 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSZRnmYfE85a7Lt629:-KBSZRnnUruWwR0qSdG5:1473342474) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L31)):*
You can leave out "Note" – there's two cases and this sentence describes the other one.

What confuses me here is the ambiguity that "selected" can mean both "selected by the user" and "selected programmatically". Also, "if" is often confused with "when", in which case this expression could be interpreted: "When the user selects a value, the picker always scrolls..."

Maybe the following would make the distinction better: "When [vaadinelement]#vaadin-date-picker# already has a value selected, opening the dropdown always scrolls..."

---

*[docs/vaadin-date-picker-overview.adoc, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNOwu_fTICwUktMWi-:-KBSi0E-rls1xLut8LVi:998216915) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L21)):*
There's #s missing: `[vaadinelement]#vaadin-date-picker#`

---

*[docs/vaadin-date-picker-overview.adoc, line 11 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSgjV-bJZwSfalfkS5:-KBSgjV-bJZwSfalfkS6:-681860142) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-overview.adoc#L11)):*
Hmm, rather use more formal "clicked or tapped".

---

*[docs/vaadin-date-picker-overview.adoc, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSh03acRO9kSRMm7Gv:-KBSh03acRO9kSRMm7Gw:1886814841) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-overview.adoc#L12)):*
Hmm, "which is determined" now refers to the two display modes.

Rather: "...desktop. The display mode to use is determined..."

---

*[docs/vaadin-date-picker-overview.adoc, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBShYO771hetCg0bzLH:-KBShYO8dW7kJIf4c45D:1885792547) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-overview.adoc#L17)):*
* Don't use contractions -> "It does not..."

---

*[docs/vaadin-date-picker-value.adoc, line 22 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSiHru0zcb9JhMYeeX:-KBSiHru0zcb9JhMYeeY:1900449799) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-value.adoc#L22)):*
* "this value" -> "the value"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSVRosciMg-_BEUoxI:-KBSnz4E1qu2V95VH5cJ:-624680025) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L12)):*
Correctomundo

---

*[docs/vaadin-date-picker-features.adoc, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSX6A8yPyR_FUqI4bj:-KBSo0o7sUTzzuhWWBpU:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L28)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 29 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSYhFuje9N88XMvj4B:-KBSo34foESI4Hstsf0Q:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L29)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 31 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSZRnmYfE85a7Lt629:-KBSoFZ2V9DCwk1PR2xq:2088341152) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L31)):*
Ok removed the Note

---

*[docs/vaadin-date-picker-overview.adoc, line 21 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBNOwu_fTICwUktMWi-:-KBSoq6ZpCdc8OmyOF8D:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4f3198f297f03923a5bee9b39a5f7f9f28c304d8/docs/vaadin-date-picker-overview.adoc#L21)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 11 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSgjV-bJZwSfalfkS5:-KBSoP3nbpk7ucRzt5bf:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-overview.adoc#L11)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSh03acRO9kSRMm7Gv:-KBSod1UC8MRqf3sKGF3:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-overview.adoc#L12)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBShYO771hetCg0bzLH:-KBSohjEDOMl9KyYcOcY:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-overview.adoc#L17)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 22 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSiHru0zcb9JhMYeeX:-KBSopZwuuAryhokB62u:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-value.adoc#L22)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by magi42** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSVRosciMg-_BEUoxI:-KBSqaqlaGNRqr34NpvW:57071413) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L12)):*
I still can't see the "element" word there.

---

*[docs/vaadin-date-picker-features.adoc, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSX6A8yPyR_FUqI4bj:-KBSqkJl6UvcfjR3wW9C:1419935529) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L28)):*
Oh, now I did the same mistake – article for a name... Remove the "the" article from the front of the element name; you can use just the name here, as it's not in the beginning of the sentence.

---

*[docs/vaadin-date-picker-features.adoc, line 31 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSZRnmYfE85a7Lt629:-KBSrNGIo7xd8lZGwee3:-1826283124) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L31)):*
No I meant that just remove the word "Note". Sorry, a bit unclear. ;-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by tomivirkki** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSVRosciMg-_BEUoxI:-KBSt9kxrtuqs-88jOD3:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L12)):*
Done.

---

*[docs/vaadin-date-picker-features.adoc, line 31 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSZRnmYfE85a7Lt629:-KBStZxDfvZOR0UuyT_m:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L31)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by tomivirkki** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-date-picker-features.adoc, line 28 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59#-KBSX6A8yPyR_FUqI4bj:-KBStn1Pl1tm0mEOzVig:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e32ae3221ab7953a7abf96ae2448a44f9c6ff385/docs/vaadin-date-picker-features.adoc#L28)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Comment by magi42** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/59)*

**Pull request merged**
