### PR TITLE
Add change event

### LINKED ISSUE #207: Implement 'change' event
Like in vaadin-combo-box we should consider this event, see https://github.com/vaadin/vaadin-combo-box/issues/271

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #207

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558#-:-LDk53M-5HHgvHY_Izwf:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/vaadin-date-picker-mixin.html, line 795 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558#-LDkW_deAhJ4KU_QNhKm:-LDkW_deAhJ4KU_QNhKn:b7rnkvb) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/16ef8e178c03284d5e0de97a39ae01a32b2906d1/src/vaadin-date-picker-mixin.html#L795)):*
> ```HTML
> 
>     /**
>     * Fired when the user commits a value change.
> ```

nit jsdoc lines needs a extra space except first  line

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558)*

**Comment by manolo** [comment]
:lgtm: apart from formatting nit. Not blocker though

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558#-:-LDkWQgk7sNJ7b_6jg9x:b3htjmh)*

**Comment by tomivirkki** [comment]
*[src/vaadin-date-picker-mixin.html, line 795 at r1](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558#-LDkW_deAhJ4KU_QNhKm:-LDkXP0I5IZPZ_ykstJl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/16ef8e178c03284d5e0de97a39ae01a32b2906d1/src/vaadin-date-picker-mixin.html#L795)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit jsdoc lines needs a extra space except first  line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/558)*

**Pull request merged**
