### PR TITLE
Indicate selection by font weight. Keep focus after space deselct.

### LINKED ISSUE #302: Unclear state after deselecting with space
### Description
If a date picker is empty, and you open the popup then today's date is indicated so you know where you start navigating from using the keyboard.

If a date picker is empty, you open the popup and select a date using space and then deselect it using space (which I find overall to be an unexpected feature) you are left in a state where no date is indicated, no is selected and you have very little information about what is going to happen when you continue navigating.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #302

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/309)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/keyboard-navigation.html, line 235 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/309#-KXf9tLFQ7B6ho1DVVxW:-KXf9tLFQ7B6ho1DVVxX:bl40aw4) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/395e04e17a848197d0edc80762a70755928fd288/test/keyboard-navigation.html#L235)):*
> ```HTML
>           });
> 
>           it('should deselect selected date with space', function() {
> ```

Can you add similar test but only with one `space()`. So if I understood in that case it should not deselect selected value with one space? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/309)*

**Comment by tomivirkki** [comment]
*[test/keyboard-navigation.html, line 235 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/309#-KXf9tLFQ7B6ho1DVVxW:-KXfBxmoFKBS82pJoG3V:bvvousu) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/395e04e17a848197d0edc80762a70755928fd288/test/keyboard-navigation.html#L235)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can you add similar test but only with one `space()`. So if I understood in that case it should not deselect selected value with one space? 
</blockquote></details>

There already is one (right above this one). I noticed this test wasn't working properly (hitting space just once doesn't deselect the value and while testing just overlay, you can't check datepicker for value) so it needed a fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/309)*

**Comment by samiheikki** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/309#-:-KXf_CNPhsD8wVwdhfCQ:bnfp4nl)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/309#-:-KXg__XGmFVw8ZGy19eX:bnfp4nl)*

**Pull request merged**
