### PR TITLE
Fix year/month scroller synchronization

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/204)

### CODE REVIEW

**Comment by platosha** [comment]
Why were the tests changed?

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/204#-:-KLpACSWh5SypF8JSdJg:1581446939)*

**Comment by tomivirkki** [comment]
Just pushed a cleaner fix for the tests that only changes the test setup.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/204#-:-KLpKWCswV8bo_6cR7b3:-956250489)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/204#-:-KLpU7thbfX1WTZ0aLun:1417088721)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/204#-:-KLpvwVGdBWSoasVPIvT:1417088721)*

**Pull request merged**
