### PR TITLE
Adds disabled and readonly properties to vaadin-date-picker

### LINKED ISSUE #93: Disabled and read-only

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #93

---
This change is [Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/110)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 131 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoqrNegIOWOQPH-9w1:-KCoqrNegIOWOQPH-9w2:816727583) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L131)):*
The field shouldn't be focusable when disabled/readonly. Perhaps making "tabindex" and #input[readonly] into computed properties fixes it. vaadin-combo-box seems to have the same issue currently.

---

*[vaadin-date-picker.html, line 140 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoqYq1unOdIcFIreK2:-KCoqYq1unOdIcFIreK3:-1441734734) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L140)):*
This should be hidden when disabled/readonly. See vaadin-combo-box for example.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by tehapo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-date-picker.html, line 140 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoqYq1unOdIcFIreK2:-KCornhMlbzvVRf6rbEN:-619342183) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L140)):*
:+1:  I was just about to say the same.

---

*[vaadin-date-picker.html, line 269 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCopvq22jWs8mxkGQpF:-KCopvq3DdRxH39g_OdW:-1212908446) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L269)):*
I would change this to follow same wording as the `disabled` JS Doc.

"Set to true to make this element read-only." or something similar.

---

*[demo/index.html, line 50 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCor7pK8y0pxb-NeL6A:-KCor7pL9CGnnhyeY6Bj:1650048757) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/demo/index.html#L50)):*
I would set some value to both date pickers to better illustrate how the element will look in these states.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by tomivirkki** [comment]
*[test/dropdown.html, line 111 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoridxQ2Rw_uIRgHOV:-KCoridxQ2Rw_uIRgHOW:329507427) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/test/dropdown.html#L111)):*
Also test that the calendar icon is hidden and that the field isn't focusable (in both cases)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by samiheikki** [comment]
Review status: 2 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-date-picker.html, line 131 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoqrNegIOWOQPH-9w1:-KCp-98L86Dirb57WCHI:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L131)):*
Done.

---

*[vaadin-date-picker.html, line 140 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoqYq1unOdIcFIreK2:-KCovz-Ojz7LgCBxu-_7:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L140)):*
Done.

---

*[vaadin-date-picker.html, line 269 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCopvq22jWs8mxkGQpF:-KCowTO7my_kJiiQID7-:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/vaadin-date-picker.html#L269)):*
Done.

---

*[demo/index.html, line 50 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCor7pK8y0pxb-NeL6A:-KCov31OhT9CiwLnmHFl:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/demo/index.html#L50)):*
Done.

---

*[test/dropdown.html, line 111 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCoridxQ2Rw_uIRgHOV:-KCoyQNdTS10XxoINX55:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fb036c90a7fcc501a812452ca823bb8e6706ba9/test/dropdown.html#L111)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-:-KCp470c1pGZibP3_oW1:1417088721)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-date-picker.html, line 491 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCp6Er3m-UmbQMmXIPP:-KCp6Er40b_NK4RJR10f:1007038078) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d5fb9748e291f47bb46a77208f392acfe7c3cb83/vaadin-date-picker.html#L491)):*
Actually I would still like to see this name changed. Maybe `_getTabIndex` or something similar. Current name suggest that this function would return a boolean value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by samiheikki** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-date-picker.html, line 491 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCp6Er3m-UmbQMmXIPP:-KCp964wlUEJKe0XZpFg:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d5fb9748e291f47bb46a77208f392acfe7c3cb83/vaadin-date-picker.html#L491)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-date-picker.html, line 491 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110#-KCp6Er3m-UmbQMmXIPP:-KCp9VOsIo6nKeeJAWSm:-1774010244) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d5fb9748e291f47bb46a77208f392acfe7c3cb83/vaadin-date-picker.html#L491)):*
That was fast. :smile:
:lgtm: -> will merge now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Comment by tehapo** [comment]
Did not merge yesterday because the tests were not passing. Master branch has now improved test reliability, so you should rebase this branch on top of the latest master.

**Comment by tehapo** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/110)*

**Pull request merged**
