### PR TITLE
Enable theming

### LINKED ISSUE #359: Enable Theming
- Remove CSS mixins (we may need to expose some states of dates in the calendar for it to be possible to replace existing mixins in the new theme)
- Define themable parts (document!)
- Extend `Vaadin.ThemableMixin`
- Add a default theme (align with text-field, button etc. default theme)
- Add a theming demo with bootstrapish look

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #359

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/376)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 20 of 22 files at r1, 1 of 1 files at r2.
Review status: 20 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker-styles.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYVUuHY5o15XeCmwD1:-KlYVUuHY5o15XeCmwD2:b-9zehtg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-date-picker-styles.html#L73)):*
> ```HTML
>         height: 20px;
>         width: 20px;
>         display: flex;
> ```

BTW `[part~="years-toggle-button"]::before` does not really need display: flex here. Unlike the toolbar icon buttons, the years toggle icon should probably be inline with `vertical-align: middle`.

Not a blocker.

---

*[vaadin-date-picker-styles.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYVu8e2Bac4zIULlRp:-KlYVu8e2Bac4zIULlRq:b-oiccog) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-date-picker-styles.html#L84)):*
> ```HTML
> 
>       [part~="years-toggle-button"] {
>         display: flex;
> ```

BTW Default `block` value should also work, considering that both the year and the icon are inlines.

Not a blocker too.

---

*[vaadin-infinite-scroller.html, line 304 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYWcCcL-ZYbBxrpYKV:-KlYWcCdeLmOEzM2IQpm:bctvsfg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-infinite-scroller.html#L304)):*
> ```HTML
> 
>             // This is needed by IE
>             Polymer.dom.flush();
> ```

Flushing inside a loop after adding each single item is not a good idea.

Maybe add all the items, then flush once, then iterate them once again, checking their visibility.

---

*[vaadin-month-calendar.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYY5zYp0ySltuPE7Rs:-KlYY5zYp0ySltuPE7Rt:b-rzoo45) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-month-calendar.html#L52)):*
> ```HTML
>       [part="weekday"]:empty,
>       [part="week-numbers"] {
>         width: 10%;
> ```

Please set to 12.5%, or `100% / 8`, this would make more sense.

---

*[demo/advanced.html, line 126 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYbiTLxgoRPWFfb4vL:-KlYbiTLxgoRPWFfb4vM:b-pi8v9d) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/demo/advanced.html#L126)):*
> ```HTML
>         <style is="custom-style">
>           .my-input1 input {
>             /* TODO: Fix styles */
> ```

This todo in the example code, is it a reminder for users or us?

---

*[test/index.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYcSn90cp_Wtgn1_Em:-KlYcSnB1nNxQIr_l33W:b-e56phk) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/test/index.html#L29)):*
> ```HTML
>       'late-upgrade.html',
>       'wai-aria.html'
>     ]);
> ```

Was it decided not to test against two Shadow DOM implementations here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by platosha** [comment]
Review status: 20 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-month-calendar.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYY5zYp0ySltuPE7Rs:-KlYd5ARfRwd68hIfC1R:bwu8ixj) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-month-calendar.html#L52)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Please set to 12.5%, or `100% / 8`, this would make more sense.
</blockquote></details>

OK now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by platosha** [comment]
Reviewed 1 of 22 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-infinite-scroller.html, line 304 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYWcCcL-ZYbBxrpYKV:-KlYdNS00j2ZlBkdOuaP:bveiq40) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-infinite-scroller.html#L304)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Flushing inside a loop after adding each single item is not a good idea.

Maybe add all the items, then flush once, then iterate them once again, checking their visibility.
</blockquote></details>

Tried that already but surprisingly the end result feels a bit slower that way (on IE)

---

*[test/index.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYcSn90cp_Wtgn1_Em:-KlYoaV-111aVrqMmfG6:bnu2d5r) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/test/index.html#L29)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Was it decided not to test against two Shadow DOM implementations here?
</blockquote></details>

The tests are currently run without the index file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by tomivirkki** [comment]
Review status: 21 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-date-picker-styles.html, line 73 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYVUuHY5o15XeCmwD1:-KlYvHCVDpI-Dm4JJn4C:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-date-picker-styles.html#L73)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW `[part~="years-toggle-button"]::before` does not really need display: flex here. Unlike the toolbar icon buttons, the years toggle icon should probably be inline with `vertical-align: middle`.

Not a blocker.
</blockquote></details>

Done.

---

*[vaadin-date-picker-styles.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYVu8e2Bac4zIULlRp:-KlYvHcOM4IFaHgjAV1I:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-date-picker-styles.html#L84)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Default `block` value should also work, considering that both the year and the icon are inlines.

Not a blocker too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by tomivirkki** [comment]
*[demo/advanced.html, line 126 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYbiTLxgoRPWFfb4vL:-KlYwLSoWcsNe0sPvP1H:b-1rkdn9) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/demo/advanced.html#L126)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This todo in the example code, is it a reminder for users or us?
</blockquote></details>

Oh, right. Forgot to restore these, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 304 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYWcCcL-ZYbBxrpYKV:-KlYypl1Ue68vQmS5B1d:b32w0x) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/vaadin-infinite-scroller.html#L304)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Tried that already but surprisingly the end result feels a bit slower that way (on IE)
</blockquote></details>

OK

---

*[test/index.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYcSn90cp_Wtgn1_Em:-KlYz8kxx8X9He3rMiP2:b3bgaj0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/test/index.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The tests are currently run without the index file
</blockquote></details>

Maybe not change then? This makes no practical effect, and is out of styling scope...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-date-picker-overlay.html, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZ10vvSrimyHLaOj-z:-KlZ10vvSrimyHLaOj0-:b-77utta) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-date-picker-overlay.html#L20)):*
> ```HTML
> <link rel="import" href="vaadin-date-picker-styles.html">
> 
> <dom-module id="vaadin-date-picker-overlay">
> ```

what is the reason of having styles here, and in the default theme.
At first view I would expect everything in the external style.html file.

---

*[vaadin-date-picker-overlay.html, line 184 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZbilOEVZW5vScpfOy:-KlZbilOEVZW5vScpfOz:b7m226m) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-date-picker-overlay.html#L184)):*
> ```HTML
>     <div part="overlay-header" on-touchend="_preventDefault" desktop$="[[_desktopMode]]" aria-hidden="true">
>       <div part="label">[[_formatDisplayed(selectedDate, i18n.formatDate, label)]]</div>
>       <div part="clear-button" on-tap="_clear" showclear$="[[_showClear(selectedDate)]]"></div>
> ```

What is the main reason of removing ids here? it makes the test code much more verbose having to use querySelector and tranverse de DOM in each test instead of having a fixed reference.

---

*[vaadin-infinite-scroller.html, line 295 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZRJDSKG9VRf84MRva:-KlZRJDSKG9VRf84MRvb:bqh9gji) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-infinite-scroller.html#L295)):*
> ```HTML
>             const slotName = 'vaadin-infinite-scroller-item-content-' + contentId;
> 
>             const injectionPoint = document.createElement('slot');
> ```

It sounds odd to me, might be insertionPoint, slotHolder  instead ? injection sounds better for classes 

---

*[demo/theming.html, line 226 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZ_RDldWsuUKpDqgBF:-KlZZzzpaIuz2YFNBBNQ:b-ucwqbk) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/demo/theming.html#L226)):*
> ```HTML
>         <script>
>           window.addEventListener('WebComponentsReady', function() {
>             // Async call needed here for IE11 compatibility.
> ```

Is it necessary to set the first day of week to 1 for theming demo purposes ? 

---

*[test/common.js, line 65 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZbDR06ldcQ8AVQ9Yo:-KlZbDR06ldcQ8AVQ9Yp:blav1vy) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/test/common.js#L65)):*
> ```JavaScript
> 
> function tap(element) {
>   element.dispatchEvent(new CustomEvent('tap', {bubbles: true, detail: {}, composed: true}));
> ```

detail is not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[demo/theming.html, line 35 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZfz-QrYt4VH_bWH43:-KlZfz-QrYt4VH_bWH44:bx0iw7v) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da16f74eb34dfde6516e79ebbcedc18ac8965252/demo/theming.html#L35)):*
> ```HTML
>               [part~="value"]:focus {
>                 outline: none;
>               }
> ```

The demo should style the input when it's focused as well as the focused date. 
Right now moving the focus is confussing, the user only knows where the focus is when it is in the footer buttons.

---

*[demo/theming.html, line 136 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZgrMuWcxcPCBAF6uv:-KlZgrMuWcxcPCBAF6uw:bjwfcd7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da16f74eb34dfde6516e79ebbcedc18ac8965252/demo/theming.html#L136)):*
> ```HTML
>               [part~="date"][selected] {
>                 font-weight: 600;
>               }
> ```

We need a default style for the date when it is focused as we had before. Moving focus from the input to the overlay does not produce any visual change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by tomivirkki** [comment]
Review status: 16 of 22 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[vaadin-date-picker-overlay.html, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZ10vvSrimyHLaOj-z:-Kl_0cCHGv-VaR6mGQvj:bfv01ip) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-date-picker-overlay.html#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

what is the reason of having styles here, and in the default theme.
At first view I would expect everything in the external style.html file.
</blockquote></details>

Most of our components need to have a set of "functional styles" that are required in every (including the default) theme. Default theme (the stuff currently in the external file) is just visual sugar on top of that but something the component would still be ok without.

We could have the default theme modules inside the element files alongside the functional styles as we do in case of text-field for example, but since the date-picker is more complex and thus has a lot of CSS, we thought it would make it more understandable/readable to separate the functional / non-functional styles like this.

---

*[vaadin-date-picker-overlay.html, line 184 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZbilOEVZW5vScpfOy:-Kl_1jF5z8_vDfec4u7Y:b-616h6j) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-date-picker-overlay.html#L184)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

What is the main reason of removing ids here? it makes the test code much more verbose having to use querySelector and tranverse de DOM in each test instead of having a fixed reference.
</blockquote></details>

The id's are no longer needed in most cases once we replaced them with parts. Didn't see a reason to leave them here just so we could use dollar accessor instead of querySelector in tests.

---

*[vaadin-infinite-scroller.html, line 295 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZRJDSKG9VRf84MRva:-Kl_2Zn8kiNRu98jwMVq:b-p5l140) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-infinite-scroller.html#L295)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It sounds odd to me, might be insertionPoint, slotHolder  instead ? injection sounds better for classes 
</blockquote></details>

Ah, true. Meant to type insertionPoint. Brainfart.

---

*[demo/theming.html, line 226 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZ_RDldWsuUKpDqgBF:-Kl_2LR55zEhfTOag058:b2hzkgg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/demo/theming.html#L226)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is it necessary to set the first day of week to 1 for theming demo purposes ? 
</blockquote></details>

Week numbers are only supported for locales that start the week on Monday

---

*[demo/theming.html, line 35 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZfz-QrYt4VH_bWH43:-KlbV5pand3fyjs31JKg:bm1jmcn) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da16f74eb34dfde6516e79ebbcedc18ac8965252/demo/theming.html#L35)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The demo should style the input when it's focused as well as the focused date. 
Right now moving the focus is confussing, the user only knows where the focus is when it is in the footer buttons.


</blockquote></details>

Looks like the default style had the same issue with focused date in a non-focused calendar. Added in both.

The caret will have to do in the theming example to indicate text field focus.

---

*[demo/theming.html, line 136 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZgrMuWcxcPCBAF6uv:-KlbVy0tW0xIcEu7v_F6:b8yeydq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da16f74eb34dfde6516e79ebbcedc18ac8965252/demo/theming.html#L136)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We need a default style for the date when it is focused as we had before. Moving focus from the input to the overlay does not produce any visual change.
</blockquote></details>

Looks like the default style had the same issue with focused date in a non-focused calendar. Added in both.

---

*[test/common.js, line 65 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZbDR06ldcQ8AVQ9Yo:-KlbTNy90OAEWM3YNF4g:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/test/common.js#L65)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

detail is not needed
</blockquote></details>

Done.

---

*[test/index.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlYcSn90cp_Wtgn1_Em:-Kl_DUUQ-jfwEP6HenEK:b-l0w77l) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/100ae7a885936b40214afca27d44f44998fe7099/test/index.html#L29)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe not change then? This makes no practical effect, and is out of styling scope...
</blockquote></details>

I guess the reason for this is to not run shady when running locally/manually either (when you use the index file)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by platosha** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by tomivirkki** [comment]
*[test/common.js, line 65 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZbDR06ldcQ8AVQ9Yo:-KlbkuhhXBBbZCFYMyYt:b9sbax9) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/test/common.js#L65)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like it was needed after all https://travis-ci.org/vaadin/vaadin-date-picker/builds/238643784

Restored

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by tomivirkki** [comment]
*[demo/theming.html, line 35 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZfz-QrYt4VH_bWH43:-Klbo5_Huq4i1nq1-_dq:b-tupoeb) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da16f74eb34dfde6516e79ebbcedc18ac8965252/demo/theming.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Looks like the default style had the same issue with focused date in a non-focused calendar. Added in both.

The caret will have to do in the theming example to indicate text field focus.
</blockquote></details>

Done. Added non-focused style for the text-field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r6.
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-overlay.html, line 184 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-KlZbilOEVZW5vScpfOy:-Klbkrirj9gJ4F_hbd20:b2bq10r) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/97f643a09035db89bb6622b3112c063070a6f0ae/vaadin-date-picker-overlay.html#L184)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The id's are no longer needed in most cases once we replaced them with parts. Didn't see a reason to leave them here just so we could use dollar accessor instead of querySelector in tests.
</blockquote></details>

Well it's a matter of amount of code, seems by removing 10 characters in code we need dozens of them in tests, so I don't see the need. not a blocker though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376#-:-Klbp6pG0opQmANni59l:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/376)*

**Pull request merged**
