### PR TITLE
Support Firefox in webcomponents.org

### PR DESCRIPTION
**Pull request by limonte**
Related to https://github.com/vaadin/vaadin-element-skeleton/pull/58

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/427)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Why does `<paper-input>` for example work without this hack?

**Comment by limonte** [comment]
Because of https://github.com/webcomponents/webcomponents.org/blob/04ba2624ff284d18a98297eb24e6425827c5d023/client/bower.json#L22

We need `webcomponentsjs 1.x` for our components.

**Comment by tomivirkki** [comment]
Yeah, looks like it's lacking from date-picker devDependencies https://github.com/vaadin/vaadin-date-picker/blob/master/bower.json even though it's directly used in the demos

**Comment by limonte** [comment]
Added `webcomponentsjs` devDependency, it works now: https://www.webcomponents.org/preview/vaadin/vaadin-date-picker/5dbb679233e560c5a079e8115355741608b52418

**Comment by tomivirkki** [comment]
LGTM

**Pull request merged**
