### PR TITLE
Fixed logic for dropdown close cancellation

### LINKED ISSUE #156: Clicking the calendar icon no longer closes the dropdown
We might need to put the "pointer-events: none" workaround (that was removed in 2bfa222694ac8e508400774e5c1e76c4369c3713) back

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #156

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/161)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 478 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/161#-KF3tjzMELfVFqHtfIXF:-KF3tjzN-Bc4w1bQVHT4:830022250) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/304b8d1a003c1103eea1f28d589b9ec765e4ad05/vaadin-date-picker.html#L478)):*
To me is more natural to use Regexp, indexOf !== -1 works but takes my time. I miss a `contains` method in JS string.

`if (/tap|mousedown|touchstart/.test(e.detail.type)) `

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/161)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 478 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/161#-KF3tjzMELfVFqHtfIXF:-KF3yrfNCNf7CsGxFPry:466147860) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/304b8d1a003c1103eea1f28d589b9ec765e4ad05/vaadin-date-picker.html#L478)):*
:thumbsup: Switched to regexp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/161)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/161#-:-KF3zb0J2xDMeYD3BRdo:1417088721)*

**Comment by jounik** [comment]
Does this also fix the "clear" icon as well? Currently seems like you can’t actually clear the date picker value at all.

**Comment by tomivirkki** [comment]
It sure does. Discussed here also https://github.com/vaadin/vaadin-date-picker/pull/160#issuecomment-208259293

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/161)*

**Pull request merged**
