### PR TITLE
Speed up some tests by removing delay in async calls

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/295)

### CODE REVIEW

**Comment by tomivirkki** [comment]
For some reason Travis is reporting false positives:
https://travis-ci.org/vaadin/vaadin-date-picker/builds/176633487

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-:-KWld4zK8OTQFCMnILBj:b-cczfz)*

**Comment by limonte** [comment]
It seems that something is wrong with Travis CI, another example of the successful build, despite of some failed tests: https://travis-ci.org/vaadin/vaadin-date-picker/builds/176633379

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-:-KWletV2gfBA6L5UZJFp:b-agome9)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWmoYDkAawM_gtjbdCK:bg9w1z4) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
> ```HTML
>             document.body.removeEventListener('iron-announce', announceSpy);
>             done();
>           }, 1);
> ```

why do we still need an async here? and why exactly 1 millsec ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWmrRc6sIpjfz-aP1cL:b-oziaou) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
> why do we still need an async here?
I'm not sure, to answer this I need to get more familiar with `iron-announce` event firing.

> why exactly 1 millsec ?
It's the minimal delay, test will be executed as fast as possible (99ms faster than it was)  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWmt8oywBcnjM8W-8Y4:bl2w6q6) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary>
> > why do we still need an async here?
> I'm not sure, to answer this I need to get more familiar with `iron-announce` event firing.
> 
> > why exactly 1 millsec ?
> It's the minimal delay, test will be executed as fast as possible (99ms faster than it was)  
</details>
Initially with this 'iron-announce' event tests, my intention was to have more relaxed timing and allow timing tweaks in the implementation.

The event dispatch timing affects the order of the announces. Sometimes we might need to postpone dispatching the event to get nicer output in screen readers.

I’m personally OK with any timeout here, as long as the test passes with the current implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWqL-uPIDUTTwmIqf8I:bhkg92l) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary>
> > why do we still need an async here?
> I'm not sure, to answer this I need to get more familiar with `iron-announce` event firing.
> 
> > why exactly 1 millsec ?
> It's the minimal delay, test will be executed as fast as possible (99ms faster than it was)  
</details>
1. What happens if you remove the async, do tests fail? I think it's worth to try it.

2. The fast is 0 millisec, that basically means when you read the code that you want to do this async, not now. Otherwise  1 means to me that the test need to wait for one after the schedule is idle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWqRHeprK3kKb_JtHDs:b-l48ttl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
> What happens if you remove the async, do tests fail? I think it's worth to try it.

Yes. Also, tests are failing with async call with 0 ms delay. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWqSVRVYePoEya66UVz:bdtxyn0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary>
> > What happens if you remove the async, do tests fail? I think it's worth to try it.
> 
> Yes. Also, tests are failing with async call with 0 ms delay. 
</details>
If test fails with timeout=0 and passes with a timeout=1 sounds to me that might fail randomly depending on the device, specially android in saucelabs or IE11. 

Since the test is waiting for the debouncer to be finished, I would be setup this with a timeout greater that  the default timeout of debouncers that is 100ms. So 101 would guarantee that there are no more than un call to the spy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by tomivirkki** [comment]
*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWqX1tkzRKIbaAKRlB7:b-9uemem) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> If test fails with timeout=0 and passes with a timeout=1 sounds to me that might fail randomly depending on the device, specially android in saucelabs or IE11. 
> 
> Since the test is waiting for the debouncer to be finished, I would be setup this with a timeout greater that  the default timeout of debouncers that is 100ms. So 101 would guarantee that there are no more than un call to the spy
> 
> 
</details>
If possible avoid magic numbers (101) timeouts in tests and instead flush the pending debouncer programmatically

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KWqYwNE0IQS7Aae8fbA:b-gpugp1) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> If possible avoid magic numbers (101) timeouts in tests and instead flush the pending debouncer programmatically
</details>
That is a good option, but only if we are sure that the bouncer has been hit twice before calling the flush. Although it should be so, I'm not sure that it is guaranteed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by Saulis** [comment]
I removed some async calls, events from the keyboard tests. There's still more stuff that could be removed IMO.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KX5Mr5SkDEQuMqWS6vl:b-oi90s2) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> That is a good option, but only if we are sure that the bouncer has been hit twice before calling the flush. Although it should be so, I'm not sure that it is guaranteed. 
</details>
Added a flush.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-:-KX5Ze-DwWpVfN2Ags7z:b-cf4c3a)*

**Comment by tomivirkki** [comment]
Still a false positive, please rebase

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-:-KX5m5OVCfY-x09G4feG:bdjm35g)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/wai-aria.html, line 452 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-KWmoYDkAawM_gtjbdCJ:-KX66b4zdtHY49VxjhyR:b-9jlkcg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d9a18dc9f3f45ed5d18ce12a6c9149ed6c7cf22e/test/wai-aria.html#L452)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Added a flush.
</details>
After rebasing, the `iron-announce` will be fired only after `iron-overlay-opened` has been fired, so after next animation frame. `1ms` delay is the simplest way getting around that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295)*

**Comment by limonte** [comment]
done.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-:-KX6CsCBNZuWD2dC25Pj:b-7rl0jd)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/295#-:-KX9oWKRyGN7IZ4iaYa3:bnfp4nl)*

**Pull request merged**
