### PR TITLE
Add new structure date picker's formatDate parameter.

### LINKED ISSUE #274: JS Date object might break under different conditions.
The Date object might break depending on how it was constructed.

See:
http://www.slideshare.net/MaggiePint/date-and-time-momentjs-edition
https://www.youtube.com/watch?v=ieIzNP6gKqU

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #274

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/487)

### CODE REVIEW

**Comment by tomivirkki** [comment]
The change set doesn't seem right (Files changed: 26)

**Comment by vicsstar** [comment]
Do you have an idea why this may have happened? Cause, this is my commit, it reports only 6 files changed: https://github.com/vaadin/vaadin-date-picker/commit/281fe48f1e52781dcd7c8c990bfada3cdee040a5

Did a rebase and it looks like a merge happened instead.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0E1M-UbZVOCQ6pvAwP:b11gltl)*

**Comment by vicsstar** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0EzAGMBemjy425dII9:b-896fix)*

**Comment by vicsstar** [comment]
Rebase is fixed. Lessons learned. :trollface: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0EzCxGoD7UjGe64ts9:bsub6w3)*

**Comment by web-padawan** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-date-picker-helper.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JrnuspAwhQGSCaUet:-L0JrnuspAwhQGSCaUeu:b-808k5t) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/src/vaadin-date-picker-helper.html#L94)):*
> ```HTML
> 
>     /**
>      * 
> ```

Is this JSDoc intentional? Should it be documented as `@private`?

---

*[src/vaadin-date-picker-mixin.html, line 205 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JtfUyicr8t-r7dZZp:-L0JtfUyicr8t-r7dZZq:b3y0z23) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/src/vaadin-date-picker-mixin.html#L205)):*
> ```HTML
>                   return [d.getMonth() + 1, d.getDate(), yearStr].join('/');
>                 } else {
>                   const yearStr = formatYear(String(d.year));
> ```

nit: using `String` for conversion could be moved into the `formatYear` function so you don't need calling it twice:
```
const formatYear = year => String(year).replace(/\d+/, y => '0000'.substr(y.length) + y);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by platosha** [comment]
Incomplete: there is also a user-provided `parseDate` i18n API callback, we should expect it to return an object `{year, month, date}`.  This was mentioned in the ticket description.

Also, it was noted and discussed that we should preserve backwards-compatibility. If a user-provided `parseDate` function returns a `Date` instance (old API), it should work, but give a warning in the developer console. Right, @tomivirkki ?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/date-picker-advanced-demos.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Jxwk76n-Hzxrott-h:-L0Jxwk76n-Hzxrott-i:b-nbi235) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L36)):*
> ```HTML
>               weekdaysShort: 'su_ma_ti_ke_to_pe_la'.split('_'),
>               formatDate: function(date) {
>                 // Sugar Date expects a native date; this `date` parameter however is in our new format.
> ```

Sugar has a builtin date constrictor that supports objects:

```javascript
return Sugar.Date.format(Sugar.Date.create(date), '{short}');
```

---

*[demo/date-picker-advanced-demos.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JvGaNqjxqZ8_xC8rT:-L0JvGaNqjxqZ8_xC8rU:b-tx6heq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L52)):*
> ```HTML
>                 dateString = matches.length === 1 ? matches[0] : dateString;
>                 // Parse the date
>                 return Sugar.Date.create(dateString);
> ```

Should return an object `{year, month, day}` instead of a Date instance.

---

*[src/vaadin-date-picker-mixin.html, line 233 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Juv4pKEweV7Axt_n3:-L0Juv4pKEweV7Axt_n4:b-tx6heq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/src/vaadin-date-picker-mixin.html#L233)):*
> ```HTML
>                   result.setMonth(month);
>                   result.setDate(date);
>                   return result;
> ```

Should return an object `{year, month, day}` instead of a Date instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0Jv_Kt_x4RJCAjWAf9:b-lnljq7)*

**Comment by vicsstar** [comment]
The decision about backward compatibility preservation was reversed 3 days ago, when we all voted to not support backward compatibility.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0K1BbGV9NB5iRwIOpK:bt03j13)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 205 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JtfUyicr8t-r7dZZp:-L0OWduHX2VXLjMtDExh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/src/vaadin-date-picker-mixin.html#L205)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: using `String` for conversion could be moved into the `formatYear` function so you don't need calling it twice:
```
const formatYear = year => String(year).replace(/\d+/, y => '0000'.substr(y.length) + y);
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-helper.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JrnuspAwhQGSCaUet:-L0OX9bpr079zzh1wtyi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/src/vaadin-date-picker-helper.html#L94)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Is this JSDoc intentional? Should it be documented as `@private`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-advanced-demos.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Jxwk76n-Hzxrott-h:-L0OXH9XVonawmoZe5br:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L36)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Sugar has a builtin date constrictor that supports objects:

```javascript
return Sugar.Date.format(Sugar.Date.create(date), '{short}');
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by tomivirkki** [comment]
*[demo/date-picker-advanced-demos.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Jxwk76n-Hzxrott-h:-L0OXZh0s8a4esglfAki:b4kg1qp) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L36)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove mentions about "new format". This _is_ our format, no need to emphasize it's changed from something at some point of time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by tomivirkki** [comment]
*[demo/date-picker-advanced-demos.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JvGaNqjxqZ8_xC8rT:-L0OY9KhRXxVYJe_m_rh:bj61be8) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L52)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should return an object `{year, month, day}` instead of a Date instance.
</blockquote></details>

Don't use private API in the demo.
```
const date = Sugar.Date.create(dateString);
return {
  day: date.getDate(),
  month: date.getMonth(),
  year: date.getFullYear()
};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by tomivirkki** [comment]
Review status: 4 of 8 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[demo/date-picker-advanced-demos.html, line 1 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OYykHCpMw6HM0z5yC:-L0OYykHCpMw6HM0z5yD:b2bg46l) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-advanced-demos.html#L1)):*
> ```HTML
> <link rel="import" href="../src/vaadin-date-picker-helper.html">
> ```

This is an internal module, remove from demos

---

*[demo/date-picker-basic-demos.html, line 1 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZ16q8NSnW3Qq_Rks:-L0OZ16q8NSnW3Qq_Rkt:b2bg46l) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-basic-demos.html#L1)):*
> ```HTML
> <link rel="import" href="../src/vaadin-date-picker-helper.html">
> ```

This is an internal module, remove from demos

---

*[demo/date-picker-basic-demos.html, line 171 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZ1eGz1EdG8y9mqjI:-L0OZ1eGz1EdG8y9mqjJ:b-xe3qqm) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-basic-demos.html#L171)):*
> ```HTML
>                 dateString = matches.length === 1 ? matches[0] : dateString;
>                 // Parse the date (using a 3rd party library)
>                 return Vaadin.DatePickerHelper._extractDateParts(Sugar.Date.create(dateString));
> ```

Don't use private APIs in the demos

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by tomivirkki** [comment]
*[src/vaadin-date-picker-mixin.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZEt_0sZhx-lDIPAE:-L0OZEt_0sZhx-lDIPAF:bq1jg2u) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/src/vaadin-date-picker-mixin.html#L10)):*
> ```HTML
> <link rel="import" href="../../iron-resizable-behavior/iron-resizable-behavior.html">
> <link rel="import" href="vaadin-date-picker-helper.html">
> <script src="../../sugar/dist/sugar.min.js"></script>
> ```

We will not add Sugar as a dependency for our element. Remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-advanced-demos.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JvGaNqjxqZ8_xC8rT:-L0O_Zy_LUKRSSQd0JuG:bwxvm8k) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L52)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Don't use private API in the demo.
```
const date = Sugar.Date.create(dateString);
return {
  day: date.getDate(),
  month: date.getMonth(),
  year: date.getFullYear()
};
```
</blockquote></details>

Okay, after I remove the helper dependency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-basic-demos.html, line 171 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZ1eGz1EdG8y9mqjI:-L0O_pBLNonlBnVXWw7h:blwz8s5) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-basic-demos.html#L171)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Don't use private APIs in the demos
</blockquote></details>

I get you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-basic-demos.html, line 171 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZ1eGz1EdG8y9mqjI:-L0Oao5HKHnjE8hVoHi6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-basic-demos.html#L171)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

I get you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-advanced-demos.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0JvGaNqjxqZ8_xC8rT:-L0Oapt1EOp5rA-LYGfJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L52)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Okay, after I remove the helper dependency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-advanced-demos.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Jxwk76n-Hzxrott-h:-L0OaqpzhyVWM1a6xtu-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Remove mentions about "new format". This _is_ our format, no need to emphasize it's changed from something at some point of time.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-advanced-demos.html, line 1 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OYykHCpMw6HM0z5yC:-L0OasUpMImkg6R_DMu0:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-advanced-demos.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is an internal module, remove from demos
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-basic-demos.html, line 1 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZ16q8NSnW3Qq_Rks:-L0Oav-SZ1JloxtcT9Y6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/demo/date-picker-basic-demos.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is an internal module, remove from demos
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZEt_0sZhx-lDIPAE:-L0ObOMoGC2UUFUhNWwD:b-tkgbh0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/src/vaadin-date-picker-mixin.html#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We will not add Sugar as a dependency for our element. Remove.
</blockquote></details>

What's the alternative?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 233 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Juv4pKEweV7Axt_n3:-L0ObVn4E-OV7tLwTTx_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/src/vaadin-date-picker-mixin.html#L233)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should return an object `{year, month, day}` instead of a Date instance.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by tomivirkki** [comment]
Review status: 4 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[demo/date-picker-advanced-demos.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Jxwk76n-Hzxrott-h:-L0Oe6H6Tj7vHvj9LkSV:b-o329rh) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L36)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"our format" doesn't really say much to the reader. Better to describe the format properly. "is in {...} format"

---

*[src/vaadin-date-picker-mixin.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZEt_0sZhx-lDIPAE:-L0OfZzwVa-RMxg2lrjv:b-mqjgjt) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/src/vaadin-date-picker-mixin.html#L10)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

What's the alternative?
</blockquote></details>

```
const dateObject = this.i18n.parseDate(inputValue);
const parsedDate = this._parseDate(`${dateObject.year}-${dateObject.month}-${dateObject.day}`);
```

---

*[src/vaadin-date-picker-mixin.html, line 160 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Ofpmad24y-qFxxJWF:-L0Ofpmad24y-qFxxJWG:b-uqemdi) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0c659c8688a5623ce6420735838dacb90b3e0b6b/src/vaadin-date-picker-mixin.html#L160)):*
> ```HTML
>               formatDate: d => {
>                 // returns a string representation of the given
>                 // Date object in 'MM/DD/YYYY' -format
> ```

The docs should be updated

---

*[src/vaadin-date-picker-mixin.html, line 169 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Ofmi8T_1Xj0IadiZK:-L0Ofmi8T_1Xj0IadiZL:b-uqemdi) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0c659c8688a5623ce6420735838dacb90b3e0b6b/src/vaadin-date-picker-mixin.html#L169)):*
> ```HTML
>               // keyboard input feature.
>               parseDate: text => {
>                 // Parses a string in 'MM/DD/YY', 'MM/DD' or 'DD' -format to
> ```

The docs should be updated

---

*[src/vaadin-date-picker-mixin.html, line 202 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OcYcdIP4yV6TDCZyQ:-L0OcYcdIP4yV6TDCZyR:b-app0yi) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0c659c8688a5623ce6420735838dacb90b3e0b6b/src/vaadin-date-picker-mixin.html#L202)):*
> ```HTML
>                 const formatYear = year => String(year).replace(/\d+/, y => '0000'.substr(y.length) + y);
> 
>                 if (typeof d.getMonth === 'function') {
> ```

Why check this? Isn't the parameter _always_ in {year, month, day} format?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OZEt_0sZhx-lDIPAE:-L0P5AWWsWe3dlLnpLeg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ad7cd77793c558ffc75cc3658a375b73e7479db5/src/vaadin-date-picker-mixin.html#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

```
const dateObject = this.i18n.parseDate(inputValue);
const parsedDate = this._parseDate(`${dateObject.year}-${dateObject.month}-${dateObject.day}`);
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 160 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Ofpmad24y-qFxxJWF:-L0P5Cbb_DzBK4L_rPgI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0c659c8688a5623ce6420735838dacb90b3e0b6b/src/vaadin-date-picker-mixin.html#L160)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The docs should be updated
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 169 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Ofmi8T_1Xj0IadiZK:-L0P5DzuQJFUTN8h0d70:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0c659c8688a5623ce6420735838dacb90b3e0b6b/src/vaadin-date-picker-mixin.html#L169)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The docs should be updated
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[demo/date-picker-advanced-demos.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0Jxwk76n-Hzxrott-h:-L0P5ItkyyTvuHgfeWQg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/db5e4139abfd3c2b75e3d37abb2cf9f28c8ad3f6/demo/date-picker-advanced-demos.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"our format" doesn't really say much to the reader. Better to describe the format properly. "is in {...} format"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by web-padawan** [comment]
Reviewed 1 of 9 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[bower.json, line 27 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0cfUACp9UyLgvho49S:-L0cfUACp9UyLgvho49T:btqosxc) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/93384d5d010aaa5003639045a584e672f30c175b/bower.json#L27)):*
> ```JSON
>     "iron-resizable-behavior": "^2.0.0",
>     "polymer": "^2.0",
> <<<<<<< HEAD
> ```

bad merge in this file, please fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[bower.json, line 27 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0cfUACp9UyLgvho49S:-L0ijcURKipr--9ALEfv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/93384d5d010aaa5003639045a584e672f30c175b/bower.json#L27)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

bad merge in this file, please fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
*[src/vaadin-date-picker-mixin.html, line 202 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0OcYcdIP4yV6TDCZyQ:-L0ijnXGjrswXaT6LWF_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0c659c8688a5623ce6420735838dacb90b3e0b6b/src/vaadin-date-picker-mixin.html#L202)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why check this? Isn't the parameter _always_ in {year, month, day} format?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0t7x4a9rvw41aMA8qb:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/date-picker-advanced-demos.html, line 1 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0tA0u5Z2bCCfGuLc_b:-L0tA0u5Z2bCCfGuLc_c:b322cir) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b42cbde97105ae4f390d5998b59b489ccd64b862/demo/date-picker-advanced-demos.html#L1)):*
> ```HTML
> <script src="../../sugar/dist/sugar.min.js"></script>
> ```

Demo dependencies are imported in `index.html`

---

*[demo/date-picker-basic-demos.html, line 1 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0tAWa0nQdGB4bNZH07:-L0tAWa0nQdGB4bNZH08:b322cir) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b42cbde97105ae4f390d5998b59b489ccd64b862/demo/date-picker-basic-demos.html#L1)):*
> ```HTML
> <script src="../../sugar/dist/sugar.min.js"></script>
> ```

Demo dependencies are imported in `index.html`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/date-picker-basic-demos.html, line 1 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0tAWa0nQdGB4bNZH07:-L0tCPsEer6Xu0UZbjnL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b42cbde97105ae4f390d5998b59b489ccd64b862/demo/date-picker-basic-demos.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Demo dependencies are imported in `index.html`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by vicsstar** [comment]
Review status: 6 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/date-picker-advanced-demos.html, line 1 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-L0tA0u5Z2bCCfGuLc_b:-L0tCReoFbIeulciKFd4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b42cbde97105ae4f390d5998b59b489ccd64b862/demo/date-picker-advanced-demos.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Demo dependencies are imported in `index.html`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487)*

**Comment by tomivirkki** [comment]
Analysis

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0tdVN8SDgeIY6J2ibf:bkbiewx)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r5, 2 of 2 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/487#-:-L0xijR2jwt3hq0obQ5m:bnfp4nl)*

**Pull request merged**
