### PR TITLE
Marking classes and properties @private, removing parameter from validate and CheckValidity

### LINKED ISSUE #457: Flow API related todo list
### Value compatibility

Make sure all public-available user input elements follow these rules:

- [ ] the `value` property is declared as `String`
- [ ] the `value` property is not read-only and allows changes
- [ ] the `value` property declaration has `notify: true`

### Validation compatibility

Make sure all public-available validatable elements follow these rules:

- [ ] the `invalid` property is declared as `Boolean`
- [ ] the `invalid` property has `notify: true`
- [ ] `validate()` method updates the `invalid` state property

### `vaadin-date-picker-mixin.html`

- [ ] ❓ deprecate `open()` and `close()` methods for future removal in next major version, since duplicate of writable `opened` property
- [ ] ❓ deprecate `cancel()` method for future removal
  - probably duplicate of `comboBox.opened = false; comboBox.value = initialValue;`
- [ ] in `validate()` and `checkValidity()` methods, document the `value` argument and mark as deprecated to be removed in next major
- [ ] mark with `@private` and deprecate the `hasValue` property, only the argument should be kept for styling

### Mark with `@private` for the element classes

- `vaadin-date-picker-overlay.html`:
  - [ ] `class DatePickerOverlayElement`
- `vaadin-infinite-scroller.html`:
  - [ ] `class InfiniteScrollerElement`
- `vaadin-month-calendar.html`:
  - [ ] `class MonthCalendarElement`

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #457

List of changes: 
- `hasValue` mark as `@private` 
- Parameter `value` was documented in `validate` method
- Parameter value and return boolean were documented in `checkValidity` method
- `DatePickerOverlayElement` marked as `@private`
- `InfiniteScrollerElement` marked as `@private`
- `MonthCalendarElement` marked as `@private`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/455)

### CODE REVIEW

**Comment by Toshegg** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/455#-:-Kxw13gyNSkU06AiU8Tx:bnfp4nl)*

**Comment by limonte** [comment]
> Make needed changes accordingly to the specified list

Meaningless PR title.

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/455#-:-KxxXHHhGvkbJcug4o5L:bnfp4nl)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[analysis.json, line 0 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/455#-KyQLxXWAiflB77wCaW-:-KyQLxXWAiflB77wCaW0:bu4np8e) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fcdb9b9e426849f8cd760f90f4696f53950a74e6/analysis.json#L0)):*
Looks like `analysis.json` was reshuffled and incorporated some unwanted Polymer.Element API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/455)*

**Pull request merged**
