### PR TITLE
Stop tap events from bubbling out of the overlay

### LINKED ISSUE #250: Open method has an undocumented event argument
From https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker-behavior.html#L228

``` js
/**
  * Opens the dropdown.
  */
open: function(e) {
  this._updateAlignmentAndPosition();
  // Prevent dropdown.open() being called when input is disabled or read-only, or tapped
  // inside the overlay
  if (!this.disabled && !this.readonly && (!e || Polymer.dom(e).path.indexOf(this.$.overlay) < 0)) {
    this.$.dropdown.open();
  }
}
```

Instead of adding documentation for `e`, I propose removing the argument altogether – instead, `tap` should be stopped from bubbling from the overlay to prevent the overlay from reopening when a date is selected.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #250

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/278)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/overlay.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/278#-KVVU2Kw_LTInTfIbMj1:-KVVU2Kw_LTInTfIbMj2:b-m8j6f7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/803eb48db4ddb32b2e5943058bdff3366b3914ca/test/overlay.html#L51)):*
> ```HTML
>         var tapSpy = sinon.spy();
>         document.addEventListener('tap', tapSpy);
>         overlay.$.scroller.dispatchEvent(new CustomEvent('tap', {
> ```

Should we dispatch this test event on the overlay instead of the scroller?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/278)*

**Comment by tomivirkki** [comment]
*[test/overlay.html, line 51 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/278#-KVVU2Kw_LTInTfIbMj1:-KVVoK-NmQ_WgQwTc3xy:b-muprw3) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/803eb48db4ddb32b2e5943058bdff3366b3914ca/test/overlay.html#L51)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Should we dispatch this test event on the overlay instead of the scroller?
</details>
Well, shouldn't really matter in practice. The event we're interested in is actually fired and bubbles from inside the scroller so this is kind of more 'realistic' case in that sense.

Copied the test case from the one above which follows the same pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/278)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/278#-:-KVYnKOt15dfT8Hrrl4e:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/278#-:-KVYp1C80UvyYOCYXWpO:bnfp4nl)*

**Pull request merged**
