### PR TITLE
Enable selecting today with today button

### LINKED ISSUE #170: Refine “Today” button behavior
### Problem

Some users really expect the “Today” button to select the date instead of just scroll it into view. This is more obvious in the situation when today is already visible in the viewport, and nothing happens visually when the user taps the “Today” button.

Also, if the popup height is less than a full month (so that the last week of the month is outside of the view), today is not scrolled fully visible if the day is in the last week of of the month. Came up with #169. Might not be an issue after that is fixed, as most viewports should have enough space to show the full month. But it also depends on the theme (font size, sizing, etc.) if it can fit.

### Spec

If today’s day number is outside the popup viewport, clicking the “Today” button scrolls the calendar to show today’s day cell. When today’s day number is visible in the popup, clicking the “Today” button selects today and closes the popup.

The “Today” button’s appearance can change depending whether today’s day cell is currently visible, or before or after the currently visible day cells. For the current default Material design theme, the button style is always the same (updated styling is planned for later).

See the mockup in #249 (“Immediate single-select”).

### PR DESCRIPTION
**Pull request by platosha**
Fixes #170

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/264)

### CODE REVIEW

**Comment by tomivirkki** [comment]
The documentation still mentions previous functionality only.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 483 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-KUVnSyGoJgCb6tJ3MiS:-KUVnSyGoJgCb6tJ3MiT:b-twzlqt) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/64f48c1c1abab7feaa60cfa4d83e2fb679dfca2e/vaadin-date-picker-overlay.html#L483)):*
> ```HTML
> 
>       _onTodayTap: function() {
>         var today = new Date();
> ```

Unnecessary variable

---

*[vaadin-date-picker-overlay.html, line 484 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-KUVnleleElRL0hhp8kI:-KUVnleleElRL0hhp8kJ:b819hak) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/64f48c1c1abab7feaa60cfa4d83e2fb679dfca2e/vaadin-date-picker-overlay.html#L484)):*
> ```HTML
>       _onTodayTap: function() {
>         var today = new Date();
>         if (this._visibleMonthIndex === this._differenceInMonths(new Date(), this._originDate)) {
> ```

This could also allow selection when the _visibleMonthIndex is the previous month. Currently it selects today if scrolled slightly downwards (today's month is partly visible) but doesn't select when scrolled a bit upwards (today's month fully visible).

Or should we rather only allow selection when position is exactly at the beginning of the month only?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-:-KUVoeu955B_mOyapOAV:b-qcvf9z)*

**Comment by platosha** [comment]
@tomivirkki updated the documentation.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 483 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-KUVnSyGoJgCb6tJ3MiS:-KUWIfVDHkyyq1_YaP5U:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/64f48c1c1abab7feaa60cfa4d83e2fb679dfca2e/vaadin-date-picker-overlay.html#L483)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Unnecessary variable
</details>
Done.

---

*[vaadin-date-picker-overlay.html, line 484 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-KUVnleleElRL0hhp8kI:-KUWIgM6rhEipdN4M1tm:b-ea2sfk) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/64f48c1c1abab7feaa60cfa4d83e2fb679dfca2e/vaadin-date-picker-overlay.html#L484)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This could also allow selection when the _visibleMonthIndex is the previous month. Currently it selects today if scrolled slightly downwards (today's month is partly visible) but doesn't select when scrolled a bit upwards (today's month fully visible).
> 
> Or should we rather only allow selection when position is exactly at the beginning of the month only?
</details>
Changed to select only when exactly positioned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-:-KUWIXb1kW7NfkHw70oy:b2nmqb0)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-:-KUWSK8q7Yp2wXMt5HiH:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-:-KUWViMMhM-5debRlqPj:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264)*

**Comment by jouni** [comment]
Some observations:
- Today button is quite redundant when that day is outside the valid range (and actually allows you to select an invalid date). Should be disabled if today is outside min and max limits.
- I would like that there’s a little bit of “leeway” in the position check, so that even if today is not _exactly_ in the middle of the dropdown viewport, it would still select it and close the popup. So it would be enough that “today” date is inside the middle area of the popup (inside the "50% height box" of the overall popup, see the illustration):
screen shot 2016-10-20 at 15 48 49

**Comment by jouni** [comment]
Just to add to my previous comment: we can make new issues from my observations if you want to merge this work already. It’s already an improvement. But if you don’t want to leave these related things hanging…

Also, I suppose the proposed styling classes for the today button, based on the scroller position, are not implemented in this patch.

**Comment by samiheikki** [comment]
Can this be merged? ping @platosha. I see two LGTMs.

**Comment by platosha** [comment]
I’ve added range-based disabling for the today button, but not the other changes yet.

The positioning logic here is a bit challenging to implement. The current implementation of the month scroller relies on the top month as a zero-point. That’s why when we scroll the overlay to `today`, or any other initial date, programmatically, it will not vertically center the date, but instead bring the month to the exact top. @jouni’s comment above makes me think that we should position any initial date in the vertical center. Might be a good thing overall, but not relevant to stuff in this PR, I believe.

The styling “classes” (mixins, I assume?) for the today button states also don’t fit here, as we don’t have any button mixins at all yet.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-:-KUqi8nfBrteRhXXoTSG:b-s46nt4)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker-overlay.html, line 483 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-KUueLdsIsPAkBxEo72x:-KUueLdsIsPAkBxEo72y:bljmoe2) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fa58c799b66c1a9f68c0a16ea5a0b5be43765682/vaadin-date-picker-overlay.html#L483)):*
> ```HTML
> 
>       _onTodayTap: function() {
>         if (this.$.todayButton.disabled) {
> ```

This check shouldn't be needed. If the button is disabled, it will never fire a tap event.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264)*

**Comment by platosha** [comment]
Issues splitted-out: #270 vertical centering, #271 overlay button states

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-:-KUufESa6amTKAKq7Lz6:b-tiv1op)*

**Comment by platosha** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-overlay.html, line 483 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264#-KUueLdsIsPAkBxEo72x:-KUv3KoOw_d0rPMuI3lO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fa58c799b66c1a9f68c0a16ea5a0b5be43765682/vaadin-date-picker-overlay.html#L483)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This check shouldn't be needed. If the button is disabled, it will never fire a tap event.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/264)*

**Pull request merged**
