### PR TITLE
Show the error indicator when required

### LINKED ISSUE #123: Should show error indicator in iron-form
If you place a `vaadin-date-picker` (with `required`) into an `iron-form` and try to submit the form, the component should show an error indicator for missing value.

The `vaadin-combo-box` in the attached image has a correct error indicator, `vaadin-date-picker` inside the same form doesn't.

screenshot 2016-03-17 10 24 23

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #123

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/127)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 489 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127#-KD8cdn5YyUyOGTnns7-:-KD8cdn6FkWgSdFBVQPG:1573436549) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e5e5d0c52f0c5dc9da65badb064a43a8b8843213/vaadin-date-picker.html#L489)):*
Not really sure how the validation should behave, but if you take a look at the `_getValidity` method from `IronValidatableBehavior`, it uses a `validator` property that can be assigned. Our overriding implementation would bypass any `validator` that might be set to the `vaadin-date-picker`.

https://github.com/PolymerElements/iron-validatable-behavior/blob/master/iron-validatable-behavior.html#L126

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 489 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127#-KD8cdn5YyUyOGTnns7-:-KD8iNe1I5PUSdHaQ7CU:-1598627757) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e5e5d0c52f0c5dc9da65badb064a43a8b8843213/vaadin-date-picker.html#L489)):*
It's seems to be private: "_validator"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 489 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127#-KD8cdn5YyUyOGTnns7-:-KD8kZbqqWjYg0GBYVtN:1367092149) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e5e5d0c52f0c5dc9da65badb064a43a8b8843213/vaadin-date-picker.html#L489)):*
Oh, but there is also a public property for it. I'll look into this in more detail.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 489 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127#-KD8cdn5YyUyOGTnns7-:-KD8wdGHVIuO7FVnB3_s:598332802) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e5e5d0c52f0c5dc9da65badb064a43a8b8843213/vaadin-date-picker.html#L489)):*
Discussed this with Tomi. I will create a separate issue about custom validators.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127)*

**Comment by tehapo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/127#-:-KD8wiOJuuY6R6rgs_RG:1417088721)*

**Pull request merged**
