### PR TITLE
Add documentation in Asciidoc

### LINKED ISSUE #26: Write Asciidoc documentation

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #26 

This PR adds initial version of the Asciidoc documentation for `vaadin-date-picker`. The component is in early alpha stage, so there is not much to document at this point.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/28)

### CODE REVIEW

**Comment by magi42** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[docs/vaadin-date-picker-overview.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA-yn-_Af-IH9uoTMUS:-KA-yn-aO3dBx9RB7blb:1360698460) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L10)):*
* Looks like we need a style name for element names, as well as property names. Perhaps I should add them ASAP, so you could start using markup such as `[elementname]#vaadin-date-picker#` already.
* Add a comma before "which". I'm not sure if the clause is restrictive or not, so that it should use "that" instead. I'd think not.

---

*[docs/vaadin-date-picker-overview.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA0-oQVPqP3Uvk0M6SY:-KA0-oQWPJo_42Um5jjh:-1039342320) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L11)):*
* _The_ user
* ~~correct~~ -> _a_
* ~~making a selection~~ -> _select a date_
* mouse -> _the_ mouse
* _a_ touch device
* Not sure if it's really relevant to state that it's possible to select something both with the mouse and a touch device, as then you'd need to mention that with every feature and it's sort of obvious. Maybe better leave the "with the mouse or a touch device" entirely out.

---

*[docs/vaadin-date-picker-overview.adoc, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA00qqPwBJBrjOvHz1B:-KA00qqQ5M6mTmtdANor:628325716) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L12)):*
* "_When a date is selected, ..._"
* ~~also~~
* a ~~clear icon~~ -> a button
* ~~after~~ -> _on the right side of_

---

*[docs/vaadin-date-picker-overview.adoc, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA01X9zuKpp-aWbEa5_:-KA01XA-GHSuIjBN6pJt:-1388617830) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L14)):*
* _The_ current alpha version
* Change ", but f" to a new sentence.
* ~~like~~ -> _such as_ (more formal and there's also a slight difference in use)

---

*[docs/vaadin-date-picker-value.adoc, line 8 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA03au7y7hvEUlQOTVY:-KA03au7y7hvEUlQOTVZ:472405906) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L8)):*
The value isn't really "handled", but rather changes in the value or user input. In this context, value changes are "date picks" or selection, so maybe talk about that. "Handling Date Selection".

---

*[docs/vaadin-date-picker-value.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA02g1N41_aDFnxx6YB:-KA02g1N41_aDFnxx6YC:342935704) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L10)):*
* _The_ user
* Also here, it's rather obvious or irrelevant that the user uses the mouse or a touch device. Maybe rather say: "The user can select a date by clicking or tapping on it."

---

*[docs/vaadin-date-picker-value.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04H6PMEDA4N-bBUAl:-KA04H6Qy9X1H_Yezwgl:-468914856) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L11)):*
* Maybe: "_Use of keyboard for navigation or for entering the date_..."

---

*[docs/vaadin-date-picker-value.adoc, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04S8mWMb-Qc6NFoTy:-KA04S8n-8MkYL_DRdCu:-1888744140) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L13)):*
* Use `[classname]#Date#` and `[classname]#String#` for such objects.

---

*[docs/vaadin-date-picker-value.adoc, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04gOLj0ylxvcGecUj:-KA04gOLj0ylxvcGecUk:-1512417985) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L14)):*
* We really need the `[propertyname]#value#` style name... Coming soon – maybe it's best if you start using it already.
* I'd repeat the _by_ proposition in the disjunction (or), as the verbs "assign" and "using" refer to different objects.

---

*[docs/vaadin-date-picker-value.adoc, line 15 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04baQZfye0tANywsR:-KA04baQZfye0tANywsS:727822120) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L15)):*
Same here, use `classname`style.

---

*[docs/vaadin-date-picker-value.adoc, line 22 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA050FqHo0Aw6kJzO0W:-KA050FrT3IePa30HfXB:-256463298) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L22)):*
Hmm, what kind of thing would the `value-changed` listener be... Is it a property or method or what... (To set the style name.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28)*

**Comment by tomivirkki** [comment]
Review status: 1 of 3 files reviewed at latest revision, 11 unresolved discussions.

---

*[docs/vaadin-date-picker-overview.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA-yn-_Af-IH9uoTMUS:-KA0BYsy4d_Xfb59KXEJ:1683877468) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L10)):*
Added the comma. Can't say if "that" would be better than "which". Maybe "...field with a scrollable..."?

---

*[docs/vaadin-date-picker-overview.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA0-oQVPqP3Uvk0M6SY:-KA0DrO2GYUr16E-CDdd:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L11)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA00qqPwBJBrjOvHz1B:-KA0DzitLFNKJiITqisj:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L12)):*
Done.

---

*[docs/vaadin-date-picker-overview.adoc, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA01X9zuKpp-aWbEa5_:-KA0E-HonKsGxlrG3Ff8:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L14)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 8 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA03au7y7hvEUlQOTVY:-KA0E-v6ETxBuMEZz2fK:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L8)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA02g1N41_aDFnxx6YB:-KA0E0N5VsRh4mKzCDp_:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L10)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04H6PMEDA4N-bBUAl:-KA0E1q7DFd-12a1Tlgr:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L11)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04S8mWMb-Qc6NFoTy:-KA0E2SUFDgIUIbmxQ1c:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L13)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04gOLj0ylxvcGecUj:-KA0EjTJlqC2GLr7Dn2c:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L14)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 15 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA04baQZfye0tANywsR:-KA0EkuD52ijMNspzo1R:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L15)):*
Done.

---

*[docs/vaadin-date-picker-value.adoc, line 22 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA050FqHo0Aw6kJzO0W:-KA0FBzTq86CJkZxvZ2E:-315794512) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-value.adoc#L22)):*
Hmm....good question. Its "a string representing the event type" so I guess [eventtype]...or [eventname]?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28)*

**Comment by magi42** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-date-picker-overview.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA-yn-_Af-IH9uoTMUS:-KAA4zgbLNLkoT3jKtEq:-863145554) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L10)):*
"...field with a scrollable..." would indeed be better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28)*

**Comment by magi42** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-date-picker-overview.adoc, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28#-KA-yn-_Af-IH9uoTMUS:-KAAM2VhnjhJ925ly_MD:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ab9b979f15dca980edff1e0434b81a801388eec1/docs/vaadin-date-picker-overview.adoc#L10)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28)*

**Comment by magi42** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/28)*

**Pull request merged**
