### PR TITLE
Fix missing showWeekNumbers in vaadin-date-picker-light

### LINKED ISSUE #456: showWeekNumbers is not working for <vaadin-date-picker-light>
`<vaadin-date-picker-light>` is missing a binding for `showWeekNumbers`.

Use case:
```html
<vaadin-date-picker-light show-week-numbers>
    <iron-input><input></iron-input>
</vaadin-date-picker-light>
```

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #456

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/459)

### CODE REVIEW

**Comment by web-padawan** [comment]
BTW, there are  unused `iron-form` and `iron-meta` imports in the custom input test (and maybe others need to be checked as well).
I left these untouched for the moment since unrelated, but some cleanup would be nice.
@tomivirkki WDYT?

**Comment by tomivirkki** [comment]
👍  Unrelated cleanup can be done in a separate PR

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/459#-KyFqDTAZUEt6qIlalnH:-KyFqDTAZUEt6qIlalnI:b-svv6z7) (no related file):*
Tests failure in Safari 10 is unrelated to this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/459)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/459#-:-KyGEX_cu-nGYc68aHgj:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/459#-:-KyGXGmXf67098hzOOVZ:bnfp4nl)*

**Pull request merged**
