### PR TITLE
Clearing all ancestor -webkit-overflow-scrolling: touch values on open

### LINKED ISSUE #66: Date picker is shown under toolbar in paper-header-panel on iOS
img_0526

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #66

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/77)

### CODE REVIEW

**Comment by platosha** [comment]
Could we support shadow DOM containers in this workaround?

I mean, during traversing parents, try to jump to `element.domHost` when the element has no `parentElement`.

See for example: `_isParentFixed` check in combo-box: https://github.com/vaadin/vaadin-combo-box/blob/21a3c7a36caef81f6da7673b77a0fc8069dd4c2f/vaadin-overlay-behavior.html#L63

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-date-picker.html, line 191 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhRjWt9JpM5xTXhr0e:-KBhRjWu6G6VK6VR9dXo:483263587) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e38898dc2a8746e2f58c67c24734cc5d58c735e5/vaadin-date-picker.html#L191)):*
Would it be better to transform the recursion into `while (smth.parentElement)` loop? Recursive calls are a bit hard to read, but too easy to break.

---

*[vaadin-date-picker.html, line 176 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhWFt1fT3CIm790dhX:-KBhWFt1fT3CIm790dhY:-5700292) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/vaadin-date-picker.html#L176)):*
Would prefer to have all arguments of `_iOSpreventWebkitOverflowScrollingTouch` as optional, and then to skip them it in this initial call.

Also would be nice to add a feature-detection for `webkitOverflowScrolling` style, and to skip the workaround if it's not there.

---

*[vaadin-date-picker.html, line 181 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhVCs-PF0dlS9MVcqm:-KBhVCs0RN4TQtFUcSgk:994385632) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/vaadin-date-picker.html#L181)):*
`iOSPreventWebkitOverflowScrollingTouch` — with uppercase P it would be more consistent camelCase.

---

*[vaadin-date-picker.html, line 182 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhVyTlxVqS2i-1IgOG:-KBhVyTlxVqS2i-1IgOH:-1656646487) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/vaadin-date-picker.html#L182)):*
Should we really check the datepicker itself on the first step? Would it make more sense to start right with its parent instead?

---

*[test/dropdown.html, line 45 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhUTXGRvzpaDLNCt0g:-KBhUTXGRvzpaDLNCt0h:-2120845458) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/test/dropdown.html#L45)):*
Would make more sense to check explicitly if it returns back to the previous `'touch'` value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-:-KBhSugSs4bgwRadfZMc:-1846389838)*

**Comment by tomivirkki** [comment]
The point is to traverse all the elements in the dom, not just the web components themselves. For example with paper-header-panel the problematic element is inside the local dom. Luckily for us, iOS Safari doesn't support native shadow at the moment.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-date-picker.html, line 191 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhRjWt9JpM5xTXhr0e:-KBhZb3sPsnUy3M6lnuR:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/e38898dc2a8746e2f58c67c24734cc5d58c735e5/vaadin-date-picker.html#L191)):*
Done.

---

*[vaadin-date-picker.html, line 176 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhWFt1fT3CIm790dhX:-KBhcPqwB-uXjaIyDjF5:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/vaadin-date-picker.html#L176)):*
Done.

---

*[vaadin-date-picker.html, line 181 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhVCs-PF0dlS9MVcqm:-KBhYq-v6Ps0nG-ro50I:-2094431190) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/vaadin-date-picker.html#L181)):*
Removed the whole _iOS -prefix

---

*[vaadin-date-picker.html, line 182 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhVyTlxVqS2i-1IgOG:-KBhZ2MNjSFumHlMG1jh:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/vaadin-date-picker.html#L182)):*
Done.

---

*[test/dropdown.html, line 45 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-KBhUTXGRvzpaDLNCt0g:-KBhcMh725zpyoS0VVUR:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c5204d7a5d6ac0cbb1ba81e983a27a96a8a1b7c2/test/dropdown.html#L45)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-:-KBhXVLWKa2UW0MhFIBi:128337984)*

**Comment by platosha** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77#-:-KBhcu2nOKoNSgYg9ZMk:980077423)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/77)*

**Pull request merged**
