### PR TITLE
Remove Polymer.GestureEventListeners

### PR DESCRIPTION
**Pull request by limonte**
The same as https://github.com/vaadin/vaadin-text-field/pull/108

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/428)

### CODE REVIEW

**Comment by manolo** [comment]
There are still many references to tap in other date-picker internal elements, shouldn't we change them to click at the same time?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/428#-:-Kttu2tEWR_KZlYX1uHX:blapc7j)*

**Comment by limonte** [comment]
This PR is related to `vaadin-date-picker.html` only. Other files could be updated later.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/428#-:-KttuwivwobuUMycDr0_:b-7n9tsj)*

**Comment by manolo** [comment]
I'd rather to cover everything at once, it could be confusing for the user that tap are used or not in different parts of the component. 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/428#-:-KtuK_jD9lS1xVnNKVTe:b8akw4k)*

**Comment by limonte** [comment]
> I'd rather to cover everything at once, it could be confusing for the user that tap are used or not in different parts of the component.

Done.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/428#-:-KyUpoah33W2z6b-7hM3:bqd644u)*

**Comment by samiheikki** [comment]
Rebase to master and change this line also https://github.com/vaadin/vaadin-date-picker/blob/master/test/basic.html#L283

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/428#-:-Kz-hmrhgzNLuXABwI2l:bvfwf6x)*

**Pull request closed without merging**
