### PR TITLE
Add vaadin-overlay

### LINKED ISSUE #465: Use <vaadin-overlay> for dropdown
Switch from `<iron-dropdown>` to `<vaadin-date-picker-overlay>` (so the element doesn't get clipped).

https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L89 -> vaadin-overlay

- Keep API backwards compatible (if possible)
- Fullscreen mode must still work
- Add max-height (approx 2 calendars) to the overlay in default theme
- Implement sizing/positioning to adjust the vaadin-overlay (remove all unnecessary code)

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fix #465

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/482)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 16 files at r1.
Review status: 3 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 457 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-W_Qn3cSF97DciPV1p:-L-W_Qn3cSF97DciPV1q:b-smz4g5) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1b9d12a8c1b6f76f1d1948a042900b3c07ef2c9d/vaadin-date-picker-mixin.html#L457)):*
> bottomAlign = this.getBoundingClien

---

*[vaadin-date-picker-mixin.html, line 463 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WbYzxw1fI95U2eKN7:-L-WbYzxw1fI95U2eKN8:bamv5j4) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L463)):*
> ```HTML
> 
>       if (!this._fullscreen) {
>         this.$.overlay.style.left = inputRect.left + 'px';
> ```

Right alignment mode was dropped. Is that intentional?

IMO we’d better continue supporting it. Align on the right side of the input is a nice fit for certain UIs:



---

*[vaadin-date-picker-mixin.html, line 465 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WYovNx0nn_y-SqRT6:-L-WYovNx0nn_y-SqRT7:b-k7a6ri) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L465)):*
> ```HTML
>         this.$.overlay.style.left = inputRect.left + 'px';
> 
>         this.$.overlay.style.top = ((inputRect.top <= window.innerHeight - inputRect.top) ? inputRect.bottom :
> ```

Well, good that this is short, but really hard to wrap one’s head about it.

Let’s maybe unwrap this trickery into individual pieces?

I really like how the old piece was written: first it computes two boolean align flags `bottomAlign` and `rightAlign`, then applies positioning depending on the flag values.

That would be rather long and explicit, but also much easier to read.

Also: for the bottom align mode, I would expect the overlay host to be constrained with the `bottom` property, not the `top`.

---

*[vaadin-date-picker-mixin.html, line 629 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WcakchSVQtuVQs9Ln:-L-WcakchSVQtuVQs9Lo:bagd9h0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L629)):*
> ```HTML
>     }
> 
>     _focusInput() {
> ```

Looks like a duplicate of `_focus()`, can we merge them somehow?

---

*[vaadin-date-picker-mixin.html, line 739 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-Wd5WcB-zb5sEaoDKh:-L-Wd5WcB-zb5sEaoDKi:b409eyz) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L739)):*
> ```HTML
>           // iOS needs a refit after input blur animation has finished
>           this._debouncerRefit = Polymer.Debouncer.debounce(this._debouncerRefit,
>             Polymer.Async.timeOut.after(500), this.$.overlay.refit);
> ```

`refit` is the `<iron-dropdown>`’s method, looks like it does not exist on the `<vaadin-date-picker-overlay>`.

Most probably we don’t need this anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by web-padawan** [comment]
Please also incorporate the fix from #474

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-Xoqms70-q7y_4C_7C:-L-Xoqms70-q7y_4C_7D:b-2hxrrp) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-overlay.html#L11)):*
> ```HTML
>        * ### Styling
>        *
>        * [Generic styling/theming documentation](https://cdn.vaadin.com/vaadin-valo-theme/0.3.1/demo/customization.html)
> ```

nit: this can be removed  per vaadin/components-team-tasks#292

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-Xsr92m4E9SA-9_pNh:b-98pgf2)*

**Comment by YuriyVaadin** [comment]
Review status: 11 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 457 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-W_Qn3cSF97DciPV1p:-L-agPaDIvlLYEKHVW9d:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1b9d12a8c1b6f76f1d1948a042900b3c07ef2c9d/vaadin-date-picker-mixin.html#L457)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

> bottomAlign = this.getBoundingClien
</blockquote></details>

Done.

---

*[vaadin-date-picker-mixin.html, line 465 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WYovNx0nn_y-SqRT6:-L-agQARI0-8FtmYVMyu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L465)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Well, good that this is short, but really hard to wrap one’s head about it.

Let’s maybe unwrap this trickery into individual pieces?

I really like how the old piece was written: first it computes two boolean align flags `bottomAlign` and `rightAlign`, then applies positioning depending on the flag values.

That would be rather long and explicit, but also much easier to read.

Also: for the bottom align mode, I would expect the overlay host to be constrained with the `bottom` property, not the `top`.
</blockquote></details>

Done.

---

*[vaadin-date-picker-mixin.html, line 629 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WcakchSVQtuVQs9Ln:-L-agQlcYJPhMfMC1w8X:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L629)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Looks like a duplicate of `_focus()`, can we merge them somehow?
</blockquote></details>

Done.

---

*[vaadin-date-picker-mixin.html, line 739 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-Wd5WcB-zb5sEaoDKh:-L-agRM2FX7Yo4f1LMHD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L739)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`refit` is the `<iron-dropdown>`’s method, looks like it does not exist on the `<vaadin-date-picker-overlay>`.

Most probably we don’t need this anymore.
</blockquote></details>

Done.

---

*[vaadin-date-picker-overlay.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-Xoqms70-q7y_4C_7C:-L-agRmdz1hbtBDXMc-L:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-overlay.html#L11)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: this can be removed  per vaadin/components-team-tasks#292
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by platosha** [comment]
Review status: 11 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 463 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WbYzxw1fI95U2eKN7:-L-aifM762PglfbrWHPz:bo98l82) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L463)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Right alignment mode was dropped. Is that intentional?

IMO we’d better continue supporting it. Align on the right side of the input is a nice fit for certain UIs:



</blockquote></details>

OK now that it’s back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker-mixin.html, line 469 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-aiOpYnihQ5SkpVxJe:-L-aiOpYnihQ5SkpVxJf:b-gtqjqn) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f0559ef0317666e23e370ea933fec0bbf2485d89/vaadin-date-picker-mixin.html#L469)):*
> ```HTML
>           this.$.overlay.setAttribute('right-aligned', '');
>           this.$.overlay.style.removeProperty('left');
>           this.$.overlay.style.right = (window.innerWidth - inputRect.right) + 'px';
> ```

We shouldn't use `window.innerWidth` and `window.innerHeight` since they don't consider scrollbars: https://www.dropbox.com/s/60gvatu48e78m22/Screenshot%202017-12-05%2014.52.16.png?dl=0

Combo-box records the previous value of applied left/right values and includes them in calculation which makes its positioning independent of any environmental differences. Should probably use the same approach here: https://github.com/vaadin/vaadin-combo-box/blob/93229f4454fd4c59497d8bb293ebcf76926ebf4f/vaadin-combo-box-dropdown.html#L243

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by platosha** [comment]
Review status: 11 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 469 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-aiOpYnihQ5SkpVxJe:-L-b7H_5voLfWRQhZ5bw:b230a8o) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f0559ef0317666e23e370ea933fec0bbf2485d89/vaadin-date-picker-mixin.html#L469)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We shouldn't use `window.innerWidth` and `window.innerHeight` since they don't consider scrollbars: https://www.dropbox.com/s/60gvatu48e78m22/Screenshot%202017-12-05%2014.52.16.png?dl=0

Combo-box records the previous value of applied left/right values and includes them in calculation which makes its positioning independent of any environmental differences. Should probably use the same approach here: https://github.com/vaadin/vaadin-combo-box/blob/93229f4454fd4c59497d8bb293ebcf76926ebf4f/vaadin-combo-box-dropdown.html#L243


</blockquote></details>

The environment is stable in case of `<vaadin-overlay>`: overlay’s position is always `fixed`, so the coordinates are always viewport-related. No need to record/subtract coordinates.

Looks like `window.innerHeight` could be both less and more than `document.documentElement.clientHeight`, so we can’t avoid using `Math.min`: 
```javascript
const viewportHeight = Math.min(window.innerHeight, document.documentElement.clientHeight);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker-mixin.html, line 469 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-aiOpYnihQ5SkpVxJe:-L-bBIg9XBHfxPVtCDJR:b-qhjy86) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f0559ef0317666e23e370ea933fec0bbf2485d89/vaadin-date-picker-mixin.html#L469)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The environment is stable in case of `<vaadin-overlay>`: overlay’s position is always `fixed`, so the coordinates are always viewport-related. No need to record/subtract coordinates.

Looks like `window.innerHeight` could be both less and more than `document.documentElement.clientHeight`, so we can’t avoid using `Math.min`: 
```javascript
const viewportHeight = Math.min(window.innerHeight, document.documentElement.clientHeight);
```
</blockquote></details>

Sounds good :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by YuriyVaadin** [comment]
Review status: 11 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 463 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-WbYzxw1fI95U2eKN7:-L-jzf0JoFlx-t9H1Hds:b-dfqh1h) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b5085ec5b1fae71dca3a7a1c103c452af303779b/vaadin-date-picker-mixin.html#L463)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK now that it’s back
</blockquote></details>

Is it Ok now or should I improve it?

---

*[vaadin-date-picker-mixin.html, line 469 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-aiOpYnihQ5SkpVxJe:-L-jzcsGdqWilcNSK40f:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f0559ef0317666e23e370ea933fec0bbf2485d89/vaadin-date-picker-mixin.html#L469)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Sounds good :+1: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by tomivirkki** [comment]
*[bower.json, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-k5NYJ-xXe9fnUF0M8:-L-k5NYJ-xXe9fnUF0M9:b-zd1nj4) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/852307e1cf9840c44d05528c4708b9234774e0a0/bower.json#L24)):*
> ```JSON
>     "iron-a11y-announcer": "^2.0.0",
>     "iron-a11y-keys-behavior": "^2.0.0",
>     "iron-dropdown": "^2.0.0",
> ```

At least iron-dropdown and iron-overlay-behavior are no longer used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by YuriyVaadin** [comment]
Review status: 9 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[bower.json, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-k5NYJ-xXe9fnUF0M8:-L-kEJ739ZXnQforx5kK:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/852307e1cf9840c44d05528c4708b9234774e0a0/bower.json#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

At least iron-dropdown and iron-overlay-behavior are no longer used?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by web-padawan** [comment]
Reviewed 3 of 5 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by tomivirkki** [comment]
*[bower.json, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-k5NYJ-xXe9fnUF0M8:-L-kIh5DO8q5ubIuk5Jj:bfhqml6) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/852307e1cf9840c44d05528c4708b9234774e0a0/bower.json#L24)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Removed.
</blockquote></details>

Not done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 9 of 16 files at r1, 3 of 5 files at r2, 1 of 1 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-kLPTJAfhwVJ-NrwAE:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-date-picker-overlay-content.html, line 192 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-kVIowXkU2MlfSSYJ6:-L-kVIowXkU2MlfSSYJ7:bn74zt8) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0145c53907c290b8278ec7e77efa73e541faa734/vaadin-date-picker-overlay-content.html#L192)):*
> ```HTML
> 
>     <div id="scrollers" desktop$="[[_desktopMode]]" on-track="_track">
>       <vaadin-infinite-scroller id="monthScroller" on-custom-scroll="_onMonthScroll" on-touchstart="_onMonthScrollTouchStart" buffer-size="6" active="[[initialPosition]]" part="months">
> ```

Now that we're actually limiting the overlay height, buffer-size could be decreased to improve performance (it will render less calendars in the DOM). Same thing with yearScroller.

---

*[vaadin-date-picker.html, line 9 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-kUk24mVbN3vvq_F9e:-L-kUk24mVbN3vvq_F9f:brwb0hc) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1b9d12a8c1b6f76f1d1948a042900b3c07ef2c9d/vaadin-date-picker.html#L9)):*
> ```HTML
> <link rel="import" href="../polymer/polymer-element.html">
> <link rel="import" href="../polymer/lib/mixins/gesture-event-listeners.html">
> <link rel="import" href="../iron-dropdown/iron-dropdown.html">
> ```

Looks like dropping this removed Gestures import or something. Clicking the text-field no longer opens the dropdown. Either import Gestures or even better, listen to click instead of tap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by platosha** [comment]
Please include updated analysis.json:

```sh
$ polymer analyze vaadin-*.html > analysis.json
```

There is one small thing noticable in the API docs after analysis.json update: the `<vaadin-date-picker-overlay>` element is listed under the `Vaadin` namespace. We seem to have a (IMO good) practice to only list public endpoint components in the namespace, and delist “internal” stuff.



Let us, maybe, remove the `DatePickerOverlayElement` class from the namespace for now?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-kkJGeETiGKiVGl94v:b-2mruon)*

**Comment by platosha** [comment]
Found an issue: the datepicker light does not close on mobile (iOS Safari) on tapping a date. Steps to reproduce:

1. Open advanced demos in mobile

2. Open one of the `<vaadin-date-picker-light>` elements, use “Custom Inputs” demo

3. Tap a date in the datepicker overlay

Expected: overlay closes, and the input displays selected date.

Actual: the date is selected in the overlay, but the overlay does not close.

---

Review status: 13 of 17 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-l5tUzl3Zv7lnisyJS:bha34yv)*

**Comment by YuriyVaadin** [comment]
> Found an issue

Fixed.

---

Review status: 12 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower.json, line 24 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-k5NYJ-xXe9fnUF0M8:-L-l6kTbbWJ3UU0hydfr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/852307e1cf9840c44d05528c4708b9234774e0a0/bower.json#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.

---

*[vaadin-date-picker-overlay-content.html, line 192 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-kVIowXkU2MlfSSYJ6:-L-l6lQCgUjh5WCJOMfU:b-a2ujfl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0145c53907c290b8278ec7e77efa73e541faa734/vaadin-date-picker-overlay-content.html#L192)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Now that we're actually limiting the overlay height, buffer-size could be decreased to improve performance (it will render less calendars in the DOM). Same thing with yearScroller.
</blockquote></details>

Changed.

---

*[vaadin-date-picker.html, line 9 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-L-kUk24mVbN3vvq_F9e:-L-l6mhxLnAA_VziheBV:b-p33edw) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1b9d12a8c1b6f76f1d1948a042900b3c07ef2c9d/vaadin-date-picker.html#L9)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Looks like dropping this removed Gestures import or something. Clicking the text-field no longer opens the dropdown. Either import Gestures or even better, listen to click instead of tap.
</blockquote></details>

Restored gestures functionality. Will be switched to click in other PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-l6gF92BKNFA_8jiW0:bv7halh)*

**Comment by tomivirkki** [comment]
One more issue. When you click the input field on Android, it opens the virtual keyboard.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-l912LQe7QM4f4MLbr:blg9ao4)*

**Comment by platosha** [comment]
Reviewed 9 of 16 files at r1, 3 of 5 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482)*

**Comment by tomivirkki** [comment]
The issue is in master, not a regression in this PR. :lgtm: 

---

Reviewed 5 of 5 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-pIRWdPD_bGTFW41fY:b-nnfj7o)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/482#-:-L-pgH-EGb6ZT3MubEU7:bnfp4nl)*

**Pull request merged**
