### PR TITLE
Make datepicker modal by setting body pointer-events: none

### LINKED ISSUE #289: Make overlay modal
Same issues as in combo box: https://github.com/vaadin/vaadin-combo-box/issues/343

We might want to consider this at the same time as we refactor the overlay to behave similarly as in combo box (place it under the `<body>`).

### PR DESCRIPTION
**Pull request by limonte**
Fixes #289 

---

If this approach is okay, I'll try to figure out how to test it. But I need a feedback from the team about the approach.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/335)

### CODE REVIEW

**Comment by tomivirkki** [comment]
This approach works quite nice :+1:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-:-KbKqGNtSuWJZ1vsaugG:bpf1bju)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-behavior.html, line 496 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbLHI0PKzXBi-omIKgb:-KbLHI0PKzXBi-omIKgc:bn9vags) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/vaadin-date-picker-behavior.html#L496)):*
> ```HTML
>       // Set body pointer-events to 'none' to disable mouse interactions with
>       // other document nodes (datepicker is "modal")
>       this._documentPointerEvents = document.body.style.pointerEvents;
> ```

shuldn't `touch-action` be considered as well ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335)*

**Comment by limonte** [comment]
The Idea copyright goes to Anton :) Ready for review now.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-behavior.html, line 496 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbLHI0PKzXBi-omIKgb:-KbLLWl3nGi9Iq_m4Q6s:b-7zmtus) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/vaadin-date-picker-behavior.html#L496)):*
> touch-action

I just tested on iPad and all works fine w/o `touch-action`. I'll test on Windows tablet tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-:-KbL3VrWEWrJO2-jjAXV:b-j5mazm)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-behavior.html, line 498 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbOgfGokibSBQjOpJia:-KbOgfGpke54PfgWPO68:bv2yrx1) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/vaadin-date-picker-behavior.html#L498)):*
> ```HTML
>       this._documentPointerEvents = document.body.style.pointerEvents;
>       document.body.style.pointerEvents = 'none';
>       this.style.pointerEvents = 'auto';
> ```

This also needs to be cleared on close. Better option might be to add style:
```
:host([opened]) {
  pointer-events: auto;
}
```

---

*[test/dropdown.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbOhLbSVIe6utpo0jDu:-KbOhLbSVIe6utpo0jDv:bg0t3kc) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/test/dropdown.html#L68)):*
> ```HTML
>         datepicker.open();
>         datepicker.async(function() {
>           datepicker._close();
> ```

You could move this `._close()`command inside the `iron-overlay-opened` listener (after the assertions) to avoid async

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335)*

**Comment by Saulis** [comment]
:lgtm: after Tomi's comments have been fixed.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-:-KbOjxDJrI1ejFKdeOCH:b-sikfvs)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-behavior.html, line 496 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbLHI0PKzXBi-omIKgb:-KbOnrMiTD2mKvxv5jm3:b-m648iu) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/vaadin-date-picker-behavior.html#L496)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> touch-action

I just tested on iPad and all works fine w/o `touch-action`. I'll test on Windows tablet tomorrow.
</blockquote></details>

Tested in Windows tablet, works fine without `touch-action`.

---

*[vaadin-date-picker-behavior.html, line 498 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbOgfGokibSBQjOpJia:-KbOnxb8JyExgG5u91u7:b-9yy7en) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/vaadin-date-picker-behavior.html#L498)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This also needs to be cleared on close. Better option might be to add style:
```
:host([opened]) {
  pointer-events: auto;
}
```
</blockquote></details>

Right, done.

---

*[test/dropdown.html, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-KbOhLbSVIe6utpo0jDu:-KbOo2o7V3WbwYBktbZY:b-opfte0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/810746c1c9e19f51ab0e053b8a281805db9748be/test/dropdown.html#L68)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

You could move this `._close()`command inside the `iron-overlay-opened` listener (after the assertions) to avoid async
</blockquote></details>

Done, thx!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/335#-:-KbPZ1imGpd0oFFsM-wF:bnfp4nl)*

**Pull request merged**
