### PR TITLE
Don't scroll to focused date on overlay tap

### LINKED ISSUE #298: Opening the popup, scrolling down and pressing mouse down should not scroll back up
### Steps to reproduce
1. Open demo/index.html
2. Open the first popup
3. Scroll down a month or two
4. Hold mouse down anywhere in the popup

### Expected outcome
Nothing happens

### Actual outcome
Popup is scrolled back up to show the current date

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [X] Safari

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #298

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/299)

### CODE REVIEW

**Comment by Saulis** [comment]
I'd rather leave the current behavior and fix #298 by preventing focusing on overlay by tapping/clicking? I think it's important to scroll to focused date when overlay is focused to clearly indicate to the user where the focus currently is. 

When the overlay is tapped/clicked, IMO it isnt mandatory to move the focus to the overlay since selecting a date is the primary function of clicking, which will close the overlay anyways.

**Comment by tomivirkki** [comment]
Changed the approach so that auto scroll is invoked only when the overlay is focused with 'tab'. Click/tap still blur the input and focus the overlay but don't scroll to the focused date.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KX5-GNHMTVztr43N9kR:b-e8kljb)*

**Comment by Saulis** [comment]
:+1: maybe a test to document + verify the intended behavior?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KX4zwaXXznrC039oo4W:b-dgnbnh)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-overlay.html, line 754 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-KX500IO_ug633NOcu0s:-KX500IO_ug633NOcu0t:bpg1m6y) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a3a30903a863dd59c9389575685f527a83a05a7d/vaadin-date-picker-overlay.html#L754)):*
> ```HTML
>             this._focused = !this._buttonFocused();
> 
>             this.debounce('overlay-focus', function() {
> ```

Not sure if this `debounce` serves any purpose here? There's not gonna be multiple `tab` keystrokes under `1ms` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299)*

**Comment by tomivirkki** [comment]
Tests added

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-overlay.html, line 754 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-KX500IO_ug633NOcu0s:-KX59rDgttmTsZsqc-Y3:bbxlffx) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a3a30903a863dd59c9389575685f527a83a05a7d/vaadin-date-picker-overlay.html#L754)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Not sure if this `debounce` serves any purpose here? There's not gonna be multiple `tab` keystrokes under `1ms` ?
</details>
Ah, good catch, meant to use async. Also removed all explicit `this._focused = ` clauses from this handler since the focus state is dominated by the async `blur`and `focus` events anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KX5DYUVTRNh-85N5euN:b-q952bo)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KX6X3FTlh0DVVZBjOEP:bnfp4nl)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KX9gyTafKo83IYh2X7q:bnfp4nl)*

**Comment by Saulis** [comment]
Looks like `should reveal the focused date on shift-tab focus from today button` is now failing on desktop?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KXA6vrD4iszMdxVcO-z:b50cb6k)*

**Comment by tomivirkki** [comment]
Fixed

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KXAM9PfHRHMABjVcyg_:b-886gsx)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/299#-:-KXAMuSN_bU9-KH9Xkv-:bnfp4nl)*

**Pull request merged**
