### PR TITLE
Keep the input field always in read-only mode

### LINKED ISSUE #225: The input box is enabled, and you can type in it
This is seen in both Chrome and Firefox (both latest).

Create a standard element:

    <vaadin-date-picker></vaadin-date-picker>

You will see that the following can be done:

Basically, I use the date picker ti pick a date. All good. Then in screenshot 3 you can see that I moved the cursor using the arrows. And then I typed CHANGED there.

There is another level to this bug. If you delete what's in the textbox, and then click on the date picker again and select the SAME date again, you will see that the textbox does NOT get restored -- since technically speaking the date hasn't changed.

This is a showstopper for us, since the app will be used from very computer illiterate people...! Happy to help with a PR for a fix -- please direct me a little in the code though...

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #225

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/226)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/226#-:-KQKbrvsROmsEInaLHFD:bnfp4nl)*

**Comment by tehapo** [comment]
Tests of this PR would fail at least on the Angular 2 part. I'll rebase this after #230 is merged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/226#-:-KQU4hl-MU62HCGc78_Z:b-cykeu1)*

**Comment by tehapo** [comment]
Seems that there is a problem with this change after all. An `input` field cannot be `readonly` and `required` at the same time. Having a field as `readonly` will disable all validation, which would also be needed for the `required` part.

Basically my current idea is to keep the field as writable but prevent user input in other ways. I'll look into this.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/226#-:-KQZJqou4ri8iApTJj2R:basvl2y)*

**Comment by tomivirkki** [comment]
Would it be an option to use disabled instead of readonly for the input? Or have an additional input type="hidden" next to the regular input?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/226#-:-KQdcYq--sNmzNAzjWM4:b-vllnie)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/226)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/226#-:-KQegdBE9n3IC3Qbvtnn:bnfp4nl)*

**Pull request merged**
