### PR TITLE
Set clear button not opening the overlay

### LINKED ISSUE #512: Don’t open the overlay when clearing the field using the “clear” button
See https://github.com/vaadin/vaadin-combo-box/issues/613

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #512 

Not sure if I can properly test the focused state of the input on mobile and desktop. Will be grateful for any suggestions.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/515)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515#-:-L6MAytSNWhaKC1YxOEt:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
Have removed `event` argument from `open` method, so it won't get to our documentation.
Checking for `e.target` in `_clear` (instead of setting to `true`) to be sure that we will be able to use `_clear` method elsewhere in future without breaking current functionality.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515#-:-L6MUTCkDr4QQUoJEXL_:bz659qm)*

**Comment by tomivirkki** [comment]
*[src/vaadin-date-picker-mixin.html, line 348 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515#-L6MWLu_XnpyPKJvCV5P:-L6MWLuaXmz3oXwUp4m0:b-yojbww) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/efa0ebf78b8ac01a31a2401ad1d39d1389a544b4/src/vaadin-date-picker-mixin.html#L348)):*
> ```HTML
>         this.$.overlay.opened = true;
>         this._updateAlignmentAndPosition();
>       } else if (this._cleared) {
> ```

The order for the if-else blocks is confusing.

instead of 
```
if (a && !b) {

} else if (b) {

}
```

use

```
if (b) {

} else if (a) {

}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515)*

**Comment by YuriyVaadin** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-date-picker-mixin.html, line 348 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515#-L6MWLu_XnpyPKJvCV5P:-L6MpGXVwHf3P05J1Tt9:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/efa0ebf78b8ac01a31a2401ad1d39d1389a544b4/src/vaadin-date-picker-mixin.html#L348)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The order for the if-else blocks is confusing.

instead of 
```
if (a && !b) {

} else if (b) {

}
```

use

```
if (b) {

} else if (a) {

}
```

</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/515#-:-L6Mq3JFLx-ANFkjtKGh:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-date-picker/515#-:-L6MqOslCYHrUJFIFuJ_:bnfp4nl)*

**Pull request merged**
