### PR TITLE
Fixes year scroller position in Firefox

### LINKED ISSUE #130: Year scroller position in Firefox
In Firefox the year scroller's years are on the left side.
Windows 10, Firefox 45.0.1

firefox_bug

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #130

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/135)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Doesn't look ok on os x now https://www.dropbox.com/s/l9za2p272n6cbox/Screenshot%202016-03-21%2013.43.38.png?dl=0

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-infinite-scroller.html, line 47 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-KDNzpePmMEgeYy0zKcQ:-KDNzpePmMEgeYy0zKcR:-482200176) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c2414c46e34308f9292554729b684d0fe0f91591/vaadin-infinite-scroller.html#L47)):*
Doesn't this kind of assume the width of the scrollbar?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDNzn93qut5ISAvwJu6:-20959305)*

**Comment by tehapo** [comment]
Except if you change to display scrollbars always, then it's fine on OSX too.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 48 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-KDO-eTIu8tbh5aMAqxl:-KDO-eTJDz9vBL_dyLJD:-319415471) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c2414c46e34308f9292554729b684d0fe0f91591/vaadin-infinite-scroller.html#L48)):*
No need to apply this line again here as it's already applied on all browsers anyway.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDO-rtcKeEExADV5txV:-655609752)*

**Comment by tomivirkki** [comment]
Yes. By default they're off.
We discussed during sprint planning to fix this by defining a fixed width for the year scroller buffers instead. Basically: 

--vaadin-infinite-scroller-buffer: {
...
width: 90px;
}

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDO0A0kddnDY_FATE7v:1664808018)*

**Comment by samiheikki** [comment]
Changed it to width,

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 47 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-KDNzpePmMEgeYy0zKcQ:-KDOFeL1eOotofrI4Vf1:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c2414c46e34308f9292554729b684d0fe0f91591/vaadin-infinite-scroller.html#L47)):*
Done.

---

*[vaadin-infinite-scroller.html, line 48 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-KDO-eTIu8tbh5aMAqxl:-KDOFemPJFTI9T2Pg8Wg:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c2414c46e34308f9292554729b684d0fe0f91591/vaadin-infinite-scroller.html#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDOFfY6PlgdxKo3a1AI:744206919)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135)*

**Comment by tehapo** [comment]
Now there appears a horizontal scrollbar in the year scroller (at least on OSX). Looks like it can be fixed by adding `overflow-x: hidden;` for the `#scroller` element.

---

Reviewed 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDOVaUlJhGfqyM_9LH6:1242245729)*

**Comment by samiheikki** [comment]
Done.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDRwFSqaB5QWfFjIvRr:-499146009)*

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/135#-:-KDS1LM-mI75GVvhrhul:1417088721)*

**Pull request merged**
