### PR TITLE
Feature/i18n title

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #152 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/164)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/164)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/164#-:-KF56u_Ys_x1tf7WMHWs:1417088721)*

**Comment by platosha** [comment]
The corresponding asciidoc changes are missing here.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/164#-:-KF9QBGTWHt_ttpSyyPy:447879683)*

**Comment by tomivirkki** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/164#-:-KF9SMrUdp2V9RAZ80l3:-499146009)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/164#-:-KF9TOL8jRHQUwhOayuB:1417088721)*

**Pull request merged**
