### PR TITLE
Dropdown close cancellation fixed for wrapped date picker

### LINKED ISSUE #156: Clicking the calendar icon no longer closes the dropdown
We might need to put the "pointer-events: none" workaround (that was removed in 2bfa222694ac8e508400774e5c1e76c4369c3713) back

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #156

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/177)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 501 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177#-KHKVeG_SZ3porPWMrNL:-KHKVeG_SZ3porPWMrNM:-1505421549) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/114f9d34ae513b4b3ed8a0fd64d034b5ab2bdba8/vaadin-date-picker.html#L501)):*
> ```HTML
>       _preventCancelOnComponentAccess: function(e) {
>         var isInPath = e.detail.path && e.detail.path.indexOf && e.detail.path.indexOf(this) !== -1;
>         var isLocal = isInPath || this.contains(e.detail.target);
> ```

Let us use `var event = Polymer.dom(e.detail);` to get the normalised original event, may be? Then you could do the same with just one check for `event.path.indexOf(this) > -1`.

Normalised Polymer event objects always have the `.path` array, the check is not needed.

---

*[test/dropdown.html, line 155 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177#-KHKVXQH9mNyZ50qK7EF:-KHKVXQH9mNyZ50qK7EG:-41763106) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/114f9d34ae513b4b3ed8a0fd64d034b5ab2bdba8/test/dropdown.html#L155)):*
> ```HTML
>       it('should not close on calendar icon mousedown', function(done) {
>         datepicker.addEventListener('iron-overlay-opened', function() {
>           Polymer.Base.fire('mousedown', {}, {
> ```

Would the `MockInteractions.tap` or `.down` call be cleaner here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 501 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177#-KHKVeG_SZ3porPWMrNL:-KHKcKKR6Od4i0xia19c:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/114f9d34ae513b4b3ed8a0fd64d034b5ab2bdba8/vaadin-date-picker.html#L501)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Let us use `var event = Polymer.dom(e.detail);` to get the normalised original event, may be? Then you could do the same with just one check for `event.path.indexOf(this) > -1`.
> 
> Normalised Polymer event objects always have the `.path` array, the check is not needed.</details>
Done.

---

*[test/dropdown.html, line 155 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177#-KHKVXQH9mNyZ50qK7EF:-KHKcL0ebPHbv70rAMrj:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/114f9d34ae513b4b3ed8a0fd64d034b5ab2bdba8/test/dropdown.html#L155)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Would the `MockInteractions.tap` or `.down` call be cleaner here?</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177)*

**Comment by platosha** [comment]
:lgtm:

<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> #### Dropdown close cancellation fixed for wrapped date picker
> 
> Fixes #156
> 
> 
> </details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/177#-:-KHKe4u0OkwOrgqWnUER:1417088721)*

**Pull request merged**
