### PR TITLE
Add initial localization support using Moment.js

### LINKED ISSUE #36: Add localization support
Localization (autodetection, 1st day of week, months, weekdays, date format, ...).

Nice idea would be to have each locale as a pluggable package. This would enable easy contributions to the component by providing new locales.

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #36 

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/37)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/basic.html, line 146 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAcw4qOueSau7shpsT2:-KAcw4qOueSau7shpsT3:620247317) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/cc25d35105700a753d882983aa3fb0edf673dd7a/test/basic.html#L146)):*
Magic numbers for a timeout should be avoided in tests. Rather use a waitUntil(condition, callback) pattern

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by tehapo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/basic.html, line 146 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAcw4qOueSau7shpsT2:-KAczjDgeGonDvdoq5Ni:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/cc25d35105700a753d882983aa3fb0edf673dd7a/test/basic.html#L146)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by tomivirkki** [comment]
Reviewed 6 of 7 files at r1, 1 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[test/month-calendar.html, line 29 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAd5EyqtUqDG3kfoCXC:-KAd5EyrPPlQWPIP0FcV:1111741374) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/test/month-calendar.html#L29)):*
Why not extract this function to common?

---

*[vaadin-date-picker-overlay.html, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAd5KydfYNCYJ8HfqfL:-KAd5KydfYNCYJ8HfqfM:-1083102900) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/vaadin-date-picker-overlay.html#L72)):*
Could you specify the format of the locale with an example : ES_es ES ES-es ? 

---

*[vaadin-locale-aware-behavior.html, line 7 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAd5rDZ7dFW6A1QfFKw:-KAd5rDZ7dFW6A1QfFKx:-1429357973) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/vaadin-locale-aware-behavior.html#L7)):*
This needs an annotation so as it can be parsed in hydrolysis :100: 


/**
   *
   * @polymerBehavior locale
   */

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-locale-aware-behavior.html, line 43 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAdOxAvE2oECnlTGHeR:-KAdOxAvE2oECnlTGHeS:-1865503096) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/vaadin-locale-aware-behavior.html#L43)):*
I'm thinking if we should fire an event instead of using this override pattern? `locale-changed` probably can't be used but maybe `locale-ready`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by tehapo** [comment]
Review status: 2 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/month-calendar.html, line 29 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAd5EyqtUqDG3kfoCXC:-KAfODxNeMvw74WR1AW0:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/test/month-calendar.html#L29)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAd5KydfYNCYJ8HfqfL:-KAfODDtywsfqFZmuX1F:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/vaadin-date-picker-overlay.html#L72)):*
Done.

---

*[vaadin-locale-aware-behavior.html, line 7 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAd5rDZ7dFW6A1QfFKw:-KAfOAOSS1-Pl20zqAls:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/vaadin-locale-aware-behavior.html#L7)):*
Done.

---

*[vaadin-locale-aware-behavior.html, line 43 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37#-KAdOxAvE2oECnlTGHeR:-KAfNwHuW73V4HkmW4Ky:1999027751) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a70a194c4bdf4df2c330a7986d097d13b9bfefa8/vaadin-locale-aware-behavior.html#L43)):*
Good idea, tried it and it seems a bit cleaner.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by samiheikki** [comment]
Reviewed 2 of 8 files at r3.
Review status: 3 of 9 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Comment by manolo** [comment]
Reviewed 1 of 8 files at r3.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/37)*

**Pull request merged**
