### PR TITLE
Add screen readers support

### LINKED ISSUE #70: Screenreader support
A visually impaired user should be able to select a specific date with the help of a screenreader, using the keyboard.

After #196, the user should still be able to navigate the calendar list and to choose a specific date using that instead of just typing in a valid date in the input field.

Should be validated at least on Windows and macOS.

#### Phase 1 DoD
- The team should be able to select a specific date with the help of a screenreader, using the keyboard, with the following:
 - macOS VoiceOver on Chrome, Firefox and Safari
 - JAWS (free trial) and NVDA on Windows
 - iOS VoiceOver
 - Android Talkback

#### Phase 2 DoD
- A visually impaired outside user should be able to select a specific date (perhaps ask on the previously mentioned Reddit thread for help)
 - We assume this is just a validation for the work, and doesn’t require much extra work from us

### PR DESCRIPTION
**Pull request by platosha**
Fixes #70

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/255)

### CODE REVIEW

**Comment by samiheikki** [comment]
When using NVDA screen reader (Chrome + Windows 10) and hovering over the vaadin-date-picker it reads the text that is behind the overlay. In Firefox it is reading the date numbers.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[vaadin-date-picker-behavior.html, line 131 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsIW9OCj-3_gIKpka5:-KTsIW9OCj-3_gIKpka6:btvzuu) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-date-picker-behavior.html#L131)):*
> ```HTML
>       calendar: 'Calendar',
> 
>       // Translation of the Clear icon button title
> ```

Can you end this sentence with a dot? As in the others

---

*[vaadin-date-picker-behavior.html, line 657 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsWFsHHU_M-GUPaiD2:-KTsWFsHHU_M-GUPaiD3:bxi4ahp) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-date-picker-behavior.html#L657)):*
> ```HTML
>         this.debounce('_announceFocusedDate', function() {
>           this.$.overlay.announceFocusedDate();
>         }, 1);
> ```

Have you considered increasing this number? For now when I'm fast scrolling it keeps saying a lot of dates and can't understand a word that is happening. Or should aria-busy in infinite-scroller handle that?

---

*[vaadin-date-picker-overlay.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsYDrdlWaEYBG5RvnV:-KTsYDrdlWaEYBG5RvnW:bhhrkyg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-date-picker-overlay.html#L241)):*
> ```HTML
>         display: inline-block;
>         position: fixed;
>         clip: rect(0px, 0px, 0px, 0px);
> ```

Can you use clip-path instead. Guess clip is deprecated https://developer.mozilla.org/en/docs/Web/CSS/clip

---

*[vaadin-month-calendar.html, line 233 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTseOun14oWS-kQ9Li4:-KTseOun14oWS-kQ9Li5:b6l8fmk) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-month-calendar.html#L233)):*
> ```HTML
>         weekDayNames = this._applyFirstDayOfWeek(weekDayNames, firstDayOfWeek);
>         weekDayNamesShort = this._applyFirstDayOfWeek(weekDayNamesShort, firstDayOfWeek);
>         return weekDayNames.map(function(day, index, days) {
> ```

Is the `days` parameter needed?

---

*[vaadin-month-calendar.html, line 342 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsf23bKRskQoFvfwgw:-KTsf23bKRskQoFvfwgx:b-v2tot8) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-month-calendar.html#L342)):*
> ```HTML
> 
>         if (this._isToday(date)) {
>           ariaLabel += ', ' + this.i18n.today;
> ```

I like this :)

---

*[test/common.js, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTshigKkm1rpiIKzVc6:-KTshigKkm1rpiIKzVc7:b-no6ss0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/test/common.js#L11)):*
> ```JavaScript
>       'June', 'July', 'August', 'September', 'October', 'November', 'December'
>     ],
>     weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
> ```

Should `clear` be here also?

---

*[test/wai-aria.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsm6hfjc0KmJ3NkF29:-KTsm6hgqGrmiH1M2-n4:b-v9i8p0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/test/wai-aria.html#L75)):*
> ```HTML
> 
>         beforeEach(function() {
>           datepickerLight = fixture('datepickerLight');
> ```

Should `datepicker` fixture be in this setup also?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-:-KTsXCJjg74xBYQwwWHK:b85fmbg)*

**Comment by platosha** [comment]
Review status: 4 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-date-picker-behavior.html, line 131 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsIW9OCj-3_gIKpka5:-KTy2wiNY72FPrQyqEeD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-date-picker-behavior.html#L131)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Can you end this sentence with a dot? As in the others
</details>
Done.

---

*[vaadin-date-picker-behavior.html, line 657 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsWFsHHU_M-GUPaiD2:-KTx1H8lXveUv2Ge1jNW:btzz3md) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-date-picker-behavior.html#L657)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Have you considered increasing this number? For now when I'm fast scrolling it keeps saying a lot of dates and can't understand a word that is happening. Or should aria-busy in infinite-scroller handle that?
</details>
This announce is an explicit additional announce for the focused date. It is called on open / focused date change. Should not be called at all while scrolling.

The speech you get on scrolling is, probably, due to the mouse cursor hovering on a lot of day cells. I don’t think there’s anything we can do about it. Probably not an issue, it is hard to use fast scrolling without fast visual feedback available anyways.

---

*[vaadin-date-picker-overlay.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsYDrdlWaEYBG5RvnV:-KTx6anjtODAAq0BkzBT:b-18yts5) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-date-picker-overlay.html#L241)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Can you use clip-path instead. Guess clip is deprecated https://developer.mozilla.org/en/docs/Web/CSS/clip
</details>
Added non-prefixed `clip-path` after `clip`, just for being future-proof here.

`clip` is still supported by all browsers, none of them fully support `clip-path` though. Replacing one with another, at this point, breaks it and make the node visible.

`clip` is deprecated and `clip-path` is introduced by the same spec, which is not in a `Recommendation` status yet.

---

*[vaadin-month-calendar.html, line 233 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTseOun14oWS-kQ9Li4:-KTy26DHczUYbNI1JTKS:bu2j3sr) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-month-calendar.html#L233)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Is the `days` parameter needed?
</details>
Nope. Removed.

---

*[vaadin-month-calendar.html, line 342 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsf23bKRskQoFvfwgw:-KTy28sKvZDSxoogXcTI:b-87j11d) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/vaadin-month-calendar.html#L342)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> I like this :)
</details>
Good!

---

*[test/common.js, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTshigKkm1rpiIKzVc6:-KTy2CYbjx758fPQTvxq:b-hakueb) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/test/common.js#L11)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Should `clear` be here also?
</details>
Done. Nice catch.

---

*[test/wai-aria.html, line 75 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KTsm6hfjc0KmJ3NkF29:-KTy2Fke4qq7AcGuJkq_:b7zb6je) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/10cddd68ceeee6f90d820bf3b9fefd0e5eacb42b/test/wai-aria.html#L75)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Should `datepicker` fixture be in this setup also?
</details>
Done.

Good question. It was inherited from parent testing scope before.

At the same time, the full `datepicker` fixture is not needed in all of the ARIA tests. I removed the global fixture in favour of local one for better performance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255)*

**Comment by manolo** [comment]
Reviewed 4 of 14 files at r1, 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255)*

**Comment by samiheikki** [comment]
Reviewed 10 of 11 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[vaadin-month-calendar.html, line 113 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU0znRcbRt0gH2y2OZp:-KU0znRcbRt0gH2y2OZq:bj74idi) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/vaadin-month-calendar.html#L113)):*
> ```HTML
>     </style>
> 
>     <div id="title" role="heading">[[_getTitle(month, i18n.monthNames)]]</div>
> ```

Should `role="heading"` divs in this file have `aria-level` attribute? https://www.w3.org/TR/wai-aria/states_and_properties#aria-level

---

*[docs/vaadin-date-picker-localization.adoc, line 95 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU10I2-67R8b0f2TfuP:-KU10I2-67R8b0f2TfuQ:b-ulj09y) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/docs/vaadin-date-picker-localization.adoc#L95)):*
> ```AsciiDoc
>   week: 'viikko',
>   calendar: 'kalenteri',
>   clear: 'tyhjennä',
> ```

`Tänään` and `Peruuta` are capitalized, but these 3 translations are not.

---

*[test/wai-aria.html, line 191 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU1AHiBEQRz-c8IIcaq:-KU1AHiBEQRz-c8IIcar:b-hzmn07) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/test/wai-aria.html#L191)):*
> ```HTML
>             // Indicate years as clickable.
> 
>             var years = Array.prototype.filter.call(yearScrollerContents, function(el, index) {
> ```

`index` is not used

---

*[test/wai-aria.html, line 204 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU1ANNzXQDWn_Zfxh08:-KU1ANNzXQDWn_Zfxh09:b-hzmn07) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/test/wai-aria.html#L204)):*
> ```HTML
>             // Do not speak dots between years.
> 
>             var dots = Array.prototype.filter.call(yearScrollerContents, function(el, index) {
> ```

`index` is not used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255)*

**Comment by platosha** [comment]
Review status: 12 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-month-calendar.html, line 113 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU0znRcbRt0gH2y2OZp:-KU1PZftIdkZPfHfdDei:bnfgn5m) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/vaadin-month-calendar.html#L113)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Should `role="heading"` divs in this file have `aria-level` attribute? https://www.w3.org/TR/wai-aria/states_and_properties#aria-level
</details>
In practice, without `aria-level` VoiceOver speaks “October 2016, heading” instead of “October 2016, heading level five”. Doesn’t feel like the heading level number adds any useful information here.

---

*[docs/vaadin-date-picker-localization.adoc, line 95 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU10I2-67R8b0f2TfuP:-KU1SmBIdbhMM4ZUcCYG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/docs/vaadin-date-picker-localization.adoc#L95)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> `Tänään` and `Peruuta` are capitalized, but these 3 translations are not.
</details>
Done.

---

*[test/wai-aria.html, line 191 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU1AHiBEQRz-c8IIcaq:-KU1SnRMLatInFklM3I1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/test/wai-aria.html#L191)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> `index` is not used
</details>
Done.

---

*[test/wai-aria.html, line 204 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-KU1ANNzXQDWn_Zfxh08:-KU1So3MnxSOFrS8aF59:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/47b5c44de4925fea14c495b17888c1d506133659/test/wai-aria.html#L204)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> `index` is not used
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255)*

**Comment by samiheikki** [comment]
Someone else should review this also, but :lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-:-KU1VdeMdspdHsBiusXR:bxrhcxl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 14 files at r1, 5 of 11 files at r2, 1 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-:-KU1nnoQrmHRngw6jVu6:bnfp4nl)*

**Comment by Saulis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/255#-:-KU1qi19pfiO16XQUQPv:bnfp4nl)*

**Pull request merged**
