### PR TITLE
Fix/clear icon placement

### LINKED ISSUE #98: Improve the clear X placement in the UI
Many test users confused the clearing functionality to closing the popup.

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #98

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/117)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-:-KCtxByIjLQtnvBE6Ulw:1417088721)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[vaadin-date-picker-overlay.html, line 185 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtugIESSdyW6SwMpUJ:-KCtugIESSdyW6SwMpUK:1213860926) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L185)):*
Hmm...both px and em in the same value...looks a bit like the previous 1em value is left there by accident. Other containers (toolbar, footer) use pixel values.
How would 0 14px work?

---

*[vaadin-date-picker-overlay.html, line 199 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtw59VW-PtcF9NkZuh:-KCtw59VW-PtcF9NkZui:-1726890843) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L199)):*
Should this also have a dedicated css property that would show in api (with --dark-theme-text-color as default)

---

*[vaadin-date-picker-overlay.html, line 210 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtvl_e2tfgNGr8JnMC:-KCtvl_e2tfgNGr8JnMD:-1542713233) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L210)):*
Pls use px

---

*[vaadin-date-picker-overlay.html, line 211 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtwmUrOKGPsmBIFisk:-KCtwmUsWmcr7uHHlFhv:-1964718547) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L211)):*
Fixed value, can't be modified.
Could we rather utilize the now hidden --paper-input-container-underline to show the focus undeline always.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker.html, line 136 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtyzkomUYuWA9g7kez:-KCtyzkpDwWNG54CXviV:2135449273) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker.html#L136)):*
What is this for?

---

*[vaadin-date-picker.html, line 140 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtzs1oryu3PBoqMyfX:-KCtzs1p52fylYEgDptu:567507053) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker.html#L140)):*
This makes the component jump a bit on open/close (with value) when set display: inline-block

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tehapo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 185 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtugIESSdyW6SwMpUJ:-KCtzaPBk2Ke4RkiRtdN:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L185)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 199 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtw59VW-PtcF9NkZuh:-KCu-1mL6ouxbRFIOCSF:-2103535206) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L199)):*
I think this should be as it is. Now it makes the icons and the input text the same color (and also the underline as fixed below).

---

*[vaadin-date-picker-overlay.html, line 210 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtvl_e2tfgNGr8JnMC:-KCu-QYBp2pn1MKIaBN4:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L210)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 211 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtwmUrOKGPsmBIFisk:-KCtzvdh6fLRtzmz5l_j:-569262264) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker-overlay.html#L211)):*
Good idea, done. Except for the color this should IMO use the same `--dark-theme-text-color` variable as the icon and the input text.

---

*[vaadin-date-picker.html, line 136 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtyzkomUYuWA9g7kez:-KCu0Uq_cf9LL9t_b6ux:2050475229) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker.html#L136)):*
It was there before (see https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L102) -> not related to this PR (even though it looks like it because of formatting changes).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tehapo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-date-picker.html, line 140 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCtzs1oryu3PBoqMyfX:-KCu2GF2jkBR_4aF2xXz:-1626451494) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f1f144fc122eac42a9ddbd76315d2af9e467bcdc/vaadin-date-picker.html#L140)):*
Oh, another good catch! :+1:  Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tomivirkki** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 205 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCu2LnbInk9lwayP2sz:-KCu2LnbInk9lwayP2t-:1896257451) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/bd48c57a12e1978bddb24561f41ce24dee659a2b/vaadin-date-picker-overlay.html#L205)):*
The icon isn't correctly aligned now. I'd remove the padding bottom here and the 8px margin-bottom from the input-contaier and instead add some common padding-bottom to header instead.

---

*[vaadin-date-picker-overlay.html, line 210 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCu2seHSKhtu5wK2M4-:-KCu2seHSKhtu5wK2M40:-1765110286) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/bd48c57a12e1978bddb24561f41ce24dee659a2b/vaadin-date-picker-overlay.html#L210)):*
I think the design has more space between

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tehapo** [comment]
Review status: 1 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 205 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCu2LnbInk9lwayP2sz:-KCu4GDlauQb0Mren174:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/bd48c57a12e1978bddb24561f41ce24dee659a2b/vaadin-date-picker-overlay.html#L205)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 210 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117#-KCu2seHSKhtu5wK2M4-:-KCu4Fugw6g28FC8hutm:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/bd48c57a12e1978bddb24561f41ce24dee659a2b/vaadin-date-picker-overlay.html#L210)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r4.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/117)*

**Pull request merged**
