### PR TITLE
Use a custom icon set instead of iron-icons

### LINKED ISSUE #279: Don't include iron-icons.html
This causes overhead, refer to https://github.com/vaadin/vaadin-combo-box/pull/268 also.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #279

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/280)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[bower.json, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280#-KVVSTifSdzx2KotWqiw:-KVVSTiiNhcMOxs2z1fq:b-7mf5gm) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/31d89921c34d9ab51da98afc8ade9777747d0bbb/bower.json#L47)):*
> ```JSON
>     "iron-flex-layout": "polymerelements/iron-flex-layout#^1.3.0",
>     "iron-meta": "polymerelements/iron-meta#^1.1.1",
>     "sugar": "^2.0.0"
> ```

There’s a demo in `demo/advanced.html` with `<iron-icon>` using an icon from the `iron-icons` set. Due to this fact, I suggest to have a dev dependency of `iron-icons`, and to add an explicit import of `iron-icons/iron-icons.html` in the demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280)*

**Comment by platosha** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280)*

**Comment by tomivirkki** [comment]
*[bower.json, line 47 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280#-KVVSTifSdzx2KotWqiw:-KVVli3Yg5NHWXHGeOcr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/31d89921c34d9ab51da98afc8ade9777747d0bbb/bower.json#L47)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> There’s a demo in `demo/advanced.html` with `<iron-icon>` using an icon from the `iron-icons` set. Due to this fact, I suggest to have a dev dependency of `iron-icons`, and to add an explicit import of `iron-icons/iron-icons.html` in the demo.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280#-:-KVYnny1HlxEDjx_9e84:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/280)*

**Pull request merged**
