### PR TITLE
Replacing legacy templatizer behavior with new P2 API

### PR DESCRIPTION
**Pull request by manolo**
Connects to #358 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/371)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-infinite-scroller.html, line 323 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuF5vHwNU6O_scoRcF:-KkuF5vHwNU6O_scoRcG:b56l33u) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L323)):*
> ```HTML
>         var tmpInstance = itemWrapper.instance;
> 
>         itemWrapper.instance = new this.TemplateClass({});
> ```

private `_templateClass` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-infinite-scroller.html, line 323 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuF5vHwNU6O_scoRcF:-KkuFwEDemyArT33x1Mj:b-pryhyq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L323)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

private `_templateClass` instead?
</blockquote></details>

Its a class name, I would use uppercase, or maybe name include the word constructor ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 140 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuNWv0Fz3R5tjHCQ3Z:-KkuNWv0Fz3R5tjHCQ3_:bgl56fz) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L140)):*
> ```HTML
>         this.TemplateClass = Polymer.Templatize.templatize(tpl, this, {
>           mutableData: false,
>           parentModel: true,
> ```

This is probably not used by any listener

---

*[vaadin-infinite-scroller.html, line 141 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuNUML3t7AUifcaOCo:-KkuNUML3t7AUifcaOCp:b-hughi0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L141)):*
> ```HTML
>           mutableData: false,
>           parentModel: true,
>           instanceProps: this._instanceProps,
> ```

This is undefined, can be omitted

---

*[vaadin-infinite-scroller.html, line 151 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuNayWRdxFaWqLbF0j:-KkuNayWRdxFaWqLbF0k:bjx3ef7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L151)):*
> ```HTML
>             }
>           },
>           notifyInstanceProp: function() {
> ```

Is this empty function required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 140 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuNWv0Fz3R5tjHCQ3Z:-KkuTVDRU46QCquqKzGU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L140)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is probably not used by any listener
</blockquote></details>

Done.

---

*[vaadin-infinite-scroller.html, line 141 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuNUML3t7AUifcaOCo:-KkuUbwJOh9npR-HO_2W:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L141)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is undefined, can be omitted
</blockquote></details>

Done.

---

*[vaadin-infinite-scroller.html, line 151 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuNayWRdxFaWqLbF0j:-KkuUe4hwQvJ2r2juXHu:b-7816zv) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L151)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this empty function required
</blockquote></details>

I left these properties for reference.
Removed now.

---

*[vaadin-infinite-scroller.html, line 323 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-KkuF5vHwNU6O_scoRcF:-KkuUkmMcKw-XtP7oE5I:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a336f4031d458476d39b3bceb4063d6a17f65d6b/vaadin-infinite-scroller.html#L323)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Its a class name, I would use uppercase, or maybe name include the word constructor ? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/371#-:-KkuVJqiA5xyOtOMkKMh:bnfp4nl)*

**Pull request merged**
