### PR TITLE
Add calendar icon

### LINKED ISSUE #48: Add calendar icon
Add calendar icon to the input field as a visual indicator of the possibility to open the calendar view.

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #48

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/53)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53#-KBCt_QWzKI7EF2V4_UZ:-KBCt_QXyegbIE1Q5hyl:-2055383813) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/250f578a94c27df92d1257af4c75d9466bd0cfe7/vaadin-date-picker.html#L66)):*
I would expect it to work like a toggle, and close the calendar if it was opened. Like the triangle in combo-box.

It would make it a bit more consistent together with clear icon. Right now, in the demo which has an initial date value:

1. **click the calendar icon:**
    shows the calendar, replaces calendar icon with clear icon

2. **click the clear icon** (in the same place where the calendar icon was):
    hides the calendar, brings calendar icon back

3. **click the calendar icon:**
    shows the calendar, calendar icon stays in its place

4. **click the calendar icon:**
    doesn't hide the calendar, unlike the clear icon.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53)*

**Comment by tehapo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 66 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53#-KBCt_QWzKI7EF2V4_UZ:-KBD5lcJsEDhT0zm8Lx9:-850953815) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/250f578a94c27df92d1257af4c75d9466bd0cfe7/vaadin-date-picker.html#L66)):*
Decided to go with a solution that keeps the calendar icon always visible (even when the clear icon is added) and it now also acts as a toggle button.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53)*

**Comment by tehapo** [comment]
The added test :lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53#-:-KBDCjP3jw0xcZFEVqnk:1427862810)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 55 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53#-KBDC-BQlPYcx6dUCL8k:-KBDC-BQlPYcx6dUCL8l:583993055) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/96a8265a3cd82ed292d39db4f680de5bfc2a93fe/vaadin-date-picker.html#L55)):*
The icons are too close to each other, and both have too small touch target area.

Currently the target size are 24px×24px. Material design guideline suggest at least 48px×48px. But that would feel too big to align with an input field.

As a compromise, in `vaadin-upload` I used 40px×40px target size for icons (by adding 8px padding from each side), and also assigned them `margin-left` and `margin-right` of -4px to have a bit nicer space ratios between icons and between icon and the field edge.

Apart from that, would be nice to have a ripple effect for icons.

I'm fine with resolving this in another ticket. The same problem exists in combo-box.

See: https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-touch-target-size

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/53)*

**Pull request merged**
