### PR TITLE
Fix/accidental taps

### LINKED ISSUE #149: Ignore tap on dates and year scroller while scrolling
The user might want to stop the momentum of month/year scrollers by tapping them.
In some cases a date might get accidentally selected in result of this.

Also ignore tap event if the time between touchstart to touchend takes longer than normal to avoid unintentional taps when dragging the scroller but the two events happen to occur at the same position.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #149 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/154)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/overlay.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-KEZruxv2DpDbqC4bOy9:-KEZruxv2DpDbqC4bOyA:-1687441858) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d383ea324e038c84b1f4c7eb94579be64625a5c1/test/overlay.html#L75)):*
Typo – "intial". :wink: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154)*

**Comment by Saulis** [comment]
Related with https://github.com/Polymer/polymer-gestures/issues/12

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-:-KE_5HePWPjScC_mJxxv:355674715)*

**Comment by Saulis** [comment]
Did you consider monkey patching https://github.com/Polymer/polymer/blob/master/src/standard/gestures.html#L630 ?

We could patch the functions `Polymer.Gestures.gestures.tap.save` and `Polymer.Gestures.gestures.tap.forward` to compared timestamps between `touchstart` and `touchend`

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-:-KE_6qH4tZuX_rmLAqhh:1313157202)*

**Comment by tomivirkki** [comment]
I prefer avoiding patches to core framework as much as possible. This PR has another similar fix that addresses scrolling so the fixes go hand-in-hand nicely here. Maybe once Polymer/polymer-gestures#12 gets fixed we could remove the other one.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-:-KE_7LMUU9szWTZDo3hc:200102827)*

**Comment by manolo** [comment]
correct the typo and :lgtm: 

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-:-KE_FIiQKzuC1ZySrqX1:-1229615815)*

**Comment by tomivirkki** [comment]
A single 3rd party component on a page making patches to core behaviour sounds hazardous. If our patch contained a bug because of something we didn't consider, in worst case it might break other components on the same page. I'd rather leave this for the Polymer guys to fix.

---

Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/overlay.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-KEZruxv2DpDbqC4bOy9:-KE_GH-jUi68u2xfcuCz:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d383ea324e038c84b1f4c7eb94579be64625a5c1/test/overlay.html#L75)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-:-KE_G5UDDKlR9ttXImED:1252077110)*

**Comment by jounik** [comment]
Tested the functionality on iPhone 6s, iOS 9.3 – feels legit 👍

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/154#-:-KEbvdTXQTypl4x4EhRR:1417088721)*

**Pull request merged**
