### PR TITLE
Fix navigation with two-digit years

### LINKED ISSUE #263: Keyboard navigation in 0-99 years
### Description
Keyboard navigation jumps from year 99 -> 2000 when using keyboard navigation

### Expected outcome
Selected date should move + 7 days.

### Actual outcome
Selected date moves ~2000 years (+ 7 days)

### Live Demo
https://plnkr.co/edit/BJ0XvpeF2UVrhsGKqjuM?p=preview

### Steps to reproduce
1. Open plunker example
2. Open date-picker
3. Press key down
4. Now the selected date is in January 2000 (Should be in January 100)

### Browsers Affected
Most likely all :)

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #263

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/267)

### CODE REVIEW

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/267#-:-KUW288vjYkKZVoOMSva:bnfp4nl)*

**Comment by samiheikki** [comment]
This seems to have three bugs remaining. 

1) When I navigate a date like `0099-12-31` and press enter date-picker's value is `1999-12-31`. 
2) When I navigate a date like `0099-12-31` and click it, the value is `1999-12-31`. 
3) When the date-picker has value `0099-12-31` and I open the date-picker and press esc two times, the value is `1991-12-31`.
I think these can be fixed in this PR also?

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/267#-:-KUW6yPYRYo2hQu-p6kh:b-ey1t0h)*

**Comment by tomivirkki** [comment]
Nice catch! Fixed

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/267#-:-KUWQhYf-LJUTWrvyifP:bhnhivs)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/267#-:-KU_tWMuKLMcqy2RcXrN:bnfp4nl)*

**Pull request merged**
