### PR TITLE
vaadin-date-picker MVP

### LINKED ISSUE #3: Create MVP
MVP Features
---
- [x] Month calendar view.
- [x] Allow navigation between months.
- [x] Allow picking a date from the month calendar (mouse/touch).
- [x] Allow clearing of the selected value.
- [x] Scroll to the selected date in month view when opening (current day by default).
- [x] Allow two-way Polymer data-binding (`value-changed` event).
- [x] Locale for the MVP is fixed to en-us.
- [ ] Asciidoc documentation

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #3

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/29)

### CODE REVIEW

**Comment by Saulis** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[bower.json, line 27 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA498IEguHAEp8lucKj:-KA498IEguHAEp8lucKk:619768140) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/bower.json#L27)):*
Did we reach some conclusion on the `iron-list` version?

---

*[bower.json, line 35 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4Hzos1ojttXv45J0N:-KA4Hzos1ojttXv45J0O:1815106754) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/bower.json#L35)):*
I'm thinking if `iron-component-page` should be added in the dependencies or not.. would allow viewing `index.html` without cloning the repo? Not sure what's the common practice on this.

---

*[test/basic.html, line 56 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4He9Kf5bsLaJl9RZL:-KA4He9Kf5bsLaJl9RZM:-295422322) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/test/basic.html#L56)):*
We could also add a similar test for tapping on label which also has on-tap listener.

---

*[vaadin-date-picker-overlay.html, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4Btdgy91k-fihVcFu:-KA4Btdgy91k-fihVcFv:-644900643) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker-overlay.html#L15)):*
We should import `paper-styles/typography.html` explicitly for this.

---

*[vaadin-date-picker-overlay.html, line 88 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4DBCRgD-Tg2PbqoG1:-KA4DBCRgD-Tg2PbqoG2:560165047) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker-overlay.html#L88)):*
Could this be converted into a function that is used as a `computed` property for the `_months` property?

---

*[vaadin-date-picker.html, line 26 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA49GhjHx3btRwzfZSF:-KA49GhjHx3btRwzfZSG:790961863) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L26)):*
I was thinking about using the svg for the clear icon instead of importing the whole iconset, but maybe that's unnecessary optimizing at this point.

---

*[vaadin-date-picker.html, line 63 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4A-bMlTde9p8IE3F-:-KA4A-bNpi5vRxNzuMtW:-913845409) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L63)):*
nitpick: `on-date-tap` would be better?

update: should we actually use `on-selected-date-changed` where to call `_close` ? Would save us from firing a custom event and I think it's OK to close the overlay if  someone calls `picker.value = ...` manually?

---

*[vaadin-date-picker.html, line 107 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4AnS03MynmW-Bmkh3:-KA4AnS03MynmW-Bmkh4:-2023275501) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L107)):*
Should we scroll to date on `value-changed` instead of overlay opened? Would also then scroll to correct place when someone sets `picker.value = ...` ?

I was also thinking if we should observe mutations on the `value`, like `picker.value.setMonth(1)` but I don't know if it's feasible..?

---

*[vaadin-month-calendar.html, line 13 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4Dq4qmbGd-uyYMqzd:-KA4Dq4qmbGd-uyYMqze:-1398937000) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-month-calendar.html#L13)):*
Import `paper-styles/typography.html`

---

*[vaadin-month-calendar.html, line 184 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4EMC27HF-_C6qLA9Q:-KA4EMC27HF-_C6qLA9R:-2007096032) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-month-calendar.html#L184)):*
would prefer `date-tap` or alternatively, using `on-selected-date-changed` in `vaadin-date-picker` and removing this custom event altogether.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-date-picker.html, line 3 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4OQrOn5Jp201FGkPM:-KA4OQrOn5Jp201FGkPN:-171259681) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L3)):*
2015 !??????!?!?!?!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[bower.json, line 27 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA498IEguHAEp8lucKj:-KA4ZnpQkf5BNGEUz8rk:1495215402) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/bower.json#L27)):*
Changed to ~1.0.0 for now

---

*[test/basic.html, line 56 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4He9Kf5bsLaJl9RZL:-KA4_A0SpMwcxDuc9pRN:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/test/basic.html#L56)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4Btdgy91k-fihVcFu:-KA4_Nqh6mh3wj5_2NUu:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker-overlay.html#L15)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 88 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4DBCRgD-Tg2PbqoG1:-KA4e0-hNGhF_ynG8Fgr:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker-overlay.html#L88)):*
Done.

---

*[vaadin-date-picker.html, line 3 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4OQrOn5Jp201FGkPM:-KA4e4ey6j0P3dlPYrjH:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L3)):*
Done.

---

*[vaadin-date-picker.html, line 63 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4A-bMlTde9p8IE3F-:-KA4eaxH1Hp8zAsaFd90:-1473813165) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L63)):*
Changed to date-tap. We used on-selected-date-changed previously but it's not fired in case a selected date is tapped again (because the value doesn't change)

---

*[vaadin-date-picker.html, line 107 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4AnS03MynmW-Bmkh3:-KA4fGv-EGLSr-E4QDuP:1086049553) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L107)):*
That's a valid question, sir. Another option would be to close the dropdown on every value change...or just ignore it. We'll discuss this with the team UX expert and get back to you.

---

*[vaadin-month-calendar.html, line 13 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4Dq4qmbGd-uyYMqzd:-KA4gJ7IglKrza2kg-cx:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-month-calendar.html#L13)):*
Done.

---

*[vaadin-month-calendar.html, line 184 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4EMC27HF-_C6qLA9Q:-KA4gMlsuDQHeHCpIjJV:1759407758) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-month-calendar.html#L184)):*
Changed to date-tap as mentioned above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29)*

**Comment by samiheikki** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-date-picker.html, line 100 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4dS0dIC0RhX1JrZVQ:-KA4dS0dIC0RhX1JrZVR:922635883) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L100)):*
Should `_open` be a public method? Eg. If the developer wants to format the date and show it in different input and hide date-picker input.

---

*[vaadin-date-picker.html, line 113 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4dk3yXuFz7HL9eXXL:-KA4dcM0k1-UR2W1fqCm:216191467) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L113)):*
Should `_close` be a public method? Eg. If the developer wants to format the date and show it in different input and hide date-picker input.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29)*

**Comment by tehapo** [comment]
Review status: 4 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-date-picker.html, line 100 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4dS0dIC0RhX1JrZVQ:-KA4hT0A6I0gge6qf_fG:1539729737) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L100)):*
Good point, but we'll consider this later. We kept this private intentionally for the MVP version.

---

*[vaadin-date-picker.html, line 113 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-KA4dk3yXuFz7HL9eXXL:-KA4hfEDLP0oMopFTTIH:1539729737) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fe0f6b97802863f240d8be686b57186ad2feb1a4/vaadin-date-picker.html#L113)):*
Good point, but we'll consider this later. We kept this private intentionally for the MVP version.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29)*

**Comment by Saulis** [comment]
:shipit: 

Now this is what I call a date picker!



---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/29#-:-KA91mW7k5XoYfOcWzrr:2056744581)*

**Pull request merged**
