### PR TITLE
Adapt demos to new vaadin site

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/components-team-tasks/issues/273

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/439)

### CODE REVIEW

**Comment by manolo** [comment]
Note that test failing (keyboard input » focus modes » should be tabbable) is also failing in master, so it should not block this.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439#-:-KuSvuJllPvuxSBGMv7b:bgnh7rp)*

**Comment by tomivirkki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[bower.json, line 31 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439#-KuT2oC7sZK6xkfx1b4A:-KuT2oC7sZK6xkfx1b4B:b4nyioe) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/652434c2f45668ad17e2ad882b6732a4d8951264/bower.json#L31)):*
> ```JSON
>     "vaadin-button": "^1.0.0",
>     "vaadin-text-field": "^1.0.0",
>     "vaadin-themable-mixin": "vaadin/vaadin-themable-mixin#^1.1.0"
> ```

Has someone registered this stuff to Bower? Polymer prefixes all of their dependencies https://github.com/PolymerElements/paper-tabs/blob/master/bower.json#L22 I don't see why we see it such a bad thing? No need to change this back now but I'm just wondering.

---

*[vaadin-date-picker-mixin.html, line 526 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439#-KuT3pl1p4C3-R8pKgV5:-KuT3pl1p4C3-R8pKgV6:b-xaocte) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/32946462d7436839340228b06a53b03ffc5463e3/vaadin-date-picker-mixin.html#L526)):*
> ```HTML
>       document.body.style.pointerEvents = 'none';
> 
>       // Click on date cells do not work on Chrome 63 otherwise
> ```

Looks like you've slipped in something more than just "Adapt demost to new vaadin site" :) I'm fine with this now but in the future include only the related stuff in PRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439)*

**Comment by manolo** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 31 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439#-KuT2oC7sZK6xkfx1b4A:-KuTbdtYSuQVf1fD_ZNZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/652434c2f45668ad17e2ad882b6732a4d8951264/bower.json#L31)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Has someone registered this stuff to Bower? Polymer prefixes all of their dependencies https://github.com/PolymerElements/paper-tabs/blob/master/bower.json#L22 I don't see why we see it such a bad thing? No need to change this back now but I'm just wondering.
</blockquote></details>

Done.

---

*[vaadin-date-picker-mixin.html, line 526 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439#-KuT3pl1p4C3-R8pKgV5:-KuTbdRNnD0lZsXiO6Fp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/32946462d7436839340228b06a53b03ffc5463e3/vaadin-date-picker-mixin.html#L526)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Looks like you've slipped in something more than just "Adapt demost to new vaadin site" :) I'm fine with this now but in the future include only the related stuff in PRs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 13 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/439#-:-KuToXc8c6UlBqAQ9fAO:bnfp4nl)*

**Pull request merged**
