### PR TITLE
Adding i18n to today button

### PR DESCRIPTION
**Pull request by manolo**
Connected to #41

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/45)

### CODE REVIEW

**Comment by manolo** [comment]
Note that this PR is almost for discussion

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45#-:-KApBzRsHNbKStdMLFPh:-840472569)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-date-picker-overlay.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45#-KAselASUHqbmdRQqmkX:-KAselASUHqbmdRQqmkY:1198745549) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/61f5e1489df4053de0be7ca78a7e914cf2b38a80/vaadin-date-picker-overlay.html#L45)):*
Could this also be something like `i18n.today` ? Using underscores separate it nicely from "normal" properties, but don't really tell explicitly what the underscores stand for.

---

*[vaadin-date-picker-overlay.html, line 89 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45#-KAsdLW7Jn26FLDQa1Ke:-KAsdLW8niBLN6cUR_AK:-326587130) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/61f5e1489df4053de0be7ca78a7e914cf2b38a80/vaadin-date-picker-overlay.html#L89)):*
Should we have `i18n` somewhere in the namespace? `vaadin.elements.datepicker.i18n.today` or even `vaadin.elements.i18n.today`for using the same string globally?

---

*[vaadin-locale-aware-behavior.html, line 29 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45#-KAsdhaV8YHueepyNDes:-KAsdhaW7w_XquaApGpo:1391567117) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/61f5e1489df4053de0be7ca78a7e914cf2b38a80/vaadin-locale-aware-behavior.html#L29)):*
Would've appreciated an example string of what `moment().calendar(Date.now())` returns in the comments, had to look it up using console :smile:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45)*

**Comment by tomivirkki** [comment]
If we're going down this road the functionality should be built separately from vaadin-date-picker and incorporated to vaadin-upload as well (it too has fixed english texts). Sounds like something outside the scope of 1.0 for the two components?
For now I would just leave the text be or use the same approach as in vaadin-upload:
`<vaadin-date-picker><div class="todaybutton">Hoy</div><vaadin-date-picker>`
or
`<vaadin-date-picker today-text="hoy" />`

There's currently no designs for locale auto-detection for vaadin-date-picker 1.0 either

**Comment by samiheikki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo/index.html, line 23 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45#-KAtmW1vfd5P1RiqmnXd:-KAtmW1vfd5P1RiqmnXe:-1217565597) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/61f5e1489df4053de0be7ca78a7e914cf2b38a80/demo/index.html#L23)):*
I think that this demo page requires another `vaadin-date-picker` example.  The first example has to be localized to English (no localization).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45)*

**Comment by manolo** [comment]
Once dis

---

Review status: 1 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/45#-:-KBH3c1HBjHGf1SJHR6o:-93672812)*

**Comment by manolo** [comment]
Closing this PR in favor of #65

**Pull request closed without merging**
