### PR TITLE
Convert to ES6

### PR DESCRIPTION
**Pull request by manolo**
Connects to #358

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/370)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 23 files reviewed at latest revision, 15 unresolved discussions.

---

*[README.md, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkowwFScn_cYRE3y07b:-KkowwFTr62GqY2AO89a:b-ml3kbc) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/README.md#L43)):*
> ```Markdown
> 1. Install [polymer-cli](https://www.npmjs.com/package/polymer-cli): `npm install -g polymer-cli`
> 
> 1. When in the `vaadin-button` directory, run `polymer serve --open`, browser will automatically open the component API documentation.
> ```

date-picker

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkowz--pfYD618Z5hsq:-Kkowz--pfYD618Z5hsr:b-ml3kbc) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/README.md#L53)):*
> ```Markdown
> ## Running tests from the command line
> 
>   1. When in the `vaadin-button` directory, run `polymer test`
> ```

date-picker

---

*[vaadin-date-picker-light.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoysTL1wquphm5w3D4:-KkoysTL1wquphm5w3D5:b9rkjtl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-light.html#L7)):*
> ```HTML
> -->
> 
> <link rel="import" href="../polymer/polymer.html">
> ```

Import `polymer-element.html` instead. Import , `dom-if`, `dom-repeat`, Gesture and `RenderStatus` etc. modules explicitly where needed. 
See https://www.polymer-project.org/2.0/docs/upgrade#optional-features

---

*[vaadin-date-picker-light.html, line 88 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkox5POOnnhbi7e7bdu:-Kkox5POOnnhbi7e7bdv:bdgjgy2) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-light.html#L88)):*
> ```HTML
>        * ```
>        *
>        * @element vaadin-date-picker-light
> ```

Instead of `@element vaadin-date-picker-element`
`@memberof Vaadin`
`@mixes Vaadin.DatePickerMixin`

---

*[vaadin-date-picker-mixin.html, line 728 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkozO-Ct6K6kJD-WfOZ:-KkozO-Ct6K6kJD-WfO_:b-k1z61i) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-mixin.html#L728)):*
> ```HTML
> 
>     /**
>      * Fired when the value changes.
> ```

This should be removed and `notify: true` put to `value` instead.

---

*[vaadin-date-picker-overlay.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkozc7g29n0IHl7muPM:-Kkozc7hG-HY1KOGkvmo:b9rkjtl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L7)):*
> ```HTML
> -->
> 
> <link rel="import" href="../polymer/polymer.html">
> ```

Import `polymer-element.html` instead. Import , `dom-if`, `dom-repeat`, Gesture and `RenderStatus` etc. modules explicitly where needed. 
See https://www.polymer-project.org/2.0/docs/upgrade#optional-features

---

*[vaadin-date-picker-overlay.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyYqRadWrNfkw2d5K:-KkoyYqRadWrNfkw2d5L:b-7p1xvl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L462)):*
> ```HTML
>             announce.push(Vaadin.DatePickerHelper._getISOWeekNumber(focusedDate));
>           }
>           var e = new Event('iron-announce', {bubbles: true, composed: true});
> ```

nitpick: `CustomEvent` instead of `Event`

---

*[vaadin-date-picker-overlay.html, line 630 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyU1-X5xPxEZvRrEz:-KkoyU1-X5xPxEZvRrF-:b-7p1xvl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L630)):*
> ```HTML
>               window.requestAnimationFrame(smoothScroll);
>             } else {
>               var e = new Event('scroll-animation-finished', {bubbles: true, composed: true});
> ```

nitpick: `CustomEvent` instead of `Event`

---

*[vaadin-date-picker.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkozirzEGzvBRlcBeiS:-KkozirzEGzvBRlcBeiT:b9rkjtl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker.html#L7)):*
> ```HTML
> -->
> 
> <link rel="import" href="../polymer/polymer.html">
> ```

Import `polymer-element.html` instead. Import , `dom-if`, `dom-repeat`, Gesture and `RenderStatus` etc. modules explicitly where needed. 
See https://www.polymer-project.org/2.0/docs/upgrade#optional-features

---

*[vaadin-date-picker.html, line 266 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoznROhuvRF50PlP0C:-KkoznRP-G842ns54iIo:boiir8o) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker.html#L266)):*
> ```HTML
>        * [`<vaadin-date-picker-light>`](#vaadin-date-picker-light) element.
>        *
>        * @element vaadin-date-picker
> ```

Instead of `@element` annotation, use `@memberof Vaadin` and` @mixes Vaadin.DatePickerMixin` (see commit 5522af3)

---

*[test/keyboard-input.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp15RDQ27v-4avdB6K:-Kkp15RDQ27v-4avdB6L:be2lu8l) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-input.html#L94)):*
> ```HTML
>           if (datepicker._ios) {
>             // wait for refit in iOS
>             setTimeout(done, 501);
> ```

mmm what's this 501ms? could we rather flush any debouncer or timers or run the refit manually?

---

*[test/keyboard-input.html, line 499 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp22BIY_KNntmu99Ma:-Kkp22BIY_KNntmu99Mb:b-s7neyx) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-input.html#L499)):*
> ```HTML
>           });
> 
>           // FIXME: flaky tests
> ```

If this test still and it's not easy to fix, let's remove it.

---

*[test/keyboard-navigation.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1ZDAnlu5qDGKI2x9:-Kkp1ZDAnlu5qDGKI2xA:b-o5mkq6) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-navigation.html#L96)):*
> ```HTML
>             if (datepicker._ios) {
>               // wait for refit in iOS
>               setTimeout(done, 501);
> ```

Same question here about the magic 501ms as in another test file.

---

*[test/month-calendar.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1gGDRclJ3pWHmRiY:-Kkp1gGDRclJ3pWHmRiZ:bcsaerw) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/month-calendar.html#L36)):*
> ```HTML
>         // Need to wait for the templates to be rendered.
>         setTimeout(done);
>         // setTimeout(done);
> ```

This line can be removed.

---

*[test/scroller.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1w2Z3NeM54apMoIK:-Kkp1w2Z3NeM54apMoIL:b-2s2ve6) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/scroller.html#L71)):*
> ```HTML
>       });
> 
>       // FIXME: fails in FF travis
> ```

If this test still fails and cannot be fixed, let's remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by tomivirkki** [comment]
Remember to re-enable IE-tests and the individual tests that were commented out in the hybrid phase (if possible)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-:-KkpEcqAIj1NQSNFIO-x:b-gygzlg)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker-mixin.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkpFyPvTG3UehlBpgr2:-KkpFyPvTG3UehlBpgr3:b-ruzpt7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-mixin.html#L20)):*
> ```HTML
>    */
>   Vaadin.DatePickerMixin = subclass => class VaadinDatePickerMixin extends Polymer.mixinBehaviors(
>   [Polymer.IronFormElementBehavior, Polymer.IronValidatableBehavior, Polymer.IronA11yKeysBehavior, Polymer.IronResizableBehavior], subclass
> ```

Should we drop IronFormElementBehavior and IronValidatableBehavior at this point? `<vaadin-text-field>` doesn't extend those either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by manolo** [comment]
I would do in the last PR to avoid spending time in the meanwhile. There are many tests and things removed in successive commits that it's worth not fix in IE11 until the end. 

---

Review status: 0 of 23 files reviewed at latest revision, 16 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkpFyPvTG3UehlBpgr2:-KkpNqB9LouKqA5r02f2:bncwcvn) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-mixin.html#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we drop IronFormElementBehavior and IronValidatableBehavior at this point? `<vaadin-text-field>` doesn't extend those either.
</blockquote></details>

It will be done in the PR replacing paper and iron stuff.

---

*[test/keyboard-input.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp15RDQ27v-4avdB6K:-KkpO2X7LPWAMET_NF7o:b-7n75mv) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-input.html#L94)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

mmm what's this 501ms? could we rather flush any debouncer or timers or run the refit manually?
</blockquote></details>

Well the original code is a `setTimeout(this.$.dropdown.refit, 500)` I did wrap it in an `if` because there were random failures in other browser when the test finishes and the refit tries to utilise elements removed from the dom.

I'd rather leave these test passing and tune at the end, so as it speeds up the task.

---

*[test/keyboard-input.html, line 499 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp22BIY_KNntmu99Ma:-KkpOfIIhnk96N6iDHUr:bu2legp) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-input.html#L499)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

If this test still and it's not easy to fix, let's remove it.
</blockquote></details>

I prefer to leave these tests here, and remove in the last PR when spending time in tuning tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-:-KkpN2NbL1OjPCJ8XrnF:bw3ri8)*

**Comment by tomivirkki** [comment]
- If you open the datepicker by clicking the calendar icon, arrow keys scroll the document afterwards
- While the dropdown is open, tab should shift focus from input -> overlay -> today-button -> cancel -> input. This doesn’t work currently. Same issue with shift-tab
- Feels like the fullscreen mode on touch devices doesn’t get tap events:
  - Can’t open year scroller in narrow viewport
  - Can’t select date
  - Can’t tap year scroller

---

Review status: 0 of 23 files reviewed at latest revision, 16 unresolved discussions.

---

*[vaadin-date-picker-mixin.html, line 598 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkpb_qu5F-Amvn2ZWhl:-Kkpb_qu5F-Amvn2ZWhm:bzgsj06) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-mixin.html#L598)):*
> ```HTML
>         this.$.overlay.focus();
>       } else {
>         this.inputElement.focus();
> ```

Should we make this private?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-:-KkpgS7NoYkqNUysOjks:b-cfanv7)*

**Comment by manolo** [comment]
@tomivirkki  Fixed Focus and Tap

---

Review status: 0 of 24 files reviewed at latest revision, 17 unresolved discussions.

---

*[README.md, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkowwFScn_cYRE3y07b:-KktWzGSJDkrVa8E_6vK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/README.md#L43)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

date-picker
</blockquote></details>

Done.

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkowz--pfYD618Z5hsq:-KktWzj83hwgxcu4fHaP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/README.md#L53)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

date-picker
</blockquote></details>

Done.

---

*[vaadin-date-picker-light.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoysTL1wquphm5w3D4:-KktYtyUZnc1zKd4XLo_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-light.html#L7)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Import `polymer-element.html` instead. Import , `dom-if`, `dom-repeat`, Gesture and `RenderStatus` etc. modules explicitly where needed. 
See https://www.polymer-project.org/2.0/docs/upgrade#optional-features
</blockquote></details>

Done.

---

*[vaadin-date-picker-light.html, line 88 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkox5POOnnhbi7e7bdu:-KktYv6PPGdq8LTiOOo1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-light.html#L88)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Instead of `@element vaadin-date-picker-element`
`@memberof Vaadin`
`@mixes Vaadin.DatePickerMixin`
</blockquote></details>

Done.

---

*[vaadin-date-picker-mixin.html, line 598 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkpb_qu5F-Amvn2ZWhl:-Kktb19JBWohrBZhPojx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-mixin.html#L598)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we make this private?
</blockquote></details>

Done.

---

*[vaadin-date-picker-mixin.html, line 728 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkozO-Ct6K6kJD-WfOZ:-KkteSnBNP-VKvo8R3X-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-mixin.html#L728)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This should be removed and `notify: true` put to `value` instead.
</blockquote></details>

Done.

---

*[vaadin-date-picker-overlay.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkozc7g29n0IHl7muPM:-KkteUmZUPWcUzRKkmLe:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L7)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Import `polymer-element.html` instead. Import , `dom-if`, `dom-repeat`, Gesture and `RenderStatus` etc. modules explicitly where needed. 
See https://www.polymer-project.org/2.0/docs/upgrade#optional-features
</blockquote></details>

Done.

---

*[vaadin-date-picker-overlay.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyYqRadWrNfkw2d5K:-KkteeJOuxp8IJpyqEsL:b-2e0xq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L462)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

nitpick: `CustomEvent` instead of `Event`
</blockquote></details>

CustomEvent has a `detail` read-only property

---

*[vaadin-date-picker-overlay.html, line 630 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyU1-X5xPxEZvRrEz:-KkteejXnIhTDj2B6rqP:b-2e0xq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L630)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

nitpick: `CustomEvent` instead of `Event`
</blockquote></details>

CustomEvent has a `detail` read-only property

---

*[vaadin-date-picker.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkozirzEGzvBRlcBeiS:-KktegPLPwjFZmTn8oR6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker.html#L7)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Import `polymer-element.html` instead. Import , `dom-if`, `dom-repeat`, Gesture and `RenderStatus` etc. modules explicitly where needed. 
See https://www.polymer-project.org/2.0/docs/upgrade#optional-features
</blockquote></details>

Done.

---

*[vaadin-date-picker.html, line 266 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoznROhuvRF50PlP0C:-KktgbFICeIri3n0UDzl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker.html#L266)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Instead of `@element` annotation, use `@memberof Vaadin` and` @mixes Vaadin.DatePickerMixin` (see commit 5522af3)
</blockquote></details>

Done.

---

*[test/keyboard-navigation.html, line 96 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1ZDAnlu5qDGKI2x9:-KktiKjgOcHCVmzkwbn3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-navigation.html#L96)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Same question here about the magic 501ms as in another test file.
</blockquote></details>

Done.

---

*[test/month-calendar.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1gGDRclJ3pWHmRiY:-KktfaTRcZYOvYi5M-9Z:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/month-calendar.html#L36)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This line can be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-:-KktWA0gh8ynGtvqo4gx:b-5j2u5c)*

**Comment by manolo** [comment]
Review status: 0 of 24 files reviewed at latest revision, 16 unresolved discussions.

---

*[test/scroller.html, line 71 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1w2Z3NeM54apMoIK:-KktnchZykAMvk0csJX1:bqzia1s) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/scroller.html#L71)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

If this test still fails and cannot be fixed, let's remove it.
</blockquote></details>

Test pass in 2.0, so re-enabling it.
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by manolo** [comment]
Review status: 0 of 24 files reviewed at latest revision, 16 unresolved discussions.

---

*[test/keyboard-input.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp15RDQ27v-4avdB6K:-Kkts9fnBjX0UrOp7lZs:b8pu03z) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/keyboard-input.html#L94)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Well the original code is a `setTimeout(this.$.dropdown.refit, 500)` I did wrap it in an `if` because there were random failures in other browser when the test finishes and the refit tries to utilise elements removed from the dom.

I'd rather leave these test passing and tune at the end, so as it speeds up the task.
</blockquote></details>

Fixed and reenabled the test
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 11 of 24 files at r1, 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-:-Kku1GqBIjRJHW2Gweyz:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-date-picker-light.html, line 88 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkox5POOnnhbi7e7bdu:-Kku1nLYlAYMrw1yDEB2:b-hcyk7r) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-light.html#L88)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like done 🤔

---

*[vaadin-date-picker-overlay.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyYqRadWrNfkw2d5K:-Kku18ZMX1EmC9s2mafc:b-vawd7w) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L462)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

CustomEvent has a `detail` read-only property
</blockquote></details>

Yes, `detail` is given as a constructor parameter

---

*[test/month-calendar.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1gGDRclJ3pWHmRiY:-Kku1S0tTsGR0UcLfLZT:b-t9169r) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/month-calendar.html#L36)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look like removed 🤔

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by manolo** [comment]
Review status: 21 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-date-picker-light.html, line 88 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkox5POOnnhbi7e7bdu:-Kku3R8qu9rSG2-DXjKe:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-light.html#L88)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Doesn't look like done 🤔
</blockquote></details>

Done.

---

*[vaadin-date-picker-overlay.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyYqRadWrNfkw2d5K:-Kku4bFmgVCUITQ6dnVC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L462)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Yes, `detail` is given as a constructor parameter
</blockquote></details>

Done.

---

*[test/month-calendar.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-Kkp1gGDRclJ3pWHmRiY:-Kku3QHENsdP-pQWxdUd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/test/month-calendar.html#L36)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Doesn't look like removed 🤔
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by manolo** [comment]
Review status: 21 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 630 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-KkoyU1-X5xPxEZvRrEz:-Kku6CYIZlVWJhNq4A6B:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/b4eb9de402aba648aaaebd280966440506bbcbaf/vaadin-date-picker-overlay.html#L630)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

CustomEvent has a `detail` read-only property
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370)*

**Comment by Saulis** [comment]
:lgtm: after build passes

---

Reviewed 10 of 24 files at r1, 12 of 14 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/370#-:-Kku8W0muBcnal51PaRj:b-9pmja4)*

**Pull request merged**
