### PR TITLE
Add pointer-events workaround for Chrome 62+

### LINKED ISSUE #450: date is not selected in Chrome Version 62.0.3202.62 (Official Build) (64-bit)
### Description
When using Chrome Version 62.0.3202.62 (Official Build) (64-bit), the calendar opens but after a date is selected and the calendar closes, the date is not updated in the input box.

### Expected outcome
The date should be updated.

### Actual outcome
The input box remains blank (or unchanged if a value is set).

### Live Demo
https://www.webcomponents.org/element/vaadin/vaadin-date-picker

### Steps to reproduce
Go here https://www.webcomponents.org/element/vaadin/vaadin-date-picker
Use the noted version of Chrome and click on the calendar icon of the "Pick a date" labeled vaadin-date-picker component.
Select a date
The calendar closed and the date is not updated.

### Browsers Affected

- [ X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### PR DESCRIPTION
**Pull request by limonte**
Fixes #450 

The same as #432

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/451)

### CODE REVIEW

**Comment by manolo** [comment]
why not reopening #432 instead of creating a new one ? 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/451#-:-KwnLltIolRXG_osIG_L:b-ecj07z)*

**Comment by limonte** [comment]
> manolo  wants to merge 1 commit into `1.x`

> limonte  wants to merge 1 commit into `master`

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/451#-:-KwnMED7Tk6XRjleyeaE:b-siv9ks)*

**Comment by manolo** [comment]
Anyways 432 seems not be possible to reopen, and it's to fix stable branch not master. Let's merge this right now.

:lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/451#-:-KwnMMwvZTkFQwmwrSNe:b-au7wfh)*

**Comment by manolo** [comment]
Actually there were  #431 for master.

**Pull request merged**
