### PR TITLE
Fix 2 flaky tests, disable 1 flaky test for iOS

### LINKED ISSUE #330: F-test: test/basic.html » Basic features » window scroll realign » should not realign on year/month scroll
https://travis-ci.org/vaadin/vaadin-date-picker/builds/194612240

### LINKED ISSUE #331: F-test: test/keyboard-input.html » keyboard input » focus modes » should not focus overlay on key-input
https://travis-ci.org/vaadin/vaadin-date-picker/builds/194399728

### PR DESCRIPTION
**Pull request by limonte**
Fixes #330 
Fixes #331 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/333)

### CODE REVIEW

**Comment by platosha** [comment]
Still fails. Let us just disable that test on iOS.

**Comment by tomivirkki** [comment]
*[test/overlay.html, line 116 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbJVM-vlQZLmgJHtXct:-KbJVM-vlQZLmgJHtXcu:bv74fe2) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0d8803826597b7b0c1f49bc412a52d809142d784/test/overlay.html#L116)):*
> ```HTML
>         });
> 
>         /* it('should react to year tap after 300ms elapsed after scroll', function(done) {
> ```

Why is this test commented out? Is it failing every time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by tomivirkki** [comment]
*[test/basic.html, line 294 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbJXKIGE-y6QzAd4lak:-KbJXKIH000h2vxawV8l:b-yzb4yj) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0d8803826597b7b0c1f49bc412a52d809142d784/test/basic.html#L294)):*
> ```HTML
>         });
> 
>         if (!ios) { // https://github.com/vaadin/vaadin-date-picker/issues/330
> ```

Can disabling be considered a proper fix for test flakiness?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/basic.html, line 294 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbJXKIGE-y6QzAd4lak:-KbJZ2cP6dJDixEII10s:bww0399) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0d8803826597b7b0c1f49bc412a52d809142d784/test/basic.html#L294)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Can disabling be considered a proper fix for test flakiness?
</blockquote></details>

In this case yes. This test is failing because of a buggy behavior of iOS, not date-picker.

---

*[test/overlay.html, line 116 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbJVM-vlQZLmgJHtXct:-KbJaF46mx0NxPDrl9dm:bsoeozc) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/0d8803826597b7b0c1f49bc412a52d809142d784/test/overlay.html#L116)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this test commented out? Is it failing every time?
</blockquote></details>

Not every time, reverted in this PR, will take a look on this later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by tomivirkki** [comment]
*[test/keyboard-navigation.html, line 290 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbKEvGwdjgCxZHyZ9oD:-KbKEvGwdjgCxZHyZ9oE:b-bpfora) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d41675327c63085512ab52d880996f6bc723192a/test/keyboard-navigation.html#L290)):*
> ```HTML
>           });
> 
>           /* it('should scroll up when focus goes invisible', function(done) {
> ```

2 more tests commented out in the latest revision???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/keyboard-navigation.html, line 290 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbKEvGwdjgCxZHyZ9oD:-KbKIX6m2r688XknAo6u:b-vynfrl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d41675327c63085512ab52d880996f6bc723192a/test/keyboard-navigation.html#L290)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

2 more tests commented out in the latest revision???
</blockquote></details>

Yes. I can't get build working so I commented buggy tests and separated them to tickets as discussed on retro. I have no idea how to fix them, someone else should take a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by tomivirkki** [comment]
*[test/keyboard-navigation.html, line 290 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbKEvGwdjgCxZHyZ9oD:-KbKLH21kxdlRZy01oEg:b-d3u31y) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d41675327c63085512ab52d880996f6bc723192a/test/keyboard-navigation.html#L290)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Yes. I can't get build working so I commented buggy tests and separated them to tickets as discussed on retro. I have no idea how to fix them, someone else should take a look.
</blockquote></details>

The master build is currently green, meaning that the build works (even if some tests are flaky).

If we comment out tests & create issues in the inbox to fix them later, they could be forgotten there for a long time, during which the code they're meant to be testing doesn't get tested at all. Sounds dangerous to me. It's better to have flaky tests for whatever they're testing than not testing at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by limonte** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/keyboard-navigation.html, line 290 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbKEvGwdjgCxZHyZ9oD:-KbKMsqcmRFgC_dJ_F7j:b3o1ogk) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d41675327c63085512ab52d880996f6bc723192a/test/keyboard-navigation.html#L290)):*
> The master build is currently green, meaning that the build works (even if some tests are flaky).

Lucky master :)

> It's better to have flaky tests for whatever they're testing than not testing at all.

This means that we will probably have a loooooooooong build - up to 40-50 min :/ We're using `travis_retry`and Travis will retry shady and shadow jobs in case of failing tests.

> If we comment out tests & create issues in the inbox to fix them later, they could be forgotten there for a long time

I'd really like to fix them and I tried but without success. As a developer, I want to be sure that build is green and if CI build is failing that's because of new feature. It's really annoying to keep in mind all those flaky tests aside development new features.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by limonte** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/keyboard-navigation.html, line 290 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-KbKEvGwdjgCxZHyZ9oD:-KbirdN_vvjZ57sABe_D:b-nggyk0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d41675327c63085512ab52d880996f6bc723192a/test/keyboard-navigation.html#L290)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> The master build is currently green, meaning that the build works (even if some tests are flaky).

Lucky master :)

> It's better to have flaky tests for whatever they're testing than not testing at all.

This means that we will probably have a loooooooooong build - up to 40-50 min :/ We're using `travis_retry`and Travis will retry shady and shadow jobs in case of failing tests.

> If we comment out tests & create issues in the inbox to fix them later, they could be forgotten there for a long time

I'd really like to fix them and I tried but without success. As a developer, I want to be sure that build is green and if CI build is failing that's because of new feature. It's really annoying to keep in mind all those flaky tests aside development new features.
</blockquote></details>

I reverted commented tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 6 files at r1, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/333#-:-KbixDTmcXRADdleLZzM:bnfp4nl)*

**Pull request merged**
