### PR TITLE
Fix bug in chrome 63 preventing click on cells

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/431)

### CODE REVIEW

**Comment by limonte** [comment]
I don't know why we adding hacks for canary version. We not supporting beta or canary version. Only **latest stable**. Let's wait for 63 stable and revisit this issue.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/431#-:-KtonovtNSxFeHoYTM_S:bkztwbj)*

**Comment by manolo** [comment]
This is already needed and merge in the branch for the new.vaadin.com, so it should be merged here.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/431#-:-Ktph1HlvspZphH-Nw7-:b-grdifs)*

**Comment by limonte** [comment]
Why something **should** be merged into master without CR? Because that code is present is some preview branch? :)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/431#-:-KtplbsnBbfQKGyQQ-F0:b-muf85c)*

**Comment by manolo** [comment]
Team does not want to fix issues for non stable browser releases

**Pull request closed without merging**
