### PR TITLE
Replace iron-list with vaadin-infinite-scroller

### LINKED ISSUE #33: Replace iron-list with vaadin-scroller
Replace `iron-list` with a custom `vaadin-scroller` component.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #33

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/38)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/scroller.html, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAn6XiDaBK4JppmwK5r:-KAn6XiDaBK4JppmwK5s:1700665795) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/366fcf34fb2c1d4d3fe53c2ef2a5410563e635f4/test/scroller.html#L32)):*
This method is the same that getFirstVisibleCalendar in the overlay.html. 
Probably it can be moved to the scroller.html, and rename it to getFirstVisibleItem and  use  it in both places.

---

*[vaadin-infinite-scroller.html, line 206 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAn9A5TPyVxBk4w7NbQ:-KAn9A5TPyVxBk4w7NbR:1698490201) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/366fcf34fb2c1d4d3fe53c2ef2a5410563e635f4/vaadin-infinite-scroller.html#L206)):*
This function is not  used in this element.
Is it an internal API of polymer?, if so it should be documented here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker-overlay.html, line 55 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAn9yiDKkv0a4xM18u8:-KAn9yiDKkv0a4xM18u9:516285147) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/366fcf34fb2c1d4d3fe53c2ef2a5410563e635f4/vaadin-date-picker-overlay.html#L55)):*
Pls set always the type, otherwise hydrolysis might not figure it out .

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by samiheikki** [comment]
Reviewed 7 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 3 files at r5.
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 78 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAnloUlx5zYXHw7WT1g:-KAnloUlx5zYXHw7WT1h:-574099149) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/09729867e4fb722a197bbb443efb90b0ecb6ef1e/vaadin-infinite-scroller.html#L78)):*
Why `500000`? What does it mean?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by tomivirkki** [comment]
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/scroller.html, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAn6XiDaBK4JppmwK5r:-KAnMRCRjNl_afEQa88T:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/366fcf34fb2c1d4d3fe53c2ef2a5410563e635f4/test/scroller.html#L32)):*
Done.

---

*[vaadin-date-picker-overlay.html, line 55 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAn9yiDKkv0a4xM18u8:-KAnEyxJVdCe1nxbM-7L:493460090) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/366fcf34fb2c1d4d3fe53c2ef2a5410563e635f4/vaadin-date-picker-overlay.html#L55)):*
These properties were accidentally left here during the process, removed them both.

---

*[vaadin-infinite-scroller.html, line 206 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAn9A5TPyVxBk4w7NbQ:-KAnFHqgvx3Jx9Hr2mrd:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/366fcf34fb2c1d4d3fe53c2ef2a5410563e635f4/vaadin-infinite-scroller.html#L206)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by tomivirkki** [comment]
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-infinite-scroller.html, line 78 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAnloUlx5zYXHw7WT1g:-KAnnO8BtMl-2MFadwnF:135448401) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/09729867e4fb722a197bbb443efb90b0ecb6ef1e/vaadin-infinite-scroller.html#L78)):*
Means that in order to be able to scroll backwards (from index 0 ->-1....) we need to be at a scroll position above 0 at first.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by manolo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-infinite-scroller.html, line 78 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAnloUlx5zYXHw7WT1g:-KAnp0X0en2J8D_WFUD3:-196278060) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/09729867e4fb722a197bbb443efb90b0ecb6ef1e/vaadin-infinite-scroller.html#L78)):*
could you add a comment like 'Initially should have some value to be able to scroll backwards'

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by tomivirkki** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[vaadin-infinite-scroller.html, line 78 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38#-KAnloUlx5zYXHw7WT1g:-KAnrd4sOeBnc7Hz_vO2:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/09729867e4fb722a197bbb443efb90b0ecb6ef1e/vaadin-infinite-scroller.html#L78)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by manolo** [comment]
Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Comment by manolo** [comment]
Reviewed 6 of 7 files at r2, 1 of 1 files at r3, 1 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/38)*

**Pull request merged**
