### PR TITLE
Fix bug in chrome 63 preventing click on cells in 1.x version

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/432)

### CODE REVIEW

**Comment by limonte** [comment]
I don't know why we adding hacks for canary version. We not supporting beta or canary version. Only **latest stable**. Let's wait for 63 stable and revisit this issue. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/432#-:-Kton6ab-LDhKjXOhS1R:bbkqc69)*

**Comment by manolo** [comment]
Team does not want to fix issues for non stable browser releases

**Comment by tomivirkki** [comment]
Looks like this is already broken on Chrome 62. @manolo reopen?

**Comment by limonte** [comment]
@manolo please reopen this PR so we can fir the `1.x` as well

**Pull request closed without merging**
