### PR TITLE
Restore excplicit year scroller buffer width

### LINKED ISSUE #384: Year numbers misaligned on Firefox (2.0.0-alpha2) when scrollbars visible
screen shot 2017-06-08 at 12 56 38

Setting  `width: 90px` (parent width) on the buffer elements seems to help.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #384

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/385)

### CODE REVIEW

**Comment by platosha** [comment]
The year scroller looks good! The month scroller still has some extra offset in FF.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/385#-:-Km6rR6NhE9kcS93NN2g:b-8kcjd2)*

**Comment by tomivirkki** [comment]
Yep, that's not a regression though. It has been there since the first version. Fixing this would probably require doing some scrollbar width measurement.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/385#-:-Km6s4QNwh9UBb9_517c:b-k1pmvf)*

**Comment by platosha** [comment]
OK then. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/385#-:-Km6t3g1FeTEgAmzwnjM:b-3zaemy)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/385#-:-KmAPHBytABJlD49H2_8:bnfp4nl)*

**Pull request merged**
