### PR TITLE
Hide clear icon when the element disabled or readonly

### LINKED ISSUE #201: Disabled/readonly modes show clear icon
Regression: The clear icon is visible in readonly/disabled modes. It can even be used in readonly.
screenshot 2016-06-22 09 41 36

### PR DESCRIPTION
**Pull request by platosha**
Fixes #201

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/202)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 147 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLFaLbBXnabT9byZnek:-KLFaLbBXnabT9byZnel:1565483206) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da9ec4b2e8fac680cce41229de7d1a461da1094b/vaadin-date-picker.html#L147)):*
> ```HTML
>       :host(:not([has-value])) #clear,
>       :host([readonly]) #clear,
>       :host([disabled]) #clear {
> ```

Should probably use these for hiding the calendar icon also. It's currently hidden with _hideCalendarIcon(...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
While reviewing this, noticed that also the clear icon is visible even while the dropdown is closed. Please fix this also.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-:-KLFbAwEhPc4TgA1CdBx:329841836)*

**Comment by tehapo** [comment]
I agree with comments from @tomivirkki. Otherwise looks good.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-:-KLFdb4I-GGzdIy33oMV:425920026)*

**Comment by platosha** [comment]
@tomivirkki the clear icon is now hidden when the dropdown is closed.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 147 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLFaLbBXnabT9byZnek:-KLFx9ljlRXIr9Y6eiHr:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/da9ec4b2e8fac680cce41229de7d1a461da1094b/vaadin-date-picker.html#L147)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Should probably use these for hiding the calendar icon also. It's currently hidden with _hideCalendarIcon(...)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-:-KLFxAaxdn2wkSzg8wMD:-517769091)*

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/basic.html, line 413 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLFzMhwzKhOxCU35Ns2:-KLFzMhwzKhOxCU35Ns3:-986387437) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ebd19d7d23668f6f65d365a7ef9392d00cf5ed96/test/basic.html#L413)):*
> ```HTML
> 
>         it('clear icon should be hidden', function() {
>           expect(datepicker.$.clear.clientHeight).to.equal(0);
> ```

Was there some reason to change these checks from `display` value to use `clientHeight` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/basic.html, line 413 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLFzMhwzKhOxCU35Ns2:-KLFzyalzCN1QZh95Dl4:497898415) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ebd19d7d23668f6f65d365a7ef9392d00cf5ed96/test/basic.html#L413)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> Was there some reason to change these checks from `display` value to use `clientHeight` instead?
</details>
There were other tests checking for icons’s `clientHeight`. Decided to keep them the same way. Also, this looks a bit simpler.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tehapo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/basic.html, line 413 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLFzMhwzKhOxCU35Ns2:-KLG-ZSlF0q2XrsBRtqw:-510466975) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ebd19d7d23668f6f65d365a7ef9392d00cf5ed96/test/basic.html#L413)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> There were other tests checking for icons’s `clientHeight`. Decided to keep them the same way. Also, this looks a bit simpler.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-:-KLG03U9NhEU1lqeJqnG:1417088721)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLG34ca5mIjiSleukCA:907512652) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
> ```HTML
>       },
> 
>       _hideClearIcon: function(selectedDate, opened, fullscreen) {
> ```

Having the clear icon always hidden on "fullscreen" was one thing that got ignored while custom input feature was implemented. Now the base element's clear icon flashes on iOS while opening before it's covered by the fullscreen mode. Not a biggie but still an annoyance.

It's ok to fix it in this PR or alternatively we can create an additional ticket/PR for it. Other than that this PR LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLG5ugjPRM6NBDJr4tx:1361358929) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Having the clear icon always hidden on "fullscreen" was one thing that got ignored while custom input feature was implemented. Now the base element's clear icon flashes on iOS while opening before it's covered by the fullscreen mode. Not a biggie but still an annoyance.
> 
> It's ok to fix it in this PR or alternatively we can create an additional ticket/PR for it. Other than that this PR LGTM
</details>
I can fix it in this PR, but the implementation is to be discussed.

Following the same approach, this would probably require us to expose the `fullscreen` attribute, so that the same is implementable for `vaadin-date-picker-light`. What do you think about exposing `_fullscreen` as a public read-only property with `reflectToAttribute`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLG8a1mlTouzUrRDRZ4:-1865998375) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> I can fix it in this PR, but the implementation is to be discussed.
> 
> Following the same approach, this would probably require us to expose the `fullscreen` attribute, so that the same is implementable for `vaadin-date-picker-light`. What do you think about exposing `_fullscreen` as a public read-only property with `reflectToAttribute`?
</details>
I guess exposing a read-only property would be a good approach. I don't like the name `fullscreen` that much, but cannot think of any better naming right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLG8S_jDkYfUHkB44VO:1493481950) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> I guess exposing a read-only property would be a good approach. I don't like the name `fullscreen` that much, but cannot think of any better naming right now.
</details>
Would it not make sense to have it as a separate attribute for the clear icon itself? like fullscreen$=[[_fullscreen]] ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLG9F_C7_s3T6tlqmTz:1316119026) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Would it not make sense to have it as a separate attribute for the clear icon itself? like fullscreen$=[[_fullscreen]] ?
</details>
....and hiding it with #clear[fullscreen=true] -selector

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLG97WZSOCMjr3W6YUl:1911818063) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> ....and hiding it with #clear[fullscreen=true] -selector
</details>
@tomivirkki this way a developer can not have the same style for an external icon inside `vaadin-date-picker-light`, because: 1) binding has to be done outside, 2) there is no property to bind to. But with a public attribute, it’s just a matter of adding a style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGDeqzwOL6PniLkWf_:150000128) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> @tomivirkki this way a developer can not have the same style for an external icon inside `vaadin-date-picker-light`, because: 1) binding has to be done outside, 2) there is no property to bind to. But with a public attribute, it’s just a matter of adding a style.
</details>
The fullscreen property still only reflects a media query so a developer can use that (max-width: 420px, max-height: 420px) as a selector with -light...

Or would exposing an additional public attribute for this be cleaner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGEkNMQfQlrODp5o__:-1268846186) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> The fullscreen property still only reflects a media query so a developer can use that (max-width: 420px, max-height: 420px) as a selector with -light...
> 
> Or would exposing an additional public attribute for this be cleaner?
</details>
Not only cleaner, but also more reliable. An external media query needs to be updated in users’s projects if we change the fullscreen detection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGJH6f3sLWyrGhZpeL:184800078) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Not only cleaner, but also more reliable. An external media query needs to be updated in users’s projects if we change the fullscreen detection.
</details>
This is starting to feel like feature creep to me. If we take the MVP approach, we expose no new properties/attributes until needed. As Teemu mentioned the naming isn't probably that well thought-out and if we just go and expose it as 'fullscreen' now, there's no going back later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGKLYbo_0BkdiBs2g_:-400854143) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This is starting to feel like feature creep to me. If we take the MVP approach, we expose no new properties/attributes until needed. As Teemu mentioned the naming isn't probably that well thought-out and if we just go and expose it as 'fullscreen' now, there's no going back later.
</details>
Ok. Then for me it seems better to leave this unfixed for a while.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGMRfL3uFmMH8HzKOp:1512840202) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Ok. Then for me it seems better to leave this unfixed for a while.
</details>
I'm fine with leaving this out of the scope of this PR. But we should create an issue of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGNeL_ssy1g_LpDuzd:1061211900) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> I'm fine with leaving this out of the scope of this PR. But we should create an issue of this.
</details>
Extracted to #203.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 252 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-KLG34ca5mIjiSleukC9:-KLGNkQCLEPn81eLu4oN:-510466975) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7f1be40d8966e3680abe62ff079ddf1baa104129/vaadin-date-picker.html#L252)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Extracted to #203.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-:-KLGNqYJEQdotDVtYK0E:1417088721)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/202#-:-KLGO8RBFeyRfb3m9-tf:1417088721)*

**Pull request merged**
