### PR TITLE
Restore focus ring if firstly was focused with Tab

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to https://github.com/vaadin/components-team-tasks/issues/306

Restore `focus-ring` if component was firstly focused with <kbd>Tab</kbd>

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/500)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500#-:-L2_5tgFYTmC_dV3lXVT:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/vaadin-date-picker.html, line 258 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500#-L2z4TXS9T15AJBnECHH:-L2z4TXS9T15AJBnECHI:b-20fjno) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7232c267a9fb36fd7bdc950c7deae0d9d6661534/src/vaadin-date-picker.html#L258)):*
> ```HTML
>         _onVaadinOverlayClose(e) {
>           if (this._openedWithFocusRing) {
>             this.focusElement.setAttribute('focus-ring', '');
> ```

What if it was closed opened with keyboard, but then closed with mouse?

Expected: the original focus is not restored on the input, focus goes to document, hence the `focus-ring` state is not set.

Actual: focus is on the document, but `focus-ring` makes you think it’s on the element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500#-:-L3m152iY-bPrZMpQfe1:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-date-picker.html, line 258 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500#-L2z4TXS9T15AJBnECHH:-L3m92mN9aP3cXOy9Fjx:bb6ywmx) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7232c267a9fb36fd7bdc950c7deae0d9d6661534/src/vaadin-date-picker.html#L258)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

What if it was closed opened with keyboard, but then closed with mouse?

Expected: the original focus is not restored on the input, focus goes to document, hence the `focus-ring` state is not set.

Actual: focus is on the document, but `focus-ring` makes you think it’s on the element.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/500#-:-L3m95lZ8Daz_hQ4o5Qq:bnfp4nl)*

**Pull request merged**
