### PR TITLE
Typing a date in the input should change focused date

### LINKED ISSUE #438: Typing the date in the input with keyboard does not change focused date
It seems that it's necessary to have the overlay closed to see the problem in action

http://recordit.co/FuRJWJESMO

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #438

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/495)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Every bugfix is required to be delivered with a test

**Comment by vicsstar** [comment]
My bad, skipped my mind. Coming up.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/495#-:-L1wXinmMW9MMynzyT0B:b-yhz0xa)*

**Comment by vicsstar** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/495#-:-L2-9VsDjbCOxKGlLINX:b-896fix)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/495#-:-L20GLGQsBYLtiK_ni4v:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/495#-:-L20KF1J7Rp2hjJyQFDP:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/495#-:-L20KHxNCQtuoBqdracH:bnfp4nl)*

**Pull request merged**
