### PR TITLE
Fix week number UX

### LINKED ISSUE #253: Improve UX of week numbers
Currently the date picker week numbers have some UX issue. They are equally close from two weeks. It’s not clear which week do they correspond to.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #253  

date_picker_week_number

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/257)

### CODE REVIEW

**Comment by platosha** [comment]
IMO: The week number is *even closer to the first day of the week* than the date numbers are to each other.

My suggestion: use the width 12% for the dates. Use the width of 10% + padding-right of 2% for week number cells. So, the week number cell width would be smaller then regular, but padding-right on the week number would make the actual distance back constant. In total we have: 10% + 12%*7 = 94% of cell space, and 6% white space on the right.

Before:


After:


Advantages:
1. Constant rhythm between numbers, easier to consume, less confusion.
2. The week numbers are now clearly on the side, less confusion.
3. The white space on the right compensates for the week numbers, making the dates back to almost the center. This gives more visual priority on the dates, less on the week numbers, less confusion.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257#-KTyHjcBpBY5w2kYPBt8:-KTyHjcBpBY5w2kYPBt9:b-jjejse) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/80ef3966da282fa507fe1e25fa464ef2fd79a179/vaadin-month-calendar.html#L99)):*
> ```HTML
>         cursor: default;
>         color: rgba(0, 0, 0, 0.4);
>         width: calc(9% - 2px);
> ```

Please group this value together with the empty cell selector, so that a single line defines the width for both of them. This way it would be easier to tweak.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257#-:-KTyKsbaBiGMcqoV6bcA:b-pfkwcl)*

**Comment by platosha** [comment]
Patch:

```patch
diff --git a/vaadin-month-calendar.html b/vaadin-month-calendar.html
index 93a5acc..b958581 100644
--- a/vaadin-month-calendar.html
+++ b/vaadin-month-calendar.html
@@ -39,7 +39,7 @@
       }
 
       :host([week-numbers]) #monthGrid div {
-        width: calc(13% - 2px);
+        width: calc(12% - 2px);
       }
 
       #monthGrid div:not(:empty) {
@@ -57,8 +57,10 @@
         @apply(--vaadin-date-picker-calendar-weekday-cell);
       }
 
-      #monthGrid div.weekday:empty {
-        width: calc(9% - 2px);
+      #monthGrid div.weekday:empty,
+      #monthGrid div.weeknumber {
+        width: calc(10% - 2px);
+        padding-right: 2%;
       }
 
       #monthGrid div[today] {
@@ -96,7 +98,6 @@
       #monthGrid div.weeknumber {
         cursor: default;
         color: rgba(0, 0, 0, 0.4);
-        width: calc(9% - 2px);
         @apply(--paper-font-caption);
         @apply(--vaadin-date-picker-calendar-weeknumber-cell);
       }
```

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257#-:-KTyRomgxuw7Z0EhgLrp:b4v5kec)*

**Comment by samiheikki** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-month-calendar.html, line 99 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257#-KTyHjcBpBY5w2kYPBt8:-KU0l66M-ByYrI6lsUFk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/80ef3966da282fa507fe1e25fa464ef2fd79a179/vaadin-month-calendar.html#L99)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Please group this value together with the empty cell selector, so that a single line defines the width for both of them. This way it would be easier to tweak.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257)*

**Comment by samiheikki** [comment]
@jouni Can we have your input on the empty space on right side of the month calendar?

**Comment by jouni** [comment]
Thanks @platosha for your eye for details like this, I appreciate it!

Everything else in your suggestion rhymes with me, but the empty space on the right side seems unnecessarily large. How does it fit on a 320px wide screen – we probably need to at least reduce it there, and tighten the calendar spacing also.

**Comment by platosha** [comment]
@jouni holds up on 320px perfectly:
screen shot 2016-10-14 at 10 54 57

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257#-:-KU1TYp3SlAaiwgxpNJD:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/257#-:-KU1VkRWxCtrS0Ys_ooT:bnfp4nl)*

**Pull request merged**
