### PR TITLE
iron-form support added, ISO String format for value property

### LINKED ISSUE #51: Integration with `iron-form`
`iron-form` support initial plan:
- Add `Polymer.IronFormElementBehavior` and `Polymer.IronValidatableBehavior`
- Separate properties for `selectedDate` (Date object, default `null`) and `value` (formatted String, empty by default)
  - both writeable, updating each other if needed
  - `value` might also support Date assignment
- `valueFormat` property. Use input field `format` when empty.
- Date formatting depends on locale. Update `value` on locale change.

### LINKED ISSUE #63: Clear icon is shown when bound to a null value
I would expect that just an empty field is shown for both null and empty values.

### PR DESCRIPTION
**Pull request by platosha**
Closes #51
Fixes #63 

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/69)

### CODE REVIEW

**Comment by tomivirkki** [comment]
If you open a vaadin-date-picker with no value set (in fullscreen mode) it displays the clear-icon on the header

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-date-picker.html, line 170 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69#-KBRv5tLWroGv4f1sgnk:-KBRv5tLWroGv4f1sgnl:-1117642119) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/cb0a629a794ec7323a133d4f421202462cb5237b/vaadin-date-picker.html#L170)):*
This check shouldn't be needed. Polymer does the check internally and invokes the observer only on change

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69#-:-KBRtjyAa18Y95LhIjax:-823743838)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker.html, line 170 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69#-KBRv5tLWroGv4f1sgnk:-KBhB7WGQWIxDhsFwYm7:677534651) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/cb0a629a794ec7323a133d4f421202462cb5237b/vaadin-date-picker.html#L170)):*
bump

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69)*

**Comment by tomivirkki** [comment]
...also, clicking the calendar icon opens the dropdown as it should but clicking it again no longer closes it

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69#-:-KBhBq8AntTrKRKnjmOX:-1362206345)*

**Comment by platosha** [comment]
↑ These two issues above are resolved.

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker.html, line 170 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69#-KBRv5tLWroGv4f1sgnk:-KBhILvTBRtWo5i-4Pbv:-499146009) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/cb0a629a794ec7323a133d4f421202462cb5237b/vaadin-date-picker.html#L170)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69#-:-KBhHyeQrlVXT0DKk6Pc:-1681985306)*

**Comment by tomivirkki** [comment]
Reviewed 4 of 9 files at r1, 1 of 2 files at r2, 1 of 4 files at r3, 1 of 2 files at r4, 2 of 4 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/69)*

**Pull request merged**
