### PR TITLE
Document date part state attributes

### LINKED ISSUE #499: Document all state attributes
The state attributes for the `date` part are not documented (`today`, `selected`, `disabled`, `focused`, etc.).

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #499

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/503)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/vaadin-date-picker-light.html, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32QFh1l_CqqaGpkPmv:-L32QFh1l_CqqaGpkPmw:b-ygoxb4) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker-light.html#L93)):*
> ```HTML
>        * Part name | Description | Theme for Element
>        * ----------------|----------------|----------------
>        * `overlay` | The overlay element | vaadin-date-picker-light
> ```

Hey, now that we are here... This part name is wrong in master, should be renamed to `overlay-content`.

The same part is called `overlay-content` in the regular `<vaadin-date-picker>`’s template: https://github.com/vaadin/vaadin-date-picker/blob/783163d34f1bedf4dfcc048e9226097efd23c479/src/vaadin-date-picker.html#L101

---

*[src/vaadin-date-picker.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32SN0LqVkTzC5rQj7k:-L32SN0LqVkTzC5rQj7l:bvg5rxg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker.html#L136)):*
> ```HTML
>        * `clear-button` | Clear button | vaadin-date-picker
>        * `toggle-button` | Toggle button | vaadin-date-picker
>        * `overlay` | The overlay element | vaadin-date-picker
> ```

The part name is `overlay-content`.

---

*[src/vaadin-date-picker.html, line 168 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32RECg644LhMQJ4KKV:-L32RECh0ins74w4_leO:bauyinm) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker.html#L168)):*
> ```HTML
>        * `today` | Set on the date corresponding to the current day | date
>        * `focused` | Set on the focused date | date
>        * `disabled` | Set on the disabled date | date
> ```

OK Not a blocker, but this is somehow confusing.

The state attributes of `[part="date"]` should be styled in `<vaadin-month-calendar>`. This is hard to tell by looking at this table, and requires to find out where the `date` part is, either from the list above, or from the source code.

Dunno what’s the best way, but personally I would add one more column here

---

*[src/vaadin-date-picker.html, line 169 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32RFH_tjpzT6X3pOI0:-L32RFH_tjpzT6X3pOI1:bwixrs8) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker.html#L169)):*
> ```HTML
>        * `focused` | Set on the focused date | date
>        * `disabled` | Set on the disabled date | date
>        * `disabled` | Set on the disabled date | date
> ```

Duplicate line. Was it supposed to be about the `disabled` attribute of the host?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503)*

**Comment by web-padawan** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/vaadin-date-picker-light.html, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32QFh1l_CqqaGpkPmv:-L32pj1evZa6g3ihCRj-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker-light.html#L93)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Hey, now that we are here... This part name is wrong in master, should be renamed to `overlay-content`.

The same part is called `overlay-content` in the regular `<vaadin-date-picker>`’s template: https://github.com/vaadin/vaadin-date-picker/blob/783163d34f1bedf4dfcc048e9226097efd23c479/src/vaadin-date-picker.html#L101
</blockquote></details>

Done.

---

*[src/vaadin-date-picker.html, line 136 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32SN0LqVkTzC5rQj7k:-L32pk2juMyvN_rPuOZR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker.html#L136)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The part name is `overlay-content`.
</blockquote></details>

Done.

---

*[src/vaadin-date-picker.html, line 169 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32RFH_tjpzT6X3pOI0:-L32pp6p05nr8zfZ7In2:b-ns7vj) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/986d22d28156a55bd704956966cb403a1ec44f9a/src/vaadin-date-picker.html#L169)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Duplicate line. Was it supposed to be about the `disabled` attribute of the host?
</blockquote></details>

Done. Changed description and updated duplicate line for `selected` state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[src/vaadin-date-picker-light.html, line 47 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32rL_lTAdGExZlQabY:-L32rL_lTAdGExZlQabZ:b-pnsvb9) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/6f93a740bd6633fb93d50b338fc7a2733d56e070/src/vaadin-date-picker-light.html#L47)):*
> ```HTML
>           on-date-tap="_close"
>           role="dialog"
>           part="overlay">
> ```

There it is still `content`, should be `overlay-content`.

---

*[src/vaadin-date-picker.html, line 165 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32rmC5TmB9kKMv0j7i:-L32rmC5TmB9kKMv0j7j:bz9lp2k) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/6f93a740bd6633fb93d50b338fc7a2733d56e070/src/vaadin-date-picker.html#L165)):*
> ```HTML
>        * `invalid` | Set when the element is invalid | :host
>        * `opened` | Set when the date selector overlay is opened | :host
>        * `readonly` | Set when the element is readonly | :host
> ```

`readonly` is mentioned, but `disabled` host state attribute is missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503)*

**Comment by web-padawan** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-date-picker-light.html, line 47 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32rL_lTAdGExZlQabY:-L32taQHhppVmSqFWeje:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/6f93a740bd6633fb93d50b338fc7a2733d56e070/src/vaadin-date-picker-light.html#L47)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

There it is still `content`, should be `overlay-content`.
</blockquote></details>

Done.

---

*[src/vaadin-date-picker.html, line 165 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-L32rmC5TmB9kKMv0j7i:-L32tbmo2OZGR80SoRC8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/6f93a740bd6633fb93d50b338fc7a2733d56e070/src/vaadin-date-picker.html#L165)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`readonly` is mentioned, but `disabled` host state attribute is missing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-:-L32v0-tKdea1a2NWpKK:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/503#-:-L37O107yiDfpdJoA4DJ:bnfp4nl)*

**Pull request merged**
