### PR TITLE
Sync with element-skeleton

### PR DESCRIPTION
**Pull request by limonte**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/313)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[README.md, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYmJg7jTe9p6zYBimbz:-KYmJg7jTe9p6zYBimc-:b-ivjgt0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L6)):*
> ```Markdown
> # &lt;vaadin-date-picker&gt;
> 
> ### [Live demo](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/)
> ```

Why do we want to move contribution docs back to individual components' readme files? We intentionally did the opposite earlier this year: https://github.com/vaadin/vaadin-date-picker/commit/202aaf6e7c63cfb092ddef0545d94c7c1e927a5b

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313)*

**Comment by limonte** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYmJg7jTe9p6zYBimbz:-KYmKsX5Di4P_UqmQic5:b9aradl) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L6)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why do we want to move contribution docs back to individual components' readme files? We intentionally did the opposite earlier this year: https://github.com/vaadin/vaadin-date-picker/commit/202aaf6e7c63cfb092ddef0545d94c7c1e927a5b
</blockquote></details>

Nice question! I'm doing this because of contributors outside the Vaadin. 
Imagine the freelancer which love and use our Grid element. He's willing to fix a bug or to introduce a feature. Contribution guide should be as close as possible to him. We shouldn't force developers to be familiar with whole core-elements project.

Every our component should have the developer's guide to be accessible and friendly for contributors, so they can take a part without additional effort to figure out what core-elements is.

I understand your concern about DRY principle, but IMO, in this case, we're getting more advantages from copy-pasting instructions to each element. We're already copy-pasting a lot of files (.travis.yml, .eslintrc, etc.) so I don't think this will be an issue.  

PS. in future we'll surely need the Vaadium bot to be able to maintain all our components, updating the README for all components won't be a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313)*

**Comment by Saulis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYmJg7jTe9p6zYBimbz:-KYmkeOt1QaqLygmJbLF:bj851i7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L6)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Nice question! I'm doing this because of contributors outside the Vaadin. 
Imagine the freelancer which love and use our Grid element. He's willing to fix a bug or to introduce a feature. Contribution guide should be as close as possible to him. We shouldn't force developers to be familiar with whole core-elements project.

Every our component should have the developer's guide to be accessible and friendly for contributors, so they can take a part without additional effort to figure out what core-elements is.

I understand your concern about DRY principle, but IMO, in this case, we're getting more advantages from copy-pasting instructions to each element. We're already copy-pasting a lot of files (.travis.yml, .eslintrc, etc.) so I don't think this will be an issue.  

PS. in future we'll surely need the Vaadium bot to be able to maintain all our components, updating the README for all components won't be a problem.
</blockquote></details>

I agree with @limonte here, the new README appears more welcoming and approachable than previously.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313)*

**Comment by manolo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYwTcJiyj06mNO67VT0:-KYwTcJiyj06mNO67VT1:b-s0qxqh) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L6)):*
> ```Markdown
> # &lt;vaadin-date-picker&gt;
> 
> ### [Live demo](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/)
> ```

Live demo link as a title looks weird to me.
Probably a section after the introduction and screenshot would be better, or just a line inviting the user to visit the demos, but not a header.

---

*[README.md, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYwSDSdQc_iEtcg5izF:-KYwSDSdQc_iEtcg5izG:b-a2skz9) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L13)):*
> ```Markdown
> <vaadin-date-picker label="Birthday">
> </vaadin-date-picker>
> ```
> ```

This does not work in webcomponents.org. 
you need the `<!-- -->` Block.

Also I will move the Live demo link after the webcomponents.org demo and screenshot. 
Users visiting the webcomponents.org page, expect the live demo in the page at the top, and the full demo links at the right links.

But users visiting the github.com README does not mind to have it after the screenshot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313)*

**Comment by platosha** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYmJg7jTe9p6zYBimbz:-KYwXc5RYqsZ6JOzXDwi:bw47e9j) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L6)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I agree with @limonte here, the new README appears more welcoming and approachable than previously.
</blockquote></details>

BTW agree with @limonte :thumbsup: for the contribution instructions directly in README files. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313)*

**Comment by limonte** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-KYwTcJiyj06mNO67VT0:-KYwan7Sj0QNTMWCM8Q-:b-igc8tk) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/60eda4f4d99919dc4486120b49a4a2d61ab90a50/README.md#L6)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Live demo link as a title looks weird to me.
Probably a section after the introduction and screenshot would be better, or just a line inviting the user to visit the demos, but not a header.
</blockquote></details>

https://github.com/vaadin/vaadin-element-skeleton/pull/4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/313#-:-KZKokJpxu5AfzjCdffa:bnfp4nl)*

**Pull request merged**
