### PR TITLE
Keep focus when overlay is closed by clicking outside.

### LINKED ISSUE #475: Keep focus if overlay is closed by clicking outside it
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #475

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/474)

### CODE REVIEW

**Comment by manolo** [comment]
There is still an issue remaining, which is related to maintain focused styles when the overlay is opened like happens with combo-box and dropdown-menu, Probably that part could be easier to implement after adding control-state beheviour to date-picker

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/dropdown.html, line 95 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474#-KzgtCLzuB4egCEOBV_S:-KzgtCLzuB4egCEOBV_T:b-vz784v) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/597de8f6d7abc77b62f12c49b3f0835406324197/test/dropdown.html#L95)):*
> ```HTML
>         datepicker.addEventListener('iron-overlay-closed', () => {
>           const input = datepicker._nativeInput;
>           expect(input.getRootNode().activeElement).to.be.equal(input);
> ```

Normally this kind of tests could fail in travis when the tests run in a frame-buffer xterminal and IE11.
You might check whether the focused status remains set, or just use sinon.spy for checking that the method to focus was set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474#-:-KzgtedHYwHnfawdAloJ:b-1g9i09)*

**Comment by manolo** [comment]
@vicsstar could you try to fix the test

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474#-:-KzyCcmPW9mOhjhrXk9F:b-ypyyis)*

**Comment by vicsstar** [comment]
*[test/dropdown.html, line 95 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474#-KzgtCLzuB4egCEOBV_S:-L-0ihqZ9_Bq0nT0ROqd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/597de8f6d7abc77b62f12c49b3f0835406324197/test/dropdown.html#L95)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Normally this kind of tests could fail in travis when the tests run in a frame-buffer xterminal and IE11.
You might check whether the focused status remains set, or just use sinon.spy for checking that the method to focus was set.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474)*

**Comment by vicsstar** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474#-:-L-0ioZemE46-nwju33H:b-896fix)*

**Comment by web-padawan** [comment]
Please rebase on top of the current `master`.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/474#-:-L-0n2KpGe-KSQesTHrD:b-w9dwxa)*

**Comment by tomivirkki** [comment]
@YuriyVaadin Was this fixed by https://github.com/vaadin/vaadin-date-picker/pull/482? I recall you mentioning that at some point.

**Pull request closed without merging**
