### PR TITLE
Always focus the overlay when opened with up/down keys

### LINKED ISSUE #301: Inconsistent keyboard navigation when opening popup
### Description
When a date field is empty, you can press arrow down to open the popup and then navigate to yesterday using arrow left.

If the date field is set the today's date, pressing arrow down still opens the popup but arrow left does not navigate to yesterday.

If you happen to do arrow up or down before arrow left, then arrow left works in both cases.
### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari

### PR DESCRIPTION
**Pull request by tomivirkki**
Also, never focus the overlay with left/right arrows

Fixes #301

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/306)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-date-picker-behavior.html, line 477 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/306#-KXPF04EHY2wQ02EMiyq:-KXPF04EHY2wQ02EMiyr:b3516n5) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4ce77a41d345962487754d25747acf01d5bc3335/vaadin-date-picker-behavior.html#L477)):*
> ```HTML
>       }
> 
>       if (this._focusOverlayOnOpen) {
> ```

I would move this logic to this_focus method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/306)*

**Comment by tomivirkki** [comment]
*[vaadin-date-picker-behavior.html, line 477 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/306#-KXPF04EHY2wQ02EMiyq:-KXPOUS8rSnZ876e6ri1:b-cgdgmt) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4ce77a41d345962487754d25747acf01d5bc3335/vaadin-date-picker-behavior.html#L477)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would move this logic to this_focus method
</details>
Hmm....well the functionality depends on open (as stated in the variable name). Checking the variable '_focusOverlayOnOpen' in focus isn't logical since the function is invoked from other contexts than open as well.

Maybe changing the name 'this._focus()' to 'this._focusPrimaryTarget' or something would make the logic more understandable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/306)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/306#-:-KXPoFfapTKX6eF0Ad1v:bnfp4nl)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/306#-:-KXXD29A3QOq2uvE6wm7:bnfp4nl)*

**Pull request merged**
