### PR TITLE
Added function to localize calendar title

### PR DESCRIPTION
**Pull request by cwdoh**
Added `formatTitle` function to option for localizing calendar title on `vaadin-month-calendar`.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/152)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-month-calendar.html, line 125 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152#-KEaCOLCPs9koRoaoKhC:-KEaCOLCPs9koRoaoKhD:-1502614817) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a223aa6be90ac1b7abf1d06c23c22c8f859738f1/vaadin-month-calendar.html#L125)):*
The problem with exposing the Date object we call 'month' to the public API is that it's date and time values might be anything really (because it's initialized with "_dateAfterXMonths" function).

Would it be an option to provide the API only the necessary data like:
`return this.i18n.formatTitle(d.getFullYear(), d.getMonth())`

---

*[demo/index.html, line 77 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152#-KEa9vXcjWWvw1wMnWQG:-KEa9vXdscb7VYsa_z0O:324143307) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a223aa6be90ac1b7abf1d06c23c22c8f859738f1/demo/index.html#L77)):*
Shouldn't say 'in' by default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152)*

**Comment by jounik** [comment]
*[demo/index.html, line 77 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152#-KEa9vXcjWWvw1wMnWQG:-KEaF-yK3skj-9tpJ8qA:-1500157392) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a223aa6be90ac1b7abf1d06c23c22c8f859738f1/demo/index.html#L77)):*
I guess we could replace that with 'ta ', to make it read "huhtikuuta 2016" etc. which is proper Finnish still?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152)*

**Comment by tomivirkki** [comment]
*[demo/index.html, line 77 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152#-KEa9vXcjWWvw1wMnWQG:-KEaG0GXYY6L2E-SYDzY:165667191) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a223aa6be90ac1b7abf1d06c23c22c8f859738f1/demo/index.html#L77)):*
Hmm..."huhtikuuta 2016" sounds like it needs a date number before it. For a finnish month title I'd prefer just "huhtikuu 2016" (nothing in between)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152)*

**Comment by cwdoh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 77 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152#-KEa9vXcjWWvw1wMnWQG:-KEaQCWiMyHuKBJrDq3-:-1479450137) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a223aa6be90ac1b7abf1d06c23c22c8f859738f1/demo/index.html#L77)):*
I understand 'April 2016' is 'huhtikuuta 2016' in Finnish, btw I couldn't take what is nice case to demonstrate `formatTitle`. For example, it can be format like '2016년 4월' in Korean. In my project, I write below:

```
	// format calendar title as Korean date format
	formatTitle: function(d, monthNames) {
		return  d.getFullYear() + '년 ' + monthNames[d.getMonth()];
	}
```

I guess this will be common case in lots of countries such as South Korea, China and Japan according to [link](https://en.wikipedia.org/wiki/Date_format_by_country). They may be proper cases for this feature. If you guys agree, I'll add some date formats in Asia. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/152)*

**Comment by jounik** [comment]
One easy option is to format the title with some extra HTML markup, like `"<b>" + monthNames[d.getMonth()] + "</b> " + d.getFullYear();`

**Comment by tomivirkki** [comment]
Hi, we discussed the i18n.formatTitle API with the team and came up with a proposal at https://github.com/vaadin/vaadin-date-picker/commit/32cc51a405d2135ebc84ea96df98c24b020a7971

Does this work for your use case? If it's ok for you we can just merge this branch

**Comment by cwdoh** [comment]
@tomivirkki Cool, it works for my case. 👍

**Pull request closed without merging**
