### PR TITLE
Use wct from command line instead of Gulp tasks

### PR DESCRIPTION
**Pull request by limonte**
With this solution we don't have that weird `wct` bug when it results with great success even if tests are failing, so I updated the `wct` dependency to latest.

Build is still slow (20-30 min), but at least is passes :)

And output became prettier than is was: 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/312)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[run-sauce-tests.sh, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXykR-WtlLBU9xzQCCZ:-KXykR-WtlLBU9xzQCC_:b8t56g1) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Although most un*x nowadays have bash, I'd rather use the standard korn shell `/bin/sh` since you are not using specific `bash` features

do you know if this script is run with the `-e` flag. If not we should set it here otherwise trivial operations that might fail will pass like `cp test/ ... `

---

*[run-sauce-tests.sh, line 2 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXykqo40V22OWTvzPiZ:-KXykqo40V22OWTvzPi_:b3sjktq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L2)):*
> ```Shell
> #!/bin/bash
> BROWSERS=$1
> ```

I do prefer camel-case variables and use upercased for constants, not blocking though

---

*[run-sauce-tests.sh, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyjFhmoso3Kl-DbgNm:-KXyjFhmoso3Kl-DbgNn:b-mwmmmt) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L5)):*
> ```Shell
> SHADOW=$2
> 
> USAGE="usage: ./run-sauce-tests <browsers> <shadow-dom>
> ```

make usage a method exiting with the status 1, so as you can just use short sentences below `[ -z "$browsers" ] && usage`

Please use strong quotes here so as you don't have to escape special shell characters. 

---

*[run-sauce-tests.sh, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyjufQPzOCTPlNIXi7:-KXyjufQPzOCTPlNIXi8:b-iisqk9) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L11)):*
> ```Shell
> 
> if [ -z "$BROWSERS" ] ; then
>   echo "<browsers> argument is missing."
> ```

Redundant line since it's already explained in usage

---

*[run-sauce-tests.sh, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXykju7U-_XcuywEKmk:-KXykju7U-_XcuywEKml:b-neemjp) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L20)):*
> ```Shell
> 
> # put browsers to wct.conf.json
> sed -i -e "s|\${BROWSERS}|$(echo $BROWSERS | sed -r 's|,\s+|", "|g')|" wct.conf.json
> ```

regex are more readable if using the `/` character

---

*[run-sauce-tests.sh, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyl587FPMBXxuRTyJU:-KXyl587FPMBXxuRTyJV:b4wkpj0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L30)):*
> ```Shell
> 
> # pretty output
> printf "\n *** \033[0;33mRUNNING TESTS FOR $BROWSERS "
> ```

Avoid escape sequences in scripts. They make the code more unreadable, and do not facilitate processing the output, #FFS

---

*[test/wct.conf.template, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXylNb2wjqSPEXHxkcz:-KXylNb2wjqSPEXHxkd-:b-t3stre) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/test/wct.conf.template#L5)):*
> ```
>     "sauce": {
>       "browsers": [
>         "${BROWSERS}"
> ```

since those are kind of template markers, do not use syntax that make sense for bash, etc, use something like __BROWSERS__ or %BROWSERS% or whatever makes the reader understand better what is happening when taking a look to this file out of the full context

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312)*

**Comment by manolo** [comment]
Do we know that sauce always run this in unix systems?  do they have windows?

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-:-KXymLp36bMDEmG9Phj1:b6uff7k)*

**Comment by limonte** [comment]
I'm not sure how Sauce actually works.

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-:-KXzLR6819i2bUwk9VJa:bft9jia)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[run-sauce-tests.sh, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXykR-WtlLBU9xzQCCZ:-KY-0euWxdu8cFf-9GcS:b-vn5bl7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L1)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Although most un*x nowadays have bash, I'd rather use the standard korn shell `/bin/sh` since you are not using specific `bash` features

do you know if this script is run with the `-e` flag. If not we should set it here otherwise trivial operations that might fail will pass like `cp test/ ... `
</blockquote></details>

Script was removed.

---

*[run-sauce-tests.sh, line 2 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXykqo40V22OWTvzPiZ:-KY-0gKfOT6bOP6AeD6L:b-vn5bl7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L2)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I do prefer camel-case variables and use upercased for constants, not blocking though
</blockquote></details>

Script was removed.

---

*[run-sauce-tests.sh, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyjFhmoso3Kl-DbgNm:-KY-0a2orJ5gp0yivxgk:b-vn5bl7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

make usage a method exiting with the status 1, so as you can just use short sentences below `[ -z "$browsers" ] && usage`

Please use strong quotes here so as you don't have to escape special shell characters. 
</blockquote></details>

Script was removed.

---

*[run-sauce-tests.sh, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyjufQPzOCTPlNIXi7:-KY-0aemZ_38L-pPmrts:b-vn5bl7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L11)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Redundant line since it's already explained in usage
</blockquote></details>

Script was removed.

---

*[run-sauce-tests.sh, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXykju7U-_XcuywEKmk:-KY-0fYpeTKi6Pcejbye:b-vn5bl7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

regex are more readable if using the `/` character
</blockquote></details>

Script was removed.

---

*[run-sauce-tests.sh, line 30 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyl587FPMBXxuRTyJU:-KY-0gg04KLvqf28id9q:b-vn5bl7) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L30)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Avoid escape sequences in scripts. They make the code more unreadable, and do not facilitate processing the output, #FFS
</blockquote></details>

Script was removed.

---

*[test/wct.conf.template, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXylNb2wjqSPEXHxkcz:-KY-0hTZrV5c9PNSgtbS:b-205fqy) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/test/wct.conf.template#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

since those are kind of template markers, do not use syntax that make sense for bash, etc, use something like __BROWSERS__ or %BROWSERS% or whatever makes the reader understand better what is happening when taking a look to this file out of the full context
</blockquote></details>

Template was removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[run-sauce-tests.sh, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KXyjufQPzOCTPlNIXi7:-KYE2K0evLqUJh0q91fb:bq54zy0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/fd024f1f799e46156fd3b25aad60b63c5e6f03f7/run-sauce-tests.sh#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Script was removed.
</blockquote></details>

ping :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312)*

**Comment by platosha** [comment]
@manolo Sauce Labs runs the test browser, but the build actually runs by Travis. Currently they use Ubuntu Linux container-based environment, other options are sudo-enabled Ubuntu and OS X. No windows.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[.travis.yml, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KYE64W89SzLlZ6ViKuQ:-KYE64W89SzLlZ6ViKuR:bqpnbxp) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a1f09a73a5b4d9b6525c40b1550b9eeeff1ab5d8/.travis.yml#L12)):*
> ```YAML
>   - npm install -g bower
>   - bower install
>   - npm install -g web-component-tester
> ```

I’d suggest:

```yaml
install:
  - npm install -g bower web-component-tester
  - npm install
  - bower install
```

Pros:

- Less invocations
- Global dependencies are installed first

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-:-KYEJWOVAfFkaVFpx_pL:b-k1d5hb)*

**Comment by platosha** [comment]
@limonte LGTM in general, but I would try to beautify the Travis config more, and get rid of the multiple browser environment variables. Somewhat like:

```diff
diff --git a/.travis.yml b/.travis.yml
index 6dcc041..dd28dc3 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,25 +6,27 @@ cache:
   directories:
     - node_modules
 install:
+  - npm install -g bower web-component-tester
   - npm install
-  - npm install -g bower
   - bower install
-  - npm install -g web-component-tester
 env:
   # desktop
-  - BROWSER1="Windows 10/chrome@54"
-    BROWSER2="Windows 10/firefox@50"
-    BROWSER3="Windows 10/microsoftedge@13"
-    BROWSER4="Windows 10/internet explorer@11"
-    BROWSER5="OS X 10.11/safari@9.0"
+  - BROWSERS=(
+      '--sauce "Windows 10/chrome@54"'
+      '--sauce "Windows 10/firefox@50"'
+      '--sauce "Windows 10/microsoftedge@13"'
+      '--sauce "Windows 10/internet explorer@11"'
+      '--sauce "OS X 10.11/safari@9.0"'
+    )
   # mobile
-  - BROWSER1="OS X 10.11/iphone@9.2"
-    BROWSER2="OS X 10.11/ipad@9.2"
-    BROWSER3="Linux/android@5.1"
-    BROWSER4=" "
-    BROWSER5=" "
+  - BROWSERS=(
+      '--sacue "OS X 10.11/iphone@9.2"'
+      '--sauce "OS X 10.11/ipad@9.2"'
+      '--sauce "Linux/android@5.1"'
+    )
 script:
+  - echo $BROWSERS
   - gulp lint:html
   - gulp lint:js
-  - travis_retry wct --sauce="$BROWSER1" --sauce="$BROWSER2" --sauce="$BROWSER3" --sauce="$BROWSER4" --sauce="$BROWSER5"
-  - travis_retry wct --sauce="$BROWSER1" --sauce="$BROWSER2" --sauce="$BROWSER3" --sauce="$BROWSER4" --sauce="$BROWSER5" test/shadow.html
+  - eval travis_retry wct $BROWSERS
+  - eval travis_retry wct $BROWSERS test/shadow.html
```

Please consider removing `test/shadow.html` as well.

---

Reviewed 3 of 6 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-:-KYEaA4hUHTMq3tigyl7:b-5agydh)*

**Comment by limonte** [comment]
> I would try to beautify the Travis config more, and get rid of the multiple browser environment variables

Unfortunately, after couple of hours trying, it seems to me that it's impossible to use arrays in Travis config.

>  Please consider removing test/shadow.html

Done.

---

Review status: 1 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[.travis.yml, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-KYE64W89SzLlZ6ViKuQ:-KYKbdg_E_7O7jd_Qbhk:b-drp6gn) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/a1f09a73a5b4d9b6525c40b1550b9eeeff1ab5d8/.travis.yml#L12)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

I’d suggest:

```yaml
install:
  - npm install -g bower web-component-tester
  - npm install
  - bower install
```

Pros:

- Less invocations
- Global dependencies are installed first
</blockquote></details>

I removed that block completely and added bower to devDependencies, and `bower install` as the postinstall task in package.json

`npm install` is performed automatically, as you figured out on Monday.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-:-KYKbE9d6DnDXEeptImT:b-3xs8yw)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/312#-:-KYODHkyIashijTSpNqS:bnfp4nl)*

**Pull request merged**
