### PR TITLE
Enable tests using Shadow DOM Polyfill

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/104

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/139)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[gulpfile.js, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139#-KDTQ6lP_YnuLF66r5Mz:-KDTQ6lQMhsj3PNezrD-:1712016382) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/d425ca2d810965e18bc4315ba227d2bb98be051a/gulpfile.js#L70)):*
Comment: not sure what's happened with the Edge version numbers, but currently the latest version is 13 according to saucelabs.com/platforms

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139)*

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 8 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139#-KDThS4qJkqFJGPDMMGO:-KDThS4qJkqFJGPDMMGP:1553942739) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ade1e26e034a133bec339f3f4e4ef56c56130053/test/form-input.html#L8)):*
why we don't need this? or is it a line  that we shouldn't have here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139)*

**Comment by Saulis** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/form-input.html, line 8 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139#-KDThS4qJkqFJGPDMMGO:-KDXMdVPH-JBiTqMX3u1:1236334658) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/ade1e26e034a133bec339f3f4e4ef56c56130053/test/form-input.html#L8)):*
Turned out that since v3.4.0 WCT has provided the `test-fixture-mocha.js` script built-in.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139)*

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139#-:-KDbOQv1QTJHf49pxkK7:1417088721)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139#-:-KDbx5T5J7Ww4cRwXNaN:1417088721)*

**Comment by tomivirkki** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/139)*

**Pull request merged**
