### PR TITLE
Add support for the placeholder property

### LINKED ISSUE #269: Placeholder property
Add support for the placeholder property for the regular `<vaadin-date-picker>` element. Bind to the `placeholder` attribute of the internal `<input>`.

Make sure it also works together with the label, so that the label floats automatically if you add the placholder.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #269

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/293)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 179 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEfTi3n44PnAtgWws:-KWcEfTi3n44PnAtgWwt:be23cnr) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/vaadin-date-picker.html#L179)):*
> ```HTML
>         disabled$="[[disabled]]"
>         role="application"
>         always-float-label$={{placeholder}}>
> ```

Please comment somewhere (commit line message, or a message here) the reason why we need to assign `always-float-label`

---

*[test/basic.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEMsdWg9-EvDyW2L2:-KWcEMsdWg9-EvDyW2L3:bdeeba2) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/test/basic.html#L103)):*
> ```HTML
>       });
> 
>       it('should pass the placeholder attribute to the input tag', function(done) {
> ```

We can just run these tests sync and remove `done`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-date-picker.html, line 179 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEfTi3n44PnAtgWws:-KWcFTiPlaiS2gEm8svA:bb0mfbg) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/vaadin-date-picker.html#L179)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Please comment somewhere (commit line message, or a message here) the reason why we need to assign `always-float-label`
</details>
Also, in this case `always-float-label=[[placeholder]]` is sufficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker.html, line 179 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEGVLQgW14xTPSTk5:-KWcEGVLQgW14xTPSTk6:bb98uu3) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/vaadin-date-picker.html#L179)):*
> ```HTML
>         disabled$="[[disabled]]"
>         role="application"
>         always-float-label$={{placeholder}}>
> ```

Missing double quotes around attribute value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by limonte** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker.html, line 179 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEGVLQgW14xTPSTk5:-KWcPkKmPVWQTMYzBbue:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/vaadin-date-picker.html#L179)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Missing double quotes around attribute value.
</details>
Done.

---

*[vaadin-date-picker.html, line 179 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEfTi3n44PnAtgWws:-KWcPxpbCVuCfhvgi8lH:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/vaadin-date-picker.html#L179)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Also, in this case `always-float-label=[[placeholder]]` is sufficient.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/basic.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWcEMsdWg9-EvDyW2L2:-KWcTundyJEDNKVjEF-H:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/781423d757379212edb7e51121a4190cfd174cf9/test/basic.html#L103)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> We can just run these tests sync and remove `done`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker.html, line 278 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWdlSvqZT51bJIkWwiv:-KWdlSvr0rfQL4EdGsaA:b-yoij81) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7ee57380ac6446347142197cc41f2a2ee6009e76/vaadin-date-picker.html#L278)):*
> ```HTML
>          */
>         errorMessage: String,
> ```

Remember to add `placeholder` property here. Plain `placeholder: String` together with approriate JSDocs is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by limonte** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-date-picker.html, line 278 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-KWdlSvqZT51bJIkWwiv:-KWgaIsrJXC3oQ_OVlv_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/7ee57380ac6446347142197cc41f2a2ee6009e76/vaadin-date-picker.html#L278)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Remember to add `placeholder` property here. Plain `placeholder: String` together with approriate JSDocs is fine.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/293#-:-KWgpWflFcTpbXc4Ysis:bnfp4nl)*

**Pull request merged**
