### PR TITLE
Don't auto-focus overlay on open

### LINKED ISSUE #304: Focus animation is run when overlay is opened
### Description
The paper-input focus animation is run again when the overlay is opened.

### Expected outcome
Focus style stays, but the animation is not run.

### Actual outcome
Focus animation is run again, which causes unnecessary blinking.

### Live Demo
http://artur.app.fi/date-picker/

### Steps to reproduce
1. Focus the date picker with the tab key
2. Press arrow down → focus underline is animated

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #304

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/305)

### CODE REVIEW

**Comment by limonte** [comment]
The build is broken because of 3rd party package, related issue: https://gitlab.com/pushrocks/smartenv/issues/4

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/basic.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/305#-KX6ZKeSa5udgGvwlbGr:-KX6ZKeSa5udgGvwlbGs:b5wq85t) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2b39a78c94eca7581ef9682becf31df4fc050736/test/basic.html#L256)):*
> ```HTML
> 
>       it('should not auto focus overlay', function() {
>         expect(datepicker.$.dropdown.noAutoFocus).to.equal(true);
> ```

Is the light date picker covered here?

Maybe add a test for `<vaadin-date-picker-light>`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/305)*

**Comment by tomivirkki** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/basic.html, line 256 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/305#-KX6ZKeSa5udgGvwlbGr:-KX6_vj_f6tf92vaKYnD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/2b39a78c94eca7581ef9682becf31df4fc050736/test/basic.html#L256)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> Is the light date picker covered here?
> 
> Maybe add a test for `<vaadin-date-picker-light>`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/305)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/305#-:-KX7drwcmN8p6ek-6Orn:bnfp4nl)*

**Pull request merged**
