### PR TITLE
Make iron-dropdown 'modal' by adding backdrop

### LINKED ISSUE #289: Make overlay modal
Same issues as in combo box: https://github.com/vaadin/vaadin-combo-box/issues/343

We might want to consider this at the same time as we refactor the overlay to behave similarly as in combo box (place it under the `<body>`).

### PR DESCRIPTION
**Pull request by limonte**
Fixes #289

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/329)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/basic.html, line 294 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbEDH4smJRNYyV1hiiK:-KbEDH4smJRNYyV1hiiL:b-9uwsme) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c43ed099603adcc445bd82c7790f179432a42908/test/basic.html#L294)):*
> ```HTML
>         });
> 
>         /* it('should not realign on year/month scroll', function(done) {
> ```

Open a ticket with these commented tests, and add the issue number. Otherwise these comment might be here for ever.

---

*[test/dropdown.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbEE2hrhnLC0M8EDTkp:-KbEE2hrhnLC0M8EDTkq:b-hbnxoy) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c43ed099603adcc445bd82c7790f179432a42908/test/dropdown.html#L67)):*
> ```HTML
>           datepicker.async(function() {
>             var linkRect = a.getBoundingClientRect();
>             expect(document.elementFromPoint(linkRect.left, linkRect.top)).to.eql(datepicker.$.dropdown.backdropElement);
> ```

This test looks odd, I would expect that it checks the fact that the link is not clickable.
Actually anything that you put in the dom should be covered by the backdrop, so I would use any other element and not an anchor which makes the test hard to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/dropdown.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbEE2hrhnLC0M8EDTkp:-KbFHUw0dtL0ALFW4JFI:b-oeyb9c) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c43ed099603adcc445bd82c7790f179432a42908/test/dropdown.html#L67)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This test looks odd, I would expect that it checks the fact that the link is not clickable.
Actually anything that you put in the dom should be covered by the backdrop, so I would use any other element and not an anchor which makes the test hard to read.


</blockquote></details>

Done, link is replaced by span.

---

*[test/basic.html, line 294 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbEDH4smJRNYyV1hiiK:-KbFLox9_2YI3AObKqB7:b3svo36) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/c43ed099603adcc445bd82c7790f179432a42908/test/basic.html#L294)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Open a ticket with these commented tests, and add the issue number. Otherwise these comment might be here for ever.
</blockquote></details>

Separated to https://github.com/vaadin/vaadin-date-picker/pull/333

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-:-KbFRvJcEXMQMat3vmAu:bnfp4nl)*

**Comment by Saulis** [comment]
Slight problem I'm afraid: the input field and its buttons need to be accessible to be able to focus the input field and click on the clear icon: 
fhtatish5m

**Comment by tomivirkki** [comment]
*[test/dropdown.html, line 70 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbFUuXAcu_3mn_7acMA:-KbFUuXAcu_3mn_7acMB:bhcylgb) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fd0194c4ad82b8ddc361fed204ea7c813b4d4f7/test/dropdown.html#L70)):*
> ```HTML
>             document.body.removeChild(span);
>             done();
>           }, 220);
> ```

Can this test be made without a magic number timeout? Timeouts can easily cause those nasty flaky tests.

I'm not sure if we should even test this actually since it's `iron-overlay-behavior` feature and can be assumed tested by them already. We merely need to verify that we're using the feature (the flag is switched on).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-date-picker-behavior.html, line 319 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbFuy4LzbrDKAtIaI2x:-KbFuy4MTlm9JR-bVyxA:b4676nm) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fd0194c4ad82b8ddc361fed204ea7c813b4d4f7/vaadin-date-picker-behavior.html#L319)):*
> ```HTML
>       this._updateAlignmentAndPosition();
>       if (!this.disabled && !this.readonly) {
>         this.$.dropdown.backdropElement.style.opacity = 0;
> ```

There is a custom CSS property `--iron-overlay-backdrop-opacity` for that. Any reasons not to use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329)*

**Comment by limonte** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/dropdown.html, line 70 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbFUuXAcu_3mn_7acMA:-KbK1wnlWh22a5cQ_aqm:b-u06jeq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fd0194c4ad82b8ddc361fed204ea7c813b4d4f7/test/dropdown.html#L70)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Can this test be made without a magic number timeout? Timeouts can easily cause those nasty flaky tests.

I'm not sure if we should even test this actually since it's `iron-overlay-behavior` feature and can be assumed tested by them already. We merely need to verify that we're using the feature (the flag is switched on).
</blockquote></details>

Added explanation link to the magic timeout :) It's because the opacity transition, we should take element from point **after** transition is finished.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329)*

**Comment by tomivirkki** [comment]
*[test/dropdown.html, line 70 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329#-KbFUuXAcu_3mn_7acMA:-KbK4p81-4vJqFyfy99d:bg41ij0) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/1fd0194c4ad82b8ddc361fed204ea7c813b4d4f7/test/dropdown.html#L70)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Added explanation link to the magic timeout :) It's because the opacity transition, we should take element from point **after** transition is finished.
</blockquote></details>

Opacity is just a visual property. document.elementFromPoint() gets the element even if its opacity is 0 or 1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/329)*

**Comment by limonte** [comment]
I came with another approach suggested by @platosha : https://github.com/vaadin/vaadin-date-picker/pull/335

**Pull request closed without merging**
