### PR TITLE
Es5 demos

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/469)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[demo/date-picker-validators-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/469#-Kz3SCO2NcRCtNqzUDMJ:-Kz3SCO2NcRCtNqzUDMK:buitt9k) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4de45890b9b77e9f131b80fd93344c0bb5a07562/demo/date-picker-validators-demos.html#L37)):*
> ```HTML
>       }
>       static get template() {
>         if (Array.prototype.find) {
> ```

Hmm..for some reason this doesn't work (even though the same approach works in text-field demos). Maybe need to check user agent (for IE) instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/469)*

**Comment by samiheikki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/date-picker-validators-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/469#-Kz3SCO2NcRCtNqzUDMJ:-Kz4SZO82UhBrebGKDEz:bdiwazw) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4de45890b9b77e9f131b80fd93344c0bb5a07562/demo/date-picker-validators-demos.html#L37)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm..for some reason this doesn't work (even though the same approach works in text-field demos). Maybe need to check user agent (for IE) instead.
</blockquote></details>

That's right, it seems to be polyfilled somewhere. I've thought that we could rather check that is this feature polyfilled or native code. This works at the moment, but will break if some date-picker dependency is polyfilling that feature even tough it is natively supported. Let me know what you think about this. After deciding I can make the same change to text-field demo also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/469)*

**Comment by tomivirkki** [comment]
*[demo/date-picker-validators-demos.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/469#-Kz3SCO2NcRCtNqzUDMJ:-KzY3zKGTExhprsLGnFg:b-w3iwec) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/4de45890b9b77e9f131b80fd93344c0bb5a07562/demo/date-picker-validators-demos.html#L37)):*
> Array.prototype.find.toString()

Doesn't this error if `Array.prototype.find` isn't defined? Would this check do the trick https://stackoverflow.com/a/30692705 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/469)*

**Comment by web-padawan** [comment]
Closing in favour of #608

**Pull request closed without merging**
