### PR TITLE
Do not run overlay-closed handler on detach if closed

### LINKED ISSUE #513: date-picker shouldn't  run`validate` on detach
When detaching the date-picker, it runs the `_onOverlayClosed` even though the overlay might be already closed. The correct way is to run it only in the case the overlay is opened, but better should be not to call the observer directly but setting `opened = false` so as the observer will be called only in the case the overlay was opened.

so, this code
```
    detached() {
      this._onOverlayClosed();
    }
```

should be replaced with
```
    detached() {
      this.opened = false;
    }
```

### PR DESCRIPTION
**Pull request by manolo**
Fixes #513

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-date-picker/514)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-date-picker-mixin.html, line 601 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514#-L5jcghopYABE8Ewxtfd:-L5jcghpMrAnTjPTrcTF:bktth28) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f282dba33b63974e92c0b7cd399c72046fbc0fbd/src/vaadin-date-picker-mixin.html#L601)):*
> ```HTML
>     }
> 
>     detached() {
> ```

BTW this should be changed to use `disconnectedCallback`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-date-picker-mixin.html, line 601 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514#-L5jcghopYABE8Ewxtfd:-L5mcQCCzpL_46DSJnYz:b-o1c2pq) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f282dba33b63974e92c0b7cd399c72046fbc0fbd/src/vaadin-date-picker-mixin.html#L601)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW this should be changed to use `disconnectedCallback`
</blockquote></details>

BTW agree, note that there is a `disconnectedCallback` defined above already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-date-picker-mixin.html, line 601 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514#-L5jcghopYABE8Ewxtfd:-L5n9otpQRVRLnqZ4Hpj:byw9db6) ([raw file](https://github.com/vaadin/vaadin-date-picker/blob/f282dba33b63974e92c0b7cd399c72046fbc0fbd/src/vaadin-date-picker-mixin.html#L601)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW agree, note that there is a `disconnectedCallback` defined above already.
</blockquote></details>

Actually there is a `this.opened = false`  on that, so this block was not needed. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-date-picker/514#-:-L5nD7eExLOSWkViCAmS:bnfp4nl)*

**Pull request merged**
